// Overnight Registry Scan — New Candidate Names
// Scan Date: 2026-04-29
// Sources: 4 parallel web + Glean agents (50+ URLs checked, 80+ web searches)
// Total new candidates: 49
//
// These names were found to be live on eBay public surfaces or in official press
// but are NOT currently in the naming repository (or need review).
// Use this file to triage additions to enriched-consolidated-DEDUPLICATED.ts

export interface RegistryScanRecord {
  id: string
  name: string
  entity_type: "Product" | "Feature" | "Program" | "Event" | "Badge" | "Campaign" | "Brand" | "Platform"
  hierarchy_level: "umbrella" | "vertical" | "product" | "feature" | "variant" | "event" | "regional"
  parent_id?: string
  market: string[]
  customer_visibility: "High" | "Medium" | "Low" | "Internal"
  live_status: "live" | "pilot" | "rolling_out" | "planned" | "one_off"
  launch_date?: string
  repository_status: "candidate_new" | "verify_before_adding" | "campaign_not_product"
  naming_recommendation: "add" | "add_as_feature" | "investigate" | "campaign_register"
  evidence_quality: "A" | "B" | "C" | "D"
  evidence_sources: string[]
  name_class: "Product Name" | "Feature Name" | "Functional Label" | "Internal Term"
  value_prop?: string
  value_territories?: string[]
  strategic_role?: string[]
  notes?: string
  flagged_for_review: boolean
  flag_reason?: string
  scan_date: string
}

export const NEW_CANDIDATES: RegistryScanRecord[] = [

  // ─── AI & LISTING TOOLS ────────────────────────────────────────────────────

  {
    id: "ai-activate",
    name: "AI Activate",
    entity_type: "Program",
    hierarchy_level: "product",
    parent_id: "ebay-for-business",
    market: ["UK"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2025-11-01",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebayinc.com/stories/press-room/uk/ebay-launches-ai-activate-programme-with-openai/",
      "https://www.ebay.co.uk/sellercentre/grow-your-sales/ai-activate",
    ],
    name_class: "Product Name",
    value_prop: "Free access to OpenAI tools and eBay-built GPTs for up to 10,000 small UK business sellers for 12 months, valued at over £3 million.",
    value_territories: ["value", "convenience"],
    strategic_role: ["reusable-capability", "high-visibility"],
    notes: "Developed in partnership with OpenAI. UK-market only. Announced at eBay Open 2025, launched November 2025. Includes ChatGPT Enterprise access and custom eBay-built GPTs.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "ebay-ai-platform",
    name: "eBay.ai",
    entity_type: "Platform",
    hierarchy_level: "umbrella",
    market: ["US"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2025-04-01",
    repository_status: "candidate_new",
    naming_recommendation: "investigate",
    evidence_quality: "B",
    evidence_sources: [
      "https://paramark.com/news/ebay-new-features-step-forward",
    ],
    name_class: "Product Name",
    value_prop: "eBay's AI platform brand, surfacing as 'Ask eBay.ai' in Seller Hub and as a buyer-facing AI shopping assistant.",
    value_territories: ["convenience", "speed"],
    strategic_role: ["high-visibility", "long-term", "multi-market"],
    notes: "Appears both as buyer-facing AI assistant and as seller-side interface label (Finances Copilot surfaces as 'Ask eBay.ai'). ebay.ai domain likely active. Evidence is aggregated reporting, not standalone press release.",
    flagged_for_review: true,
    flag_reason: "Verify whether eBay.ai is a named product or a URL/interface label. May not merit its own registry entry.",
    scan_date: "2026-04-29",
  },

  {
    id: "ai-assistant-for-messaging",
    name: "AI Assistant",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "seller-hub",
    market: ["US", "UK"],
    customer_visibility: "Medium",
    live_status: "live",
    launch_date: "2025-08-12",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebay.com/sellercenter/news/2025-august/ai-responses",
      "https://www.ebayinc.com/stories/news/ebay-launches-seller-tools-to-save-time-boost-profits-and-build-trust/",
    ],
    name_class: "Feature Name",
    value_prop: "Drafts suggested replies to common buyer questions using live listing details and order info. Sellers review before sending.",
    value_territories: ["speed", "convenience"],
    strategic_role: ["reusable-capability"],
    notes: "Announced at eBay Open 2025. Does not auto-send. URL path /ai-responses suggests internal label may differ. Separate from Magical Listing — this is for buyer messaging, not listing creation.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "finances-copilot",
    name: "Finances Copilot",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "seller-hub",
    market: ["US"],
    customer_visibility: "Medium",
    live_status: "pilot",
    launch_date: "2025-08-12",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "B",
    evidence_sources: [
      "https://www.valueaddedresource.net/ebay-finances-copilot-ai/",
    ],
    name_class: "Feature Name",
    value_prop: "AI chat in Seller Hub Payments tab for querying financial data in natural language — holds, fees, payouts, earnings by period.",
    value_territories: ["transparency", "convenience"],
    strategic_role: ["reusable-capability"],
    notes: "Beta at eBay Open 2025; broader rollout early 2026. Also appears as 'Finances Co-Pilot' — verify canonical capitalization. Surfaces in UI as 'Ask eBay.ai'. No Microsoft Copilot relation.",
    flagged_for_review: true,
    flag_reason: "Verify canonical capitalization: 'Finances Copilot' vs 'Finances Co-Pilot'",
    scan_date: "2026-04-29",
  },

  {
    id: "inventory-mapping-api",
    name: "Inventory Mapping API",
    entity_type: "Product",
    hierarchy_level: "product",
    parent_id: "seller-hub",
    market: ["US"],
    customer_visibility: "Low",
    live_status: "live",
    launch_date: "2025-08-12",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebayinc.com/stories/news/ebay-launches-seller-tools-to-save-time-boost-profits-and-build-trust/",
    ],
    name_class: "Feature Name",
    value_prop: "AI-powered API generating optimized titles, item specifics, and descriptions from images and product identifiers for high-volume sellers.",
    value_territories: ["speed", "value"],
    strategic_role: ["reusable-capability"],
    notes: "Developer/API-facing product for large-scale sellers. Not consumer-facing. Available to select U.S. merchants as of August 2025.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  // ─── SELLER TOOLS & FEATURES ───────────────────────────────────────────────

  {
    id: "offers-in-messaging",
    name: "Offers in Messaging",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "best-offer",
    market: ["US"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2025-08-12",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebayinc.com/stories/news/ebay-launches-seller-tools-to-save-time-boost-profits-and-build-trust/",
    ],
    name_class: "Feature Name",
    value_prop: "Send, receive, counter, and accept offers directly within the messaging thread without switching screens.",
    value_territories: ["convenience", "speed"],
    strategic_role: ["reusable-capability"],
    notes: "Announced at eBay Open 2025 (August 12, 2025). Mobile app and web. Tracks past offers and messages in one place. Distinct from existing Best Offer feature — this is in-thread.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "your-cost-field",
    name: "Your cost",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "seller-hub",
    market: ["US"],
    customer_visibility: "Low",
    live_status: "live",
    launch_date: "2025-08-12",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "B",
    evidence_sources: [
      "https://www.ebayinc.com/stories/news/ebay-launches-seller-tools-to-save-time-boost-profits-and-build-trust/",
    ],
    name_class: "Functional Label",
    value_prop: "Optional field in listing flow and earnings reports for tracking cost of goods sold, enabling smarter pricing without separate spreadsheets.",
    value_territories: ["transparency", "value"],
    strategic_role: ["reusable-capability"],
    notes: "Official product name is 'Your cost' (lowercase). NOT 'Track Your Costs'. Sellers reported concerns about sharing cost data with eBay.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "automated-positive-feedback",
    name: "Automated Feedback",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "seller-hub",
    market: ["US", "UK"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2025-09-01",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebayinc.com/stories/news/ebay-launches-seller-tools-to-save-time-boost-profits-and-build-trust/",
      "https://www.3dsellers.com/blog/ebay-automatic-feedback",
    ],
    name_class: "Feature Name",
    value_prop: "Automatically leaves positive feedback for sellers who deliver on time with no issues, if the buyer hasn't left feedback within 7 days of delivery.",
    value_territories: ["trust", "convenience"],
    strategic_role: ["reusable-capability"],
    notes: "Also called 'Automatic Positive Feedback' in some sources. US rollout Sep 2025 (UK earlier). Labeled 'automated feedback' in UI with filter option. Announced at eBay Open 2025.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "seller-inr-protection",
    name: "Seller INR Protection",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "seller-protections",
    market: ["US"],
    customer_visibility: "Low",
    live_status: "live",
    launch_date: "2025-10-01",
    repository_status: "candidate_new",
    naming_recommendation: "investigate",
    evidence_quality: "B",
    evidence_sources: [
      "https://www.valueaddedresource.net/ebay-seller-protections-inr-as-is-returns-automatic-feedback/",
    ],
    name_class: "Feature Name",
    value_prop: "If seller ships on time with eBay labels and tracking shows delivery after a refund is issued, eBay reimburses the seller for item cost and removes resulting negative feedback.",
    value_territories: ["protection", "trust"],
    strategic_role: ["reusable-capability"],
    notes: "Requires eBay labels for qualification. INR = Item Not Received. The official name is described as 'improvements to handle INR claims' — 'Seller INR Protection' may not be the branded name. Investigate official name.",
    flagged_for_review: true,
    flag_reason: "Verify official branded name — may not be 'Seller INR Protection'",
    scan_date: "2026-04-29",
  },

  {
    id: "issue-resolution-center",
    name: "Issue Resolution Center",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "seller-hub",
    market: ["US", "UK", "AU", "CA"],
    customer_visibility: "Medium",
    live_status: "rolling_out",
    launch_date: "2026-03-01",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebay.com/sellercenter/news/2026-april/issue-resolution-center-launch",
    ],
    name_class: "Feature Name",
    value_prop: "Centralized seller tool for managing compliance tasks including ID verification, negative balance, tax information, and policy issues with step-by-step remediation.",
    value_territories: ["convenience", "transparency"],
    strategic_role: ["reusable-capability"],
    notes: "Official confirmed name. Rolling out globally March–April 2026. Note: third-party sources sometimes call it 'Seller Resolution Center' — incorrect. UK spelling: 'Issue Resolution Centre'.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "team-access",
    name: "Team Access",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "seller-hub",
    market: ["US", "UK"],
    customer_visibility: "Medium",
    live_status: "live",
    launch_date: "2025-10-01",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.valueaddedresource.net/ebay-us-october-2025-seller-update/",
      "https://www.ebay.com/sellercenter/news/2025-october/optimize-business",
    ],
    name_class: "Feature Name",
    value_prop: "Allows sellers to share account tasks with multiple team members safely from a single dashboard, with granular permission controls.",
    value_territories: ["convenience"],
    strategic_role: ["reusable-capability"],
    notes: "Launched in October 2025 Seller Update (US + UK). Team members receive email invitations with 4-day acceptance window. Activity audit dashboard included.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "seller-hub-discounts",
    name: "Seller Hub Discounts",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "seller-hub",
    market: ["US", "UK", "DE", "AU"],
    customer_visibility: "Medium",
    live_status: "live",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebay.com/sellercenter/growth/seller-hub-promotions",
    ],
    name_class: "Feature Name",
    value_prop: "Seller promotion management tool with Volume Pricing, Sale Events, Coupons, Automated Offers, Order Discounts, and Shipping Discounts.",
    value_territories: ["value", "convenience"],
    strategic_role: ["reusable-capability"],
    notes: "RENAMED from 'Promotions Manager'. The old URL pages.ebay.com/promotionsmanager redirects to /sellercenter/growth/seller-hub-promotions where the tool is now consistently called 'Seller Hub Discounts'. Add as canonical name; mark Promotions Manager as Legacy.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  // ─── PROGRAMS & SELLER SUPPORT ────────────────────────────────────────────

  {
    id: "ambassador-program",
    name: "eBay Ambassador Program",
    entity_type: "Program",
    hierarchy_level: "product",
    parent_id: "ebay-partner-network",
    market: ["US", "UK"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2025-04-01",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebayinc.com/stories/news/with-the-ebay-ambassador-program-everyone-can-be-an-affiliate/",
      "https://www.ebay.com/sellercenter/news/2025-october/ambassador-program",
    ],
    name_class: "Product Name",
    value_prop: "Self-service affiliate program open to all US/UK buyers, sellers, and creators to earn up to 7.5% commission by sharing eBay listings via personalized storefronts.",
    value_territories: ["value", "community"],
    strategic_role: ["high-visibility", "long-term", "multi-market"],
    notes: "Open to all US users (no follower minimum). Limited launch April 2025; fully open August 26, 2025 US; expanded to UK. Available at ambassador.ebay.com. Evolved from eBay Partner Network (ePN), which remains live as a separate track.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "pre-loved-partner-program",
    name: "eBay Pre-Loved Partner Program",
    entity_type: "Program",
    hierarchy_level: "product",
    parent_id: "ebay-fashion",
    market: ["US"],
    customer_visibility: "Medium",
    live_status: "rolling_out",
    launch_date: "2025-04-01",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebay.com/sellercenter/selling/what-to-sell/pre-loved-partner-program",
    ],
    name_class: "Product Name",
    value_prop: "Credentialing program for top pre-loved fashion sellers with a dedicated badge, increased search visibility, and access to a dedicated support team.",
    value_territories: ["trust", "community"],
    strategic_role: ["high-visibility"],
    notes: "Business sellers only. Badge displays on View Item pages. Slow rollout — some accepted sellers reported delays in badge display. Linked to broader eBay Pre-Loved Fashion Week initiative.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "circular-fashion-fund",
    name: "Circular Fashion Fund",
    entity_type: "Program",
    hierarchy_level: "product",
    parent_id: "ebay-impact",
    market: ["US", "UK", "EU"],
    customer_visibility: "Low",
    live_status: "live",
    launch_date: "2022-10-01",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebayinc.com/stories/news/ebay-expands-circular-fashion-fund-across-europe-and-north-america/",
    ],
    name_class: "Product Name",
    value_prop: "Annual grant awarding $50K to 8 finalists plus $300K investment from eBay Ventures to one global winner in sustainable fashion. Expanded to EU, Switzerland, Canada in 2026.",
    value_territories: ["community", "value"],
    strategic_role: ["long-term", "high-visibility"],
    notes: "Program originated 2022; significant 2026 expansion to new markets makes it newly relevant for those regions. Fourth year of program.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  // ─── MOTORS & AUTOMOTIVE ──────────────────────────────────────────────────

  {
    id: "secure-purchase",
    name: "Secure Purchase",
    entity_type: "Product",
    hierarchy_level: "product",
    parent_id: "ebay-motors",
    market: ["US"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2024-09-01",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://pages.ebay.com/secure-purchase/",
      "https://www.ebayinc.com/stories/news/ebay-unveils-new-checkout-solution-for-vehicle-transactions/",
      "https://www.prnewswire.com/news-releases/ebay-unveils-new-checkout-solution-for-vehicle-transactions-302516196.html",
    ],
    name_class: "Product Name",
    value_prop: "End-to-end vehicle transaction solution managing payment, financing, registration, ownership transfer, and transport in one integrated flow — no DMV visit required.",
    value_territories: ["trust", "protection", "convenience"],
    strategic_role: ["high-visibility", "long-term"],
    notes: "Powered by Caramel Dealer Services LLC (eBay subsidiary, acquired 2024). $25 buyer fee. Includes Vehicle Purchase Protection up to $100,000 at no extra charge. Available for cars, trucks, boats, ATVs, motorcycles, RVs, commercial vehicles. 80% of eBay vehicle purchases cross state lines.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "vehicle-purchase-protection",
    name: "Vehicle Purchase Protection",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "secure-purchase",
    market: ["US"],
    customer_visibility: "High",
    live_status: "live",
    repository_status: "candidate_new",
    naming_recommendation: "investigate",
    evidence_quality: "A",
    evidence_sources: [
      "https://pages.ebay.com/motors/buy/purchase-protection/",
      "https://pages.ebay.com/secure-purchase/",
    ],
    name_class: "Product Name",
    value_prop: "Buyer protection covering vehicle purchases up to $100,000 when using Secure Purchase; up to $50,000 for eligible purchases not using Secure Purchase.",
    value_territories: ["protection", "trust"],
    strategic_role: ["reusable-capability"],
    notes: "May already be in registry as VPP or Vehicle Purchase Protection. VPP $50K for standard, $100K with Secure Purchase. Confirm whether existing registry entry covers this or if it's separate.",
    flagged_for_review: true,
    flag_reason: "Check if 'Vehicle Purchase Protection' already exists in registry before adding",
    scan_date: "2026-04-29",
  },

  {
    id: "fitment-plus-auto",
    name: "Fitment Plus Auto",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "ebay-fitment-plus",
    market: ["US"],
    customer_visibility: "Low",
    live_status: "live",
    launch_date: "2025-10-20",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebay.com/sellercenter/news/2025-october/fitment-plus-auto",
      "https://www.valueaddedresource.net/ebay-us-october-2025-seller-update/",
    ],
    name_class: "Feature Name",
    value_prop: "Automatically enrolls Motors P&A sellers and updates listings with eBay-maintained vehicle compatibility data. Eliminates manual fitment data management.",
    value_territories: ["speed", "convenience"],
    strategic_role: ["reusable-capability"],
    notes: "Also abbreviated 'FPA'. Distinct from parent 'eBay Fitment Plus' program — this is an auto-enrollment expansion launched October 2025, expanded to all sellers April 2026. Sellers can opt out via Motors Selling Preferences.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  // ─── EBAY LIVE & COMMERCE EVENTS ──────────────────────────────────────────

  {
    id: "ebay-live-on-tour",
    name: "eBay Live on Tour",
    entity_type: "Product",
    hierarchy_level: "variant",
    parent_id: "ebay-live",
    market: ["US"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2025-09-01",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "B",
    evidence_sources: [
      "https://nycplugged.com/calendar/pokemon-ebay-live-on-tour/",
      "https://www.ebayinc.com/stories/news/ebay-celebrates-30-years-of-creating-economic-opportunity-for-all-as-it-reinvents-the-future-of-ecommerce/",
    ],
    name_class: "Product Name",
    value_prop: "In-person live shopping event series at U.S. venues, pairing digital eBay Live programming with physical collector experiences.",
    value_territories: ["community", "selection"],
    strategic_role: ["high-visibility"],
    notes: "Sub-brand of eBay Live. Used for 30th anniversary events September 2025 and Pokémon Day NYC February 2026. Format: collector community block parties with trading tables, PSA grading, live programming.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "video-receipt",
    name: "Video Receipt",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "ebay-live",
    market: ["US"],
    customer_visibility: "High",
    live_status: "live",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "A",
    evidence_sources: ["https://www.ebay.com/help/buying/ebay-live/ebay-live"],
    name_class: "Feature Name",
    value_prop: "Short video clip sent to buyer confirming their live auction purchase, showing the exact item won.",
    value_territories: ["trust", "transparency"],
    strategic_role: ["reusable-capability"],
    notes: "Named feature within eBay Live per official eBay help page. Confirmed on live rendered help page.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "soft-close",
    name: "Soft Close",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "ebay-live",
    market: ["US"],
    customer_visibility: "High",
    live_status: "live",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "A",
    evidence_sources: ["https://www.ebay.com/help/buying/ebay-live/ebay-live"],
    name_class: "Feature Name",
    value_prop: "Auction mechanic that resets the countdown timer when new bids come in near close, preventing sniping and extending competitive bidding.",
    value_territories: ["trust", "community"],
    strategic_role: ["reusable-capability"],
    notes: "Named on official eBay Live help page. Customer-facing mechanic name.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  // ─── COLLECTIBLES & VAULT ─────────────────────────────────────────────────

  {
    id: "psa-vault",
    name: "PSA Vault",
    entity_type: "Product",
    hierarchy_level: "product",
    parent_id: "ebay-vault",
    market: ["US"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2024-05-16",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://investors.ebayinc.com/investor-news/press-release-details/2024/",
      "https://www.ebay.com (My eBay navigation menu shows 'PSA Vault')",
    ],
    name_class: "Product Name",
    value_prop: "Secure graded trading card vault storage operated by PSA (Collectors), accessible and transactable through eBay with integrated authentication.",
    value_territories: ["trust", "protection"],
    strategic_role: ["long-term"],
    notes: "eBay sold vault operations to PSA in May 2024 (as part of Goldin acquisition swap). 'PSA Vault' now appears in My eBay navigation menu. 'eBay Vault' brand name remains at ebay.com/vault. Send to PSA Vault checkout feature launched November 2025. COMPLEX: both names are in use simultaneously.",
    flagged_for_review: true,
    flag_reason: "Relationship to existing 'eBay Vault' entry needs clarification. Are these the same product with dual naming, or distinct?",
    scan_date: "2026-04-29",
  },

  {
    id: "my-collection",
    name: "My Collection",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "ebay-vault",
    market: ["US", "FR", "IT"],
    customer_visibility: "Medium",
    live_status: "live",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebay.com (My eBay navigation menu)",
      "https://www.ebay.fr (My eBay navigation)",
      "https://www.ebay.it (My eBay navigation)",
    ],
    name_class: "Feature Name",
    value_prop: "Digital portfolio tool for managing collectibles, linked to eBay Vault and PSA Vault. Appears in My eBay menu across US, French, and Italian sites.",
    value_territories: ["community"],
    strategic_role: ["reusable-capability"],
    notes: "Appears in My eBay navigation consistently. Different from 'My Garage' (automotive). Confirmed on US, FR, IT.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  // ─── FINANCING & CAPITAL ──────────────────────────────────────────────────

  {
    id: "flexible-cash-advance",
    name: "Flexible Cash Advance",
    entity_type: "Product",
    hierarchy_level: "product",
    parent_id: "ebay-seller-capital",
    market: ["US"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2024-09-26",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebayinc.com/stories/news/ebay-and-liberis-introduce-flexible-cash-advance-a-new-way-for-sellers-to-expand-and-grow-their-businesses/",
    ],
    name_class: "Product Name",
    value_prop: "Revolving credit line ($5K–$2M) for US sellers with ongoing access without reapplication, repaid as a percentage of gross sales.",
    value_territories: ["value"],
    strategic_role: ["long-term", "multi-market"],
    notes: "Via partner Liberis. Launched September 2024. Distinct from Business Cash Advance (lump sum) and Term Loans. UK equivalent: Flexible Growth Financing.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "flexible-growth-financing",
    name: "Flexible Growth Financing",
    entity_type: "Product",
    hierarchy_level: "product",
    parent_id: "ebay-seller-capital",
    market: ["UK"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2026-04-06",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebayinc.com/stories/press-room/uk/ebay-and-liberis-launch-flexible-growth-financing-for-uk-small-businesses/",
    ],
    name_class: "Product Name",
    value_prop: "UK flexible credit line for small business sellers, accessed in full or in stages. Funding decisions within 24 hours.",
    value_territories: ["value"],
    strategic_role: ["long-term"],
    notes: "UK-market specific name (US equivalent: Flexible Cash Advance). Via Liberis. Available from April 6, 2026.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  // ─── ADVERTISING ──────────────────────────────────────────────────────────

  {
    id: "promoted-listings-priority-video",
    name: "Promoted Listings Priority Video Ads",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "promoted-listings-priority",
    market: ["US", "UK", "DE", "CA", "AU"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2026-04-15",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebay.com/sellercenter/news/2026-april/video-ads-format-update",
      "https://www.valueaddedresource.net/ebay-april-2026-seller-news/",
    ],
    name_class: "Feature Name",
    value_prop: "Video ad format within Promoted Listings Priority (CPC) for showcasing items in motion with video-specific metrics.",
    value_territories: ["selection"],
    strategic_role: ["reusable-capability"],
    notes: "Sellers upload up to 45-second MP4/MOV videos. Includes view rates, completion rate. First launched in AU; expanded to US, UK, DE, CA in April 2026.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "promoted-stores-custom",
    name: "Promoted Stores Custom",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "promoted-stores",
    market: ["US"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2026-01-01",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "B",
    evidence_sources: [
      "https://www.valueaddedresource.net/ebay-january-2026-seller-news/",
    ],
    name_class: "Feature Name",
    value_prop: "CPC variant of Promoted Stores allowing sellers to manually select up to 1,000 listings with custom landing page destinations including eBay Live events.",
    value_territories: ["selection", "value"],
    strategic_role: ["reusable-capability"],
    notes: "Distinct from standard Promoted Stores (algorithm-driven). Allows linking to eBay Live events and Ambassador storefronts as destinations. Approximate January 2026 launch.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  // ─── REGIONAL & INTERNATIONAL ─────────────────────────────────────────────

  {
    id: "simple-delivery-uk",
    name: "Simple Delivery",
    entity_type: "Product",
    hierarchy_level: "product",
    parent_id: "ebay-shipping",
    market: ["UK"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2025-04-15",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebay.co.uk/sellercentre/postage/simple-delivery",
      "https://www.valueaddedresource.net/ebay-uk-simple-delivery-mandate-april-2025/",
    ],
    name_class: "Product Name",
    value_prop: "Mandatory label-based shipping service for UK private sellers, with Evri and Royal Mail as integrated carriers, simplified rates, and consolidated logistics.",
    value_territories: ["speed", "convenience"],
    strategic_role: ["long-term", "multi-market"],
    notes: "MANDATORY for UK private sellers as of April 15, 2025 — major policy change. Dedicated UK Seller Centre page. Significant coverage in seller community. UK-only program.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "ebay-extra-fr-it",
    name: "eBay Extra",
    entity_type: "Product",
    hierarchy_level: "product",
    parent_id: "ebay-loyalty",
    market: ["FR", "IT"],
    customer_visibility: "High",
    live_status: "live",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebay.it/ebayextra",
    ],
    name_class: "Product Name",
    value_prop: "Free loyalty points program on eBay France and eBay Italy — earn 1 point per €1 spent, redeemable for discounts on future purchases.",
    value_territories: ["value", "community"],
    strategic_role: ["long-term"],
    notes: "Available at ebay.it/ebayextra and ebay.fr. Points expire 60 days after earning if no further purchases. NOT the US eBay Extras Mastercard (separate credit card via Synchrony Bank). FR+IT only.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "ebay-reparation-fr",
    name: "eBay réparation",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "consommation-raisonnee",
    market: ["FR"],
    customer_visibility: "Medium",
    live_status: "live",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "B",
    evidence_sources: [
      "https://pages.ebay.fr/consommation-raisonnee/",
    ],
    name_class: "Feature Name",
    value_prop: "French repair tool providing diagnostics, parts search, and video tutorials to support product repair as part of eBay France's circular economy initiative.",
    value_territories: ["value"],
    strategic_role: ["one-off"],
    notes: "Named sub-tool within eBay France's Consommation Raisonnée hub. No standalone URL verified beyond the parent page.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  // ─── ACQUIRED BRANDS ──────────────────────────────────────────────────────

  {
    id: "depop",
    name: "Depop",
    entity_type: "Brand",
    hierarchy_level: "umbrella",
    market: ["US", "UK", "EU"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2026-02-18",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://investors.ebayinc.com/investor-news/press-release-details/2026/eBay-to-Acquire-Depop-from-Etsy/default.aspx",
    ],
    name_class: "Product Name",
    value_prop: "Mobile-first C2C fashion marketplace for Gen Z buyers (90% under 34), with ~$1B annual GMS, 7M active buyers, and 3M+ active sellers.",
    value_territories: ["community", "selection", "value"],
    strategic_role: ["inherited-M&A", "high-visibility", "long-term"],
    notes: "eBay acquiring Depop from Etsy for ~$1.2B. Announced February 18, 2026; deal subject to regulatory approval (expected close Q2 2026). Depop will retain its name and brand. Founded 2011. eBay's second major fashion acquisition (after Vestiaire Collective investment).",
    flagged_for_review: true,
    flag_reason: "Acquisition not yet closed as of scan date (April 2026). Confirm close status before adding to registry.",
    scan_date: "2026-04-29",
  },

  {
    id: "tise",
    name: "Tise",
    entity_type: "Brand",
    hierarchy_level: "umbrella",
    market: ["NO", "SE", "DK"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2025-09-01",
    repository_status: "candidate_new",
    naming_recommendation: "add",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebayinc.com/ (acquisition announcement September 2025)",
    ],
    name_class: "Product Name",
    value_prop: "Nordic C2C secondhand fashion and interior marketplace with ~2.5M users, acquired by eBay from Tise founders for approximately $130M.",
    value_territories: ["community", "value", "selection"],
    strategic_role: ["inherited-M&A", "long-term"],
    notes: "Oslo-based, founded 2014. eBay Ventures was early investor since 2022. Acquisition announced September 2025; expected close Q4 2025. Likely closed by April 2026. Operates as standalone brand. Contributes ~1M active buyers to eBay's count.",
    flagged_for_review: true,
    flag_reason: "Confirm acquisition close date and whether Tise is operating standalone or integrating",
    scan_date: "2026-04-29",
  },

  // ─── AI & DISCOVERY FEATURES ──────────────────────────────────────────────

  {
    id: "shop-the-look",
    name: "Shop the Look",
    entity_type: "Feature",
    hierarchy_level: "feature",
    parent_id: "ebay-fashion",
    market: ["US", "UK"],
    customer_visibility: "High",
    live_status: "live",
    launch_date: "2024-04-09",
    repository_status: "candidate_new",
    naming_recommendation: "add_as_feature",
    evidence_quality: "B",
    evidence_sources: [
      "https://techcrunch.com/2024/04/09/ebay-adds-an-ai-powered-shop-the-look-feature-to-its-ios-app/",
    ],
    name_class: "Feature Name",
    value_prop: "AI-powered buyer discovery showing complete fashion outfits with interactive hotspots to find similar listings for each item.",
    value_territories: ["selection", "convenience"],
    strategic_role: ["reusable-capability"],
    notes: "iOS app (US + UK). Targets users who viewed 10+ fashion items in past 180 days. Available on homepage and fashion landing page. Launched April 2024 but continued in 2025.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  // ─── CAMPAIGNS & EVENTS (not sustained product names) ─────────────────────

  {
    id: "48-hours-of-drops",
    name: "48 Hours of Drops",
    entity_type: "Event",
    hierarchy_level: "event",
    parent_id: "ebay-live",
    market: ["US"],
    customer_visibility: "High",
    live_status: "one_off",
    launch_date: "2026-03-26",
    repository_status: "campaign_not_product",
    naming_recommendation: "campaign_register",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebayinc.com/stories/news/ebay-launches-48-hour-livestream-shopping-event-featuring-celebrities-rare-finds-and-1-starting-bids/",
    ],
    name_class: "Functional Label",
    value_prop: "48-hour consecutive eBay Live shopping event with celebrity sellers, $1 starting bids across fashion and collectibles.",
    value_territories: ["selection", "value", "community"],
    strategic_role: ["high-visibility", "one-off"],
    notes: "Official eBay Inc. press release. Featured La La Anthony, Jared McCain, Goldin, Xolo Maridueña. Could become a recurring event format. Campaign/event classification — likely not a durable product name.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

  {
    id: "the-30-30-collection",
    name: "The 30/30 Collection",
    entity_type: "Campaign",
    hierarchy_level: "event",
    parent_id: "ebay-live",
    market: ["US"],
    customer_visibility: "High",
    live_status: "one_off",
    launch_date: "2026-02-27",
    repository_status: "campaign_not_product",
    naming_recommendation: "campaign_register",
    evidence_quality: "A",
    evidence_sources: [
      "https://www.ebayinc.com/stories/news/ebay-unveils-pokemon-day-auction-celebrating-30-years-of-iconic-collectibles/",
    ],
    name_class: "Functional Label",
    value_prop: "Curated collection of 30 iconic Pokémon collectibles auctioned exclusively on eBay Live for Pokémon's 30th anniversary.",
    value_territories: ["community", "selection"],
    strategic_role: ["one-off"],
    notes: "One-time event name (Pokémon Day, February 27, 2026). Campaign classification — not a durable product name.",
    flagged_for_review: false,
    scan_date: "2026-04-29",
  },

]

export default NEW_CANDIDATES
