/**
 * Output Formatter Module — deterministic output rendering (NO LLM)
 *
 * Input:        VerdictOutput + CompiledBrief + GateEvaluation + ScoringResult
 * Output:       Formatted strings — Markdown, Slack blocks, MachinePayload JSON
 * Side effects: none — pure TypeScript string building, no I/O
 * Called by:    lib/orchestrator.ts  (FORMATTING phase)
 *               app/api/evaluate-v2/route.ts  (toMachinePayload)
 * Tested by:    tests/formatter.test.ts
 */

import type { VerdictOutput, EvaluationResult, MachinePayload } from "../models/verdict";
import type { CompiledBrief } from "../models/brief";
import type { GateEvaluation } from "../models/gates";
import type { ScoringResult } from "../models/scoring";

/**
 * Format verdict as markdown
 */
export function formatAsMarkdown(verdict: VerdictOutput): string {
  let output = `### ${verdict.title}\n\n`;

  // Summary - now with coaching explanations (no bullets, just paragraphs)
  output += verdict.summary.join('\n') + '\n\n';

  // Score table (if present)
  if (verdict.score_table) {
    output += `### Naming Score Breakdown\n\n`;
    output += `${verdict.score_table}\n\n`;
  }

  // Audit table
  output += `### Decision Logic Audit\n\n`;
  output += `${verdict.audit_table}\n\n`;

  // Disclaimer
  output += `---\n\n`;
  output += `_This assessment is AI-generated and intended for preliminary governance guidance. Please verify all data independently and consult with Brand team for final naming decisions._\n\n`;

  output += `*** END OF REPORT ***\n`;

  return output;
}

/**
 * Format evaluation result as Slack payload
 */
export function formatAsSlack(
  result: EvaluationResult,
  brief: CompiledBrief
): Record<string, unknown> {
  const { verdict, gateEvaluation, scoringResult } = result;

  // Build key facts
  const keyFacts = [
    brief.offering_description && `• **Offering:** ${brief.offering_description}`,
    brief.target_customers && `• **Target:** ${brief.target_customers}`,
    brief.target_geographies && `• **Markets:** ${brief.target_geographies}`,
    brief.value_proposition && `• **Value Prop:** ${brief.value_proposition}`,
    brief.timing && `• **Timing:** ${brief.timing}`,
  ].filter(Boolean).join('\n');

  // Build gate checks
  const gateChecks = Object.entries(gateEvaluation.gate_results)
    .map(([key, gate]) => {
      const status = gate.status === "Pass" ? "PASS" : gate.status === "Fail" ? "FAIL" : "PENDING";
      return `> **${key} (${gate.label}):** ${status}\n> *Rationale:* ${gate.reasoning}`;
    })
    .join('\n\n');

  // Build score table (if applicable)
  let scoreTable = '';
  if (scoringResult && verdict.path === "PATH_C") {
    const { breakdown, total } = scoringResult.scores;
    scoreTable = `
**Audit Log: Naming Score (60+ needed to pass)**
\`\`\`
Factor                    Points
--------------------------------
Standalone Behavior       ${breakdown.standalone}
Central/Long-lived        ${breakdown.longevity}
Formal Requirement        ${breakdown.legal}
Global Viability          ${breakdown.global}
Clarity Lift              ${breakdown.clarity}
Portfolio Risk            ${breakdown.portfolio_risk}
Trademark Risk            ${breakdown.trademark_risk}
--------------------------------
TOTAL SCORE               ${total}/70
\`\`\`
`;
  }

  // Build Slack message
  const text = `**Naming Decision**

**${verdict.title}**

**Key Facts**
${keyFacts}

**Decision Logic & Rationale**
${verdict.summary.join('\n')}

**Audit Log: Gate Checks**
${gateChecks}

${scoreTable}

_Generated by eBay Naming Agent_`;

  return {
    text,
    blocks: [
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: text,
        },
      },
    ],
  };
}

/**
 * Format brief as markdown table
 */
export function formatBriefAsMarkdown(brief: CompiledBrief): string {
  const fields = [
    { label: "Offering Description", value: brief.offering_description },
    { label: "Value Proposition", value: brief.value_proposition },
    { label: "Benefits", value: brief.benefits },
    { label: "Job(s) to be Done", value: brief.jobs_to_be_done },
    { label: "Example Use Case(s)", value: brief.example_use_cases },
    { label: "Pain Point(s)", value: brief.pain_points },
    { label: "Target Customer(s)", value: brief.target_customers },
    { label: "Target Geographies", value: brief.target_geographies },
    { label: "Customer Research and Competitive Insights", value: brief.customer_research_and_competitive_insights },
    { label: "Brand Considerations", value: brief.brand_considerations },
    { label: "Naming Request", value: brief.naming_request },
    { label: "Primary Contact", value: brief.primary_contact },
    { label: "Initial Name Ideas", value: brief.initial_name_ideas },
    { label: "Timing", value: brief.timing },
  ];

  const rows = fields
    .filter(field => field.value && field.value.trim())
    .map(field => `| **${field.label}** | ${field.value} |`);

  return `| Field | Content |\n| :--- | :--- |\n${rows.join('\n')}`;
}

/**
 * Format a brief as a 2-3 sentence natural language summary (shown before the verdict).
 * Implements the conversational flow from spec §3 steps 1-3.
 */
export function formatBriefSummary(brief: CompiledBrief): string {
  const parts: string[] = [];

  if (brief.offering_description) {
    parts.push(brief.offering_description.trim().replace(/\.$/, "") + ".");
  }

  if (brief.target_customers) {
    parts.push(`It's designed for ${brief.target_customers.toLowerCase().replace(/\.$/, "")}.`);
  } else if (brief.jobs_to_be_done) {
    parts.push(`Primary job to be done: ${brief.jobs_to_be_done.toLowerCase().replace(/\.$/, "")}.`);
  }

  if (brief.target_geographies) {
    parts.push(`Target markets: ${brief.target_geographies}.`);
  }

  if (brief.timing && parts.length < 3) {
    parts.push(`Timeline: ${brief.timing}.`);
  }

  return parts.slice(0, 3).join(" ");
}

/**
 * Convert an EvaluateResult to the spec-compliant machine payload (spec §6.2).
 * Maps internal PATH_A0/PATH_B/etc. enum values to the short "A0"/"B"/etc. format.
 */
export function toMachinePayload(result: {
  verdict: VerdictOutput;
  gateEvaluation: GateEvaluation;
  scoringResult?: ScoringResult;
  factsData?: unknown;
  compiledBrief?: CompiledBrief;
  requiresClarification: boolean;
  questions?: string[];
}): MachinePayload {
  // Strip the "PATH_" prefix: PATH_A0 → "A0", PATH_B → "B", etc.
  const verdictPath = result.verdict.path.replace(/^PATH_/, "") as MachinePayload["verdict_path"];

  return {
    step: "step_1_gate",
    verdict_path: verdictPath,
    verdict_label: result.verdict.title,
    compiled_brief: result.compiledBrief ?? null,
    naming_facts: result.factsData ?? null,
    gate_results: result.gateEvaluation,
    scores: result.scoringResult?.scores ?? null,
    needs_clarification: result.requiresClarification,
    clarification_questions: result.questions ?? [],
  };
}

/**
 * Escalation context from retry attempts
 */
export interface EscalationContext {
  attempt1Status: string;
  attempt2Status: string;
  userClarification: string;
  remainingGaps: string[];
  brief: CompiledBrief;
  gateEvaluation: import("../models/gates").GateEvaluation;
  clarificationHistory?: string;
}

/**
 * Format as escalation output
 * Used when retry still results in PATH_B (needs more info)
 */
export function formatAsEscalation(context: EscalationContext): string {
  const { attempt1Status, attempt2Status, userClarification, remainingGaps, brief, gateEvaluation, clarificationHistory } = context;

  let output = `### ⚠️ ESCALATION: Manual Review Needed\n\n`;
  output += `**I appreciate your patience, but I need to escalate this for manual review.**\n\n`;
  output += `Even with your clarification, I'm still missing critical information needed to make a definitive naming recommendation. Here's what happened:\n\n`;

  // 1. Assessment History
  output += `**What I tried:**\n\n`;
  output += `1. **Initial assessment:** ${attempt1Status}\n`;
  output += `2. **After your clarification:** ${attempt2Status}\n\n`;

  // 2. User Clarification Provided
  output += `**Your clarification:**\n\n`;
  output += `> ${userClarification}\n\n`;

  // 3. Why we are still stuck
  output += `**Why I'm still stuck:**\n\n`;
  output += `These critical questions remain unanswered:\n\n`;
  for (const gap of remainingGaps) {
    output += `- ${gap}\n`;
  }
  output += '\n';
  output += `Without this information, I can't determine whether this feature qualifies for a proper name or should use a descriptive label. The framework requires specific facts about standalone behavior, longevity, and scope - and the current brief doesn't provide enough detail.\n\n`;

  // 4. Current State of Facts (Updated Brief)
  output += `**What I know so far:**\n\n`;
  output += `- **Offering:** ${brief.offering_description || 'Not specified'}\n`;
  output += `- **Value Proposition:** ${brief.value_proposition || 'Not specified'}\n`;
  if (brief.target_customers) {
    output += `- **Target Customers:** ${brief.target_customers}\n`;
  }
  if (brief.target_geographies) {
    output += `- **Target Markets:** ${brief.target_geographies}\n`;
  }
  if (brief.timing) {
    output += `- **Timing:** ${brief.timing}\n`;
  }
  if (clarificationHistory) {
    output += `- **Clarifications provided:** ${clarificationHistory}\n`;
  }
  output += '\n';

  // Audit Log: Gate Checks
  output += `**Current gate evaluation:**\n\n`;
  for (const [key, gate] of Object.entries(gateEvaluation.gate_results)) {
    const statusEmoji = gate.status === "Pass" ? "✅" : gate.status === "Fail" ? "❌" : "⚠️";
    output += `${statusEmoji} **${key} (${gate.label}):** ${gate.status}\n`;
    output += `   *Reasoning:* ${gate.reasoning}\n`;
    if (gate.evidence) {
      output += `   *Evidence:* ${gate.evidence}\n`;
    }
    output += '\n';
  }

  // Recommendation
  output += `**Next steps:**\n\n`;
  output += `Please work with your PM/PMM to gather the missing information listed above, then submit a new assessment with a complete brief. Alternatively, schedule a 15-minute sync with the Brand team to walk through the feature and answer these questions together.\n\n`;
  output += `---\n\n`;
  output += `_This escalation was generated because the naming framework requires specific factual inputs that weren't available in the current brief or clarifications._\n`;

  return output;
}
