/**
 * G4 (Portfolio Alignment) Integration
 * Enhances G4 gate evaluation with automated name checking
 *
 * This module can be used to:
 * 1. Validate proposed names against eBay portfolio
 * 2. Check for trademark conflicts
 * 3. Provide data-driven reasoning for G4 gate decisions
 */

import { getNameChecker, type NameCheckResult } from './name-checker';
import type { GateStatus } from '@/lib/schemas';

export interface G4EnhancedResult {
  status: GateStatus;
  reasoning: string;
  nameCheckData?: NameCheckResult;
  autoGenerated: boolean;
}

/**
 * Enhance G4 gate evaluation with automated name checking
 */
export async function enhanceG4Evaluation(
  proposedName: string,
  existingReasoning?: string
): Promise<G4EnhancedResult> {
  try {
    const nameChecker = getNameChecker();
    const nameCheckData = await nameChecker.checkName(proposedName, {
      checkEbay: true,
      checkTrademarks: true,
      useCache: true,
    });

    // Determine gate status based on name check results
    const status = determineG4Status(nameCheckData);

    // Generate reasoning
    const reasoning = generateG4Reasoning(nameCheckData, existingReasoning);

    return {
      status,
      reasoning,
      nameCheckData,
      autoGenerated: true,
    };
  } catch (error) {
    console.error('G4 enhancement failed:', error);

    // Fallback to manual evaluation
    return {
      status: 'Pending',
      reasoning: existingReasoning || 'Automated name checking unavailable. Manual portfolio review required.',
      autoGenerated: false,
    };
  }
}

/**
 * Determine G4 gate status from name check results
 */
function determineG4Status(nameCheckData: NameCheckResult): GateStatus {
  const { riskLevel, conflicts } = nameCheckData;

  // Critical or high risk = automatic fail
  if (riskLevel === 'critical' || riskLevel === 'high') {
    const hasPortfolioConflict = conflicts.some(c => c.type === 'portfolio');
    const hasTrademarkConflict = conflicts.some(c => c.type === 'trademark' && c.severity === 'high');

    if (hasPortfolioConflict || hasTrademarkConflict) {
      return 'Fail';
    }

    return 'Pending'; // High risk but might be acceptable
  }

  // Medium risk = pending for review
  if (riskLevel === 'medium') {
    return 'Pending';
  }

  // Low risk = pass
  return 'Pass';
}

/**
 * Generate CHECK/FINDING format reasoning for G4
 */
function generateG4Reasoning(
  nameCheckData: NameCheckResult,
  existingReasoning?: string
): string {
  const { name, conflicts, riskLevel, ebayData, trademarkData } = nameCheckData;

  const checkParts: string[] = [];
  const findingParts: string[] = [];

  // Portfolio conflicts
  const portfolioConflicts = conflicts.filter(c => c.type === 'portfolio');
  if (portfolioConflicts.length > 0) {
    checkParts.push(
      `Automated portfolio scan found ${portfolioConflicts.length} conflict(s) with existing eBay products: ${portfolioConflicts.map(c => c.details?.product).filter(Boolean).join(', ')}.`
    );
    findingParts.push(
      `The proposed name "${name}" has significant overlap with established eBay product names, which could cause user confusion.`
    );
  } else {
    checkParts.push(
      `Automated portfolio scan of ${name} against known eBay products found no direct conflicts.`
    );
  }

  // Trademark conflicts
  if (trademarkData?.hasConflicts) {
    checkParts.push(
      `Trademark database search found ${trademarkData.conflicts.length} registered mark(s) with similarity to "${name}".`
    );
    findingParts.push(
      `Trademark conflicts detected with risk level: ${trademarkData.riskLevel}.`
    );
  } else if (trademarkData) {
    checkParts.push(
      `USPTO trademark search returned no active conflicts for "${name}".`
    );
  }

  // eBay marketplace analysis
  if (ebayData) {
    if (ebayData.totalProducts > 100) {
      checkParts.push(
        `eBay marketplace analysis shows ${ebayData.totalProducts} existing product listings using the term "${name}".`
      );
      findingParts.push(
        `High volume of existing products may indicate genericness or established third-party brand usage.`
      );
    } else if (ebayData.totalProducts > 0) {
      checkParts.push(
        `eBay marketplace shows ${ebayData.totalProducts} product listings containing "${name}".`
      );
    }
  }

  // Combine with existing reasoning if provided
  let reasoning = '';

  if (checkParts.length > 0) {
    reasoning = `CHECK: ${checkParts.join(' ')}`;
  }

  if (findingParts.length > 0) {
    reasoning += `\n// FINDING: ${findingParts.join(' ')}`;
  } else {
    // Default finding based on risk level
    if (riskLevel === 'low') {
      reasoning += `\n// FINDING: No significant naming conflicts detected. The proposed name appears distinct from existing eBay portfolio and has low trademark risk.`;
    } else if (riskLevel === 'medium') {
      reasoning += `\n// FINDING: Some potential conflicts detected. Recommend legal review and portfolio alignment check before proceeding.`;
    } else {
      reasoning += `\n// FINDING: Multiple conflicts detected with high risk of user confusion or legal issues. Recommend selecting an alternative name.`;
    }
  }

  // Append existing reasoning if provided
  if (existingReasoning) {
    reasoning += `\n\nAdditional context: ${existingReasoning}`;
  }

  return reasoning;
}

/**
 * Batch enhance multiple names (for comparing alternatives)
 */
export async function enhanceG4BatchEvaluation(
  proposedNames: string[]
): Promise<Map<string, G4EnhancedResult>> {
  const results = new Map<string, G4EnhancedResult>();

  for (const name of proposedNames) {
    const result = await enhanceG4Evaluation(name);
    results.set(name, result);
  }

  return results;
}

/**
 * Generate G4 gate summary for multiple name candidates
 */
export function generateG4Summary(results: Map<string, G4EnhancedResult>): string {
  const passed = Array.from(results.entries()).filter(([_, r]) => r.status === 'Pass');
  const failed = Array.from(results.entries()).filter(([_, r]) => r.status === 'Fail');
  const pending = Array.from(results.entries()).filter(([_, r]) => r.status === 'Pending');

  let summary = `G4 Portfolio Alignment Summary:\n\n`;

  if (passed.length > 0) {
    summary += `✅ Passed (${passed.length}): ${passed.map(([name]) => name).join(', ')}\n`;
  }

  if (pending.length > 0) {
    summary += `⚠️ Pending Review (${pending.length}): ${pending.map(([name]) => name).join(', ')}\n`;
  }

  if (failed.length > 0) {
    summary += `❌ Failed (${failed.length}): ${failed.map(([name]) => name).join(', ')}\n`;
  }

  return summary;
}

/**
 * Extract proposed name from brief text
 * Uses simple heuristics - can be enhanced with NLP
 */
export function extractProposedName(brief: string): string | null {
  // Look for common patterns:
  // - "name: X"
  // - "proposed name: X"
  // - "product name: X"
  // - quoted names

  const patterns = [
    /(?:proposed\s+)?(?:product\s+)?name:\s*["']?([a-zA-Z0-9\s-]+?)["']?(?:\n|$|\.)/i,
    /["']([A-Z][a-zA-Z0-9\s-]+?)["']/,
    /\bnamed?\s+["']?([A-Z][a-zA-Z0-9\s-]+?)["']?/i,
  ];

  for (const pattern of patterns) {
    const match = brief.match(pattern);
    if (match && match[1]) {
      return match[1].trim();
    }
  }

  return null;
}

/**
 * Helper to integrate with existing evaluate route
 * Can be called before or after LLM evaluation
 */
export async function augmentG4WithNameCheck(
  brief: string,
  existingG4Result?: { status: GateStatus; reasoning: string }
): Promise<G4EnhancedResult | null> {
  // Try to extract proposed name from brief
  const proposedName = extractProposedName(brief);

  if (!proposedName) {
    console.log('Could not extract proposed name from brief');
    return null;
  }

  console.log(`Extracted proposed name: "${proposedName}"`);

  // Enhance G4 evaluation
  return enhanceG4Evaluation(proposedName, existingG4Result?.reasoning);
}
