/**
 * Slack webhook integration
 * Fires a Block Kit notification when a PATH_C verdict is reached.
 * Configure via SLACK_WEBHOOK_URL environment variable.
 */

export interface SlackVerdictPayload {
  verdictTitle: string;
  score: number | null;
  briefSnippet: string;
  gateSummary: string | null;
  offeringDescription: string | null;
}

export async function notifySlackPathC(payload: SlackVerdictPayload): Promise<boolean> {
  const webhookUrl = process.env.SLACK_WEBHOOK_URL;
  if (!webhookUrl) return false;

  const scoreText = payload.score !== null ? `${payload.score}/70` : "N/A";
  const gateText = payload.gateSummary ?? "All gates passed";
  const offeringText = payload.offeringDescription ?? payload.briefSnippet;

  const body = {
    blocks: [
      {
        type: "header",
        text: { type: "plain_text", text: "✅ Naming Approved", emoji: true },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*${payload.verdictTitle}*`,
        },
      },
      {
        type: "section",
        fields: [
          { type: "mrkdwn", text: `*Score*\n${scoreText}` },
          { type: "mrkdwn", text: `*Gates*\n${gateText}` },
        ],
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*Offering*\n${offeringText.slice(0, 300)}${offeringText.length > 300 ? "…" : ""}`,
        },
      },
      {
        type: "context",
        elements: [
          {
            type: "mrkdwn",
            text: `Generated by <https://naming-studio.vip.ebay.com|eBay Naming Studio> · ${new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`,
          },
        ],
      },
    ],
  };

  try {
    const res = await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    return res.ok;
  } catch {
    return false;
  }
}
