/**
 * eBay Name Checker Usage Examples
 *
 * This file demonstrates how to use the name checking system
 * in various scenarios.
 */

import { getNameChecker } from '@/lib/modules/name-checker';
import {
  enhanceG4Evaluation,
  enhanceG4BatchEvaluation,
  generateG4Summary,
  augmentG4WithNameCheck
} from '@/lib/modules/g4-integration';
import type { NameCheckOptions } from '@/lib/modules/name-checker';

// ============================================================================
// Example 1: Basic Single Name Check
// ============================================================================

async function basicNameCheck() {
  const nameChecker = getNameChecker();

  const result = await nameChecker.checkName('eBay SmartSell');

  console.log('Name:', result.name);
  console.log('Available:', result.isAvailable);
  console.log('Risk Level:', result.riskLevel);
  console.log('Conflicts:', result.conflicts.length);
  console.log('Recommendations:', result.recommendations);
}

// ============================================================================
// Example 2: Custom Options
// ============================================================================

async function customOptionsCheck() {
  const nameChecker = getNameChecker();

  const options: NameCheckOptions = {
    checkEbay: true,           // Search eBay marketplace
    checkTrademarks: true,     // Check USPTO database
    maxEbayResults: 50,        // Get more results
    useCache: true,            // Use caching
    includeRelatedTerms: false // Don't check variations
  };

  const result = await nameChecker.checkName('QuickList Pro', options);

  // Access detailed data
  if (result.ebayData) {
    console.log('Total eBay products:', result.ebayData.totalProducts);
    console.log('Sample products:', result.ebayData.sampleProducts);
    console.log('Search URL:', result.ebayData.searchUrl);
  }

  if (result.trademarkData) {
    console.log('Trademark conflicts:', result.trademarkData.conflicts.length);
    console.log('Trademark risk:', result.trademarkData.riskLevel);
  }

  // Analyze conflicts
  result.conflicts.forEach(conflict => {
    console.log(`${conflict.type} conflict:`, conflict.description);
    console.log(`Severity: ${conflict.severity}`);
  });
}

// ============================================================================
// Example 3: Batch Name Checking
// ============================================================================

async function batchNameCheck() {
  const nameChecker = getNameChecker();

  const candidates = [
    'AutoSell Plus',
    'SmartList Manager',
    'QuickPost Pro',
    'eBay Turbo' // This should fail due to portfolio conflict
  ];

  const results = await nameChecker.batchCheckNames(candidates);

  // Sort by risk level
  const sorted = results.sort((a, b) => {
    const levels = { low: 0, medium: 1, high: 2, critical: 3 };
    return levels[a.riskLevel] - levels[b.riskLevel];
  });

  console.log('Best Options (lowest risk first):');
  sorted.forEach(result => {
    console.log(`- ${result.name}: ${result.riskLevel} risk`);
  });
}

// ============================================================================
// Example 4: G4 Gate Integration - Single Name
// ============================================================================

async function g4SingleEnhancement() {
  const proposedName = 'SellerTools Hub';

  const g4Result = await enhanceG4Evaluation(proposedName);

  console.log('G4 Status:', g4Result.status); // Pass, Fail, Pending, Unknown
  console.log('G4 Reasoning:', g4Result.reasoning);
  console.log('Auto-generated:', g4Result.autoGenerated);

  // Access underlying name check data
  if (g4Result.nameCheckData) {
    console.log('Conflicts:', g4Result.nameCheckData.conflicts);
  }

  // Use in evaluation flow
  if (g4Result.status === 'Fail') {
    console.log('❌ G4 Gate Failed - Choose different name');
  } else if (g4Result.status === 'Pending') {
    console.log('⚠️ G4 Gate Pending - Manual review needed');
  } else {
    console.log('✅ G4 Gate Passed');
  }
}

// ============================================================================
// Example 5: G4 Gate Integration - Batch Comparison
// ============================================================================

async function g4BatchComparison() {
  const candidates = [
    'AutoList Pro',
    'Seller Companion',
    'QuickPost Manager'
  ];

  const results = await enhanceG4BatchEvaluation(candidates);

  // Generate summary
  const summary = generateG4Summary(results);
  console.log(summary);

  // Detailed analysis
  results.forEach((g4Result, name) => {
    console.log(`\n${name}:`);
    console.log(`  Status: ${g4Result.status}`);
    console.log(`  Reasoning: ${g4Result.reasoning.substring(0, 100)}...`);

    if (g4Result.nameCheckData) {
      console.log(`  Risk: ${g4Result.nameCheckData.riskLevel}`);
      console.log(`  Conflicts: ${g4Result.nameCheckData.conflicts.length}`);
    }
  });

  // Find best option
  const passedNames = Array.from(results.entries())
    .filter(([_, result]) => result.status === 'Pass')
    .map(([name]) => name);

  console.log('\nRecommended names:', passedNames);
}

// ============================================================================
// Example 6: Auto-Augment G4 from Brief
// ============================================================================

async function autoAugmentG4() {
  const brief = `
    We're launching a new feature called "QuickSell Pro" that helps sellers
    list items faster using AI-powered description generation and automatic
    category selection.
  `;

  // Automatically extract name and run checks
  const g4Enhancement = await augmentG4WithNameCheck(brief);

  if (g4Enhancement) {
    console.log('Extracted name and ran checks');
    console.log('Status:', g4Enhancement.status);
    console.log('Reasoning:', g4Enhancement.reasoning);
  } else {
    console.log('Could not extract proposed name from brief');
  }
}

// ============================================================================
// Example 7: API Endpoint Usage (Frontend)
// ============================================================================

async function frontendApiUsage() {
  // Single name check via POST
  const response = await fetch('/api/check-names', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      names: 'SmartSell Assistant',
      options: {
        checkEbay: true,
        checkTrademarks: true,
        maxEbayResults: 20
      }
    })
  });

  const data = await response.json();
  console.log('API Response:', data);

  // Access results
  const result = data.results[0];
  console.log('Name:', result.name);
  console.log('Available:', result.isAvailable);
  console.log('Recommendations:', result.recommendations);
}

// ============================================================================
// Example 8: Batch API Check (Frontend)
// ============================================================================

async function batchApiUsage() {
  const response = await fetch('/api/check-names', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      names: [
        'AutoList Pro',
        'Seller Suite',
        'QuickPost Manager'
      ]
    })
  });

  const data = await response.json();

  // Summary
  console.log('Summary:', data.summary);
  console.log(`Total: ${data.summary.totalChecked}`);
  console.log(`Available: ${data.summary.available}`);
  console.log(`High Risk: ${data.summary.highRisk}`);

  // Individual results
  data.results.forEach((result: any) => {
    console.log(`\n${result.name}:`);
    console.log(`  Available: ${result.isAvailable}`);
    console.log(`  Risk: ${result.riskLevel}`);
  });
}

// ============================================================================
// Example 9: GET Endpoint (Quick Check)
// ============================================================================

async function quickApiCheck() {
  const name = 'SellerTools Pro';
  const response = await fetch(
    `/api/check-names?name=${encodeURIComponent(name)}`
  );

  const result = await response.json();

  if (result.isAvailable) {
    console.log('✅ Name is available!');
  } else {
    console.log('❌ Name has conflicts:');
    result.conflicts.forEach((conflict: any) => {
      console.log(`  - ${conflict.description}`);
    });
  }
}

// ============================================================================
// Example 10: Error Handling
// ============================================================================

async function errorHandlingExample() {
  try {
    const response = await fetch('/api/check-names', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ names: 'TestName' })
    });

    if (!response.ok) {
      if (response.status === 429) {
        console.error('Rate limit exceeded - wait before retrying');
      } else if (response.status === 503) {
        console.error('Service unavailable - eBay API not configured');
      } else {
        console.error('Request failed:', response.status);
      }
      return;
    }

    const data = await response.json();
    console.log('Success:', data);

  } catch (error) {
    console.error('Network error:', error);
  }
}

// ============================================================================
// Example 11: Pre-flight Validation in Form
// ============================================================================

async function formValidationExample() {
  // In your form submission handler
  const proposedName = 'UserInputName';

  // Quick check before full evaluation
  const response = await fetch('/api/check-names', {
    method: 'POST',
    body: JSON.stringify({ names: proposedName })
  });

  const data = await response.json();
  const result = data.results[0];

  if (result.riskLevel === 'critical' || result.riskLevel === 'high') {
    const conflictSummary = result.conflicts
      .map((c: any) => c.description)
      .join('\n');

    const proceed = confirm(
      `Warning: This name has conflicts:\n\n${conflictSummary}\n\nDo you want to proceed anyway?`
    );

    if (!proceed) {
      return; // Cancel submission
    }
  }

  // Continue with full evaluation
  console.log('Proceeding with evaluation...');
}

// ============================================================================
// Example 12: Integration with Existing Evaluate Endpoint
// ============================================================================

async function evaluateWithNameCheck(brief: string, model?: string) {
  // Step 1: Run name check (optional pre-flight)
  const g4Enhancement = await augmentG4WithNameCheck(brief);

  if (g4Enhancement && g4Enhancement.status === 'Fail') {
    console.warn('Name will likely fail G4 gate');
  }

  // Step 2: Run normal evaluation
  const response = await fetch('/api/evaluate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ brief, model })
  });

  const evaluationResult = await response.json();

  // Step 3: Optionally override G4 with name check data
  if (g4Enhancement && g4Enhancement.autoGenerated) {
    evaluationResult.gatekeeperResult.G4 = {
      status: g4Enhancement.status,
      reasoning: g4Enhancement.reasoning
    };
  }

  return evaluationResult;
}

// ============================================================================
// Example 13: Cache Management
// ============================================================================

async function cacheManagementExample() {
  const nameChecker = getNameChecker();

  // Check with cache (default)
  const cachedResult = await nameChecker.checkName('TestName', {
    useCache: true
  });

  console.log('From cache:', cachedResult.cachedResult);

  // Force fresh check (bypass cache)
  const freshResult = await nameChecker.checkName('TestName', {
    useCache: false
  });

  console.log('Fresh check:', freshResult.cachedResult); // Should be false
}

// ============================================================================
// Export examples for use
// ============================================================================

export {
  basicNameCheck,
  customOptionsCheck,
  batchNameCheck,
  g4SingleEnhancement,
  g4BatchComparison,
  autoAugmentG4,
  frontendApiUsage,
  batchApiUsage,
  quickApiCheck,
  errorHandlingExample,
  formValidationExample,
  evaluateWithNameCheck,
  cacheManagementExample
};

// ============================================================================
// Run examples (uncomment to test)
// ============================================================================

async function runExamples() {
  console.log('=== Running Name Checker Examples ===\n');

  // await basicNameCheck();
  // await customOptionsCheck();
  // await batchNameCheck();
  // await g4SingleEnhancement();
  // await g4BatchComparison();
  // await autoAugmentG4();
}

// runExamples().catch(console.error);
