// eBay Naming Graph - Enriched Wave 4 Batch R
// Focus: Listing Features, Item Specifics, Categories, Product Identifiers, Variations, Bulk Tools
// Generated: 2026-04-18
// Count: 110 programs

import { GraphNode } from './enriched-consolidated-DEDUPLICATED'

export const ENRICHED_WAVE4_R: GraphNode[] = [
  {
    id: "multi-variation-listings",
    name: "Multi-Variation Listings",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Single listing supporting multiple product variations (size, color, style) - buyers select specific option from unified product page with shared description.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "variations",
    name: "Variations",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Product attribute selector on listings - enables buyers to choose size, color, or other options within single listing without navigating to separate pages.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "variation-listings",
    name: "Variation Listings",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Listing format consolidating product variants - supports up to 250 variations per listing with individual pricing, inventory, and SKUs per variant.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "listing-with-variations",
    name: "Listing with Variations",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Multi-option listing type - displays dropdown or swatch selectors for product attributes, shares images and description across all variants.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "variation-option",
    name: "Variation Option",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Individual attribute choice within variation listing - represents single selectable value (e.g., 'Red' in Color variation, 'Medium' in Size).",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "color-variation",
    name: "Color Variation",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Color attribute selector in variation listings - displays as swatches or dropdown, often paired with variant-specific product images.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "size-variation",
    name: "Size Variation",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Size attribute selector in variation listings - common in apparel, shoes, and accessories with standardized or custom size values.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "color-option",
    name: "Color Option",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Color selector control in variation listings - visual swatch interface for product color choices with thumbnail image updates.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2011
  },
  {
    id: "size-option",
    name: "Size Option",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Size selector control in variation listings - dropdown or button group for size selection with real-time inventory availability display.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2011
  },
  {
    id: "custom-variation",
    name: "Custom Variation",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "User-defined variation attribute - allows sellers to create non-standard variation types (material, pattern, scent) beyond size/color.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2012
  },
  {
    id: "category-specifics",
    name: "Category Specifics",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Category-mandated item attributes - structured data fields required for listings in specific categories (brand, model, size) to improve search relevance.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2008
  },
  {
    id: "required-item-specifics",
    name: "Required Item Specifics",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Mandatory structured data fields for listing creation - category-dependent attributes that must be completed before listing can go live.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2008
  },
  {
    id: "recommended-item-specifics",
    name: "Recommended Item Specifics",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Suggested structured data fields to improve listing performance - optional attributes shown during listing creation to boost search visibility.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "ai-item-specifics",
    name: "AI Item Specifics",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Machine learning-powered attribute suggestion - auto-populates item specifics based on title, description, and product catalog matching.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2022
  },
  {
    id: "brand",
    name: "Brand",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Manufacturer or brand name item specific - searchable attribute distinguishing branded vs generic products, used for catalog matching and faceted search.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2005
  },
  {
    id: "unbranded",
    name: "Unbranded",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Brand attribute value for generic products - indicates item has no manufacturer brand, commonly used for handmade or no-name goods.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "does-not-apply",
    name: "Does Not Apply",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Item specific opt-out value - indicates attribute is not relevant to product (e.g., 'Size' for digital downloads).",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "upc",
    name: "UPC",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Universal Product Code identifier - 12-digit barcode standard used for product catalog matching and inventory management in US/Canada markets.",
    market: ["US", "CA"],
    year: 2006
  },
  {
    id: "ean",
    name: "EAN",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "European Article Number identifier - 13-digit barcode standard used for product catalog matching in European and international markets.",
    market: ["UK", "DE", "FR", "IT", "AU"],
    year: 2006
  },
  {
    id: "isbn",
    name: "ISBN",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "International Standard Book Number - unique identifier for books enabling catalog matching and edition-specific listing accuracy.",
    market: "global",
    year: 2005
  },
  {
    id: "gtin",
    name: "GTIN",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Global Trade Item Number - umbrella term for product identifiers (UPC, EAN, ISBN) used in catalog matching and inventory systems.",
    market: "global",
    year: 2010
  },
  {
    id: "mpn",
    name: "MPN",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Manufacturer Part Number - brand-specific product identifier used when GTIN unavailable, critical for automotive and electronics catalog matching.",
    market: "global",
    year: 2006
  },
  {
    id: "ebay-product-catalog",
    name: "eBay Product Catalog",
    type: "category",
    tier: "platform",
    status: "current",
    parent: "listing",
    desc: "Centralized product database mapping GTINs to product attributes - enables structured data, image suggestions, and cross-listing consistency.",
    market: "global",
    year: 2011
  },
  {
    id: "ebay-product-id",
    name: "eBay Product ID",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "eBay-assigned product identifier - links listing to catalog entry for pre-filled attributes and product page aggregation.",
    market: "global",
    year: 2011
  },
  {
    id: "ebay-catalog-integration",
    name: "eBay Catalog Integration",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Product catalog matching during listing creation - automatically populates title, attributes, and images when GTIN/ePID recognized.",
    market: "global",
    year: 2012
  },
  {
    id: "browse-categories",
    name: "Browse Categories",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "discovery",
    desc: "Hierarchical product taxonomy navigation - structured category tree enabling buyers to drill down from broad categories to specific product types.",
    market: "global",
    year: 1995
  },
  {
    id: "category-browse",
    name: "Category Browse",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "discovery",
    desc: "Category-based product exploration interface - displays subcategories, filters, and listings within selected category level.",
    market: "global",
    year: 1995
  },
  {
    id: "all-categories",
    name: "All Categories",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "discovery",
    desc: "Top-level category directory - entry point showing all L1 categories for site-wide product navigation.",
    market: "global",
    year: 1995
  },
  {
    id: "browse",
    name: "Browse",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "discovery",
    desc: "Product exploration mode - category and filter-driven discovery alternative to search-based finding.",
    market: "global",
    year: 1995
  },
  {
    id: "subcategories",
    name: "Subcategories",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "discovery",
    desc: "Child category levels beneath parent category - enables progressive narrowing from broad to specific product types.",
    market: "global",
    year: 1995
  },
  {
    id: "store-categories",
    name: "Store Categories",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "stores",
    desc: "Seller-defined category structure within eBay Store - custom taxonomy organizing store inventory independently from site-wide categories.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2001
  },
  {
    id: "custom-categories",
    name: "Custom Categories",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "stores",
    desc: "Seller-created category names and hierarchy for Store - up to 300 custom categories with 3 nested levels for brand-specific organization.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2001
  },
  {
    id: "featured-categories",
    name: "Featured Categories",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "stores",
    desc: "Highlighted category display in Store header/sidebar - promotes selected categories for seasonal campaigns or top-selling product groups.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2005
  },
  {
    id: "dual-category-listing",
    name: "Dual Category Listing",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Listing visible in two categories simultaneously - increases discoverability for cross-category products with additional insertion fee.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2003
  },
  {
    id: "getcategoryfeatures",
    name: "GetCategoryFeatures",
    type: "developer",
    tier: "feature",
    status: "current",
    parent: "api",
    desc: "Trading API call returning category-specific listing features - indicates variations support, item specifics, condition values per category.",
    market: "global",
    year: 2008
  },
  {
    id: "sku",
    name: "SKU",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "inventory",
    desc: "Stock Keeping Unit identifier - seller-defined alphanumeric code for internal inventory tracking and multi-channel synchronization.",
    market: "global",
    year: 2005
  },
  {
    id: "custom-sku",
    name: "Custom SKU",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "inventory",
    desc: "User-defined inventory identifier field - enables sellers to maintain consistent SKU across platforms for ERP and warehouse integration.",
    market: "global",
    year: 2005
  },
  {
    id: "custom-label",
    name: "Custom Label",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "inventory",
    desc: "Internal tagging field for seller organization - not visible to buyers, used for reporting segmentation and campaign tracking.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "item-number",
    name: "Item Number",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Unique eBay-assigned listing identifier - 12-digit number used for customer service, reporting, and API operations.",
    market: "global",
    year: 1995
  },
  {
    id: "bulk-upload",
    name: "Bulk Upload",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Multi-listing creation via file import - CSV/Excel template-based tool for creating/revising hundreds of listings simultaneously.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2006
  },
  {
    id: "csv-upload",
    name: "CSV Upload",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Spreadsheet-based listing import - uses comma-separated value files to create/update listings with structured product data.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2006
  },
  {
    id: "bulk-listing",
    name: "Bulk Listing",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "High-volume listing creation workflow - supports batch operations for sellers managing large inventories or seasonal campaigns.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2006
  },
  {
    id: "bulk-edit",
    name: "Bulk Edit",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Multi-listing modification tool - update price, quantity, shipping, or item specifics across multiple active listings in single operation.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2007
  },
  {
    id: "bulk-listing-tools",
    name: "Bulk Listing Tools",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Suite of high-volume listing management features - includes CSV upload, bulk edit, and template-based creation for power sellers.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2008
  },
  {
    id: "listing-template",
    name: "Listing Template",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Reusable listing configuration - saves category, item specifics, shipping, and business policies for rapid similar listing creation.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2004
  },
  {
    id: "duplicate-listing",
    name: "Duplicate Listing",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Clone existing listing function - creates new draft copying all attributes from active/ended listing for modification and re-listing.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2002
  },
  {
    id: "listing-title",
    name: "Listing Title",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "80-character product name field - primary search-indexed text displayed in browse and search results, critical for discoverability.",
    market: "global",
    year: 1995
  },
  {
    id: "character-limit",
    name: "Character Limit",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Title length constraint - 80 characters maximum for listing titles across all categories and formats.",
    market: "global",
    year: 1995
  },
  {
    id: "keywords",
    name: "Keywords",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Search-relevant terms in title and description - influences Cassini ranking and query matching for product discovery.",
    market: "global",
    year: 1995
  },
  {
    id: "title-optimization",
    name: "Title Optimization",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Search-driven title recommendations - suggests high-performing keywords and structure based on category-specific buyer search patterns.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2016
  },
  {
    id: "item-condition",
    name: "Item Condition",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Required product state attribute - dropdown selection (New, Used, Refurbished, etc.) with category-specific condition values.",
    market: "global",
    year: 2007
  },
  {
    id: "condition-description",
    name: "Condition Description",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Freeform text field elaborating on item condition - optional details about wear, defects, or included accessories.",
    market: "global",
    year: 2008
  },
  {
    id: "condition-guide",
    name: "Condition Guide",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Standardized condition definitions - category-specific descriptions helping sellers select accurate condition value (e.g., 'Very Good' criteria).",
    market: "global",
    year: 2010
  },
  {
    id: "new",
    name: "New",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Brand-new condition value - indicates unused product in original packaging with all original accessories and warranty.",
    market: "global",
    year: 2007
  },
  {
    id: "pre-owned",
    name: "Pre-owned",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Used condition umbrella term - generic previously-owned product state without specific quality grading.",
    market: "global",
    year: 2007
  },
  {
    id: "used",
    name: "Used",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Previously-owned condition value - indicates item has been used with varying degrees of wear described in condition description.",
    market: "global",
    year: 2007
  },
  {
    id: "like-new",
    name: "Like New",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Near-perfect used condition - minimal to no wear, appears unused but may lack original packaging.",
    market: "global",
    year: 2008
  },
  {
    id: "very-good",
    name: "Very Good",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Gently used condition grade - light wear or cosmetic blemishes, fully functional with no major defects.",
    market: "global",
    year: 2008
  },
  {
    id: "good",
    name: "Good",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Moderate wear condition grade - visible use with cosmetic imperfections, fully functional with no mechanical issues.",
    market: "global",
    year: 2008
  },
  {
    id: "acceptable",
    name: "Acceptable",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Heavy wear condition grade - significant cosmetic damage or defects, still functional but below average appearance.",
    market: "global",
    year: 2008
  },
  {
    id: "for-parts-or-not-working",
    name: "For Parts or Not Working",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Non-functional condition value - item does not work or sold for component harvesting only, as-is no warranty.",
    market: "global",
    year: 2008
  },
  {
    id: "for-parts",
    name: "For Parts",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Component-only sale condition - item sold for spare parts or repair use, not expected to function as complete product.",
    market: "global",
    year: 2008
  },
  {
    id: "brand-new",
    name: "Brand New",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Unused sealed product condition - emphasizes factory-fresh state with original packaging and manufacturer warranty intact.",
    market: "global",
    year: 2007
  },
  {
    id: "new-with-tags",
    name: "New with Tags",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Unworn apparel condition - original retail tags attached, never used or washed.",
    market: "global",
    year: 2008
  },
  {
    id: "new-without-tags",
    name: "New without Tags",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Unworn apparel condition - tags removed but item never used, often display models or tag removal during purchase.",
    market: "global",
    year: 2008
  },
  {
    id: "new-with-box",
    name: "New with Box",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Unused product with original packaging - common for shoes and collectibles, box condition may vary.",
    market: "global",
    year: 2009
  },
  {
    id: "new-without-box",
    name: "New without Box",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Unused product missing original packaging - unworn/unused but sold without manufacturer box.",
    market: "global",
    year: 2009
  },
  {
    id: "new-other",
    name: "New Other",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Brand-new with defects condition - unused but with packaging damage, cosmetic flaws, or missing non-essential accessories.",
    market: "global",
    year: 2010
  },
  {
    id: "new-with-defects",
    name: "New with Defects",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Unused product with known issues - factory seconds, display models, or damaged packaging, sold as-is.",
    market: "global",
    year: 2010
  },
  {
    id: "certified-pre-owned",
    name: "Certified Pre-owned",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Manufacturer-inspected used condition - previously-owned product meeting manufacturer standards with warranty coverage.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2012
  },
  {
    id: "manufacturer-refurbished",
    name: "Manufacturer Refurbished",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Factory-restored condition - OEM-refurbished product with new parts, testing, and manufacturer warranty.",
    market: "global",
    year: 2010
  },
  {
    id: "listing-description",
    name: "Listing Description",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Freeform product details section - supports HTML, images, and rich media for comprehensive product information and brand storytelling.",
    market: "global",
    year: 1995
  },
  {
    id: "description-template",
    name: "Description Template",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Reusable HTML description layout - saves formatted description structure for consistent branding across multiple listings.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2003
  },
  {
    id: "description-builder",
    name: "Description Builder",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Visual description editor - drag-and-drop interface for creating formatted product descriptions without HTML knowledge.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2015
  },
  {
    id: "html-editor",
    name: "HTML Editor",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Code-level description editor - advanced users can write custom HTML/CSS for listing descriptions with preview mode.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2000
  },
  {
    id: "visual-editor",
    name: "Visual Editor",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "WYSIWYG description interface - rich text editor with formatting toolbar for description creation without coding.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "wysiwyg-editor",
    name: "WYSIWYG Editor",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "What-you-see-is-what-you-get description tool - real-time preview editor for formatted descriptions with style controls.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "template-builder",
    name: "Template Builder",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Custom listing template creator - visual design tool for building reusable description layouts with placeholder fields.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2012
  },
  {
    id: "custom-template",
    name: "Custom Template",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "User-created listing template - personalized HTML/CSS layout saved for repeated use across similar product listings.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2003
  },
  {
    id: "mobile-responsive-template",
    name: "Mobile-Responsive Template",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Adaptive description layout - templates automatically adjusting formatting for optimal display on mobile and desktop devices.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2014
  },
  {
    id: "mobile-responsive-templates",
    name: "Mobile Responsive Templates",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Mobile-optimized description designs - pre-built responsive templates ensuring consistent listing appearance across all screen sizes.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2014
  },
  {
    id: "item-description",
    name: "Item Description",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Product details text field - main content area for describing features, condition, specifications, and seller policies.",
    market: "global",
    year: 1995
  },
  {
    id: "product-details",
    name: "Product Details",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Structured product information section - auto-populated from catalog data showing specifications, dimensions, and attributes.",
    market: "global",
    year: 2011
  },
  {
    id: "quantity-available",
    name: "Quantity Available",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "inventory",
    desc: "Current stock level display - real-time inventory count shown to buyers, automatically decrements with sales.",
    market: "global",
    year: 2000
  },
  {
    id: "stock-quantity",
    name: "Stock Quantity",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "inventory",
    desc: "Inventory level field in listing - seller-entered available quantity, supports up to 999,999 units per fixed-price listing.",
    market: "global",
    year: 2000
  },
  {
    id: "stock-level",
    name: "Stock Level",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "inventory",
    desc: "Inventory availability indicator - displays current quantity in stock for multi-quantity listings or variation options.",
    market: "global",
    year: 2005
  },
  {
    id: "stock-levels",
    name: "Stock Levels",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "inventory",
    desc: "Inventory tracking across listings - aggregated view of available quantities per SKU or variation.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2008
  },
  {
    id: "out-of-stock",
    name: "Out of Stock",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "inventory",
    desc: "Zero inventory status - listing state when quantity depleted, hides from search until seller replenishes stock.",
    market: "global",
    year: 2005
  },
  {
    id: "inventory-management",
    name: "Inventory Management",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Stock tracking and control tools - quantity updates, multi-channel sync, and low-stock alerts for active listings.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2008
  },
  {
    id: "inventory-sync",
    name: "Inventory Sync",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Real-time inventory synchronization - automatic quantity updates across eBay when stock changes via API or third-party tools.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2012
  },
  {
    id: "multi-channel-inventory",
    name: "Multi-Channel Inventory",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Cross-platform inventory coordination - integrates eBay stock levels with other marketplaces to prevent overselling.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2014
  },
  {
    id: "multi-quantity-listing",
    name: "Multi-Quantity Listing",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Listing with multiple units available - fixed-price format allowing buyers to purchase 1 to max quantity from single listing.",
    market: "global",
    year: 2000
  },
  {
    id: "lot-size",
    name: "Lot Size",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Bulk purchase unit quantity - indicates how many items included in single purchase (e.g., '5-pack', 'case of 24').",
    market: "global",
    year: 2002
  },
  {
    id: "bundle",
    name: "Bundle",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Multi-item product package - combined listing of related products sold together as single unit with bundle pricing.",
    market: "global",
    year: 2005
  },
  {
    id: "kit",
    name: "Kit",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Curated product set - packaged collection of complementary items sold together (e.g., starter kit, gift set).",
    market: "global",
    year: 2006
  },
  {
    id: "fitment-data",
    name: "Fitment Data",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "motors",
    desc: "Vehicle compatibility specifications - structured year/make/model data for automotive parts ensuring accurate vehicle fitment matching.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2008
  },
  {
    id: "active-content-policy",
    name: "Active Content Policy",
    type: "category",
    tier: "legal",
    status: "current",
    parent: "policy",
    desc: "Listing restrictions on dynamic elements - prohibits JavaScript, external stylesheets, and auto-playing media in descriptions for security.",
    market: "global",
    year: 2017
  },
  {
    id: "listing-error",
    name: "Listing Error",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Validation failure notification - blocking or warning message when listing violates policy, missing required fields, or has invalid data.",
    market: "global",
    year: 2000
  },
  {
    id: "validation-error",
    name: "Validation Error",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Data integrity check failure - error message indicating required field omission, format mismatch, or policy violation.",
    market: "global",
    year: 2005
  },
  {
    id: "attention-required",
    name: "Attention Required",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Listing issue flag - notification that listing has policy violation, missing information, or action needed to remain active.",
    market: "global",
    year: 2010
  },
  {
    id: "listing-designer",
    name: "Listing Designer",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Pre-built listing theme library - decorative templates with borders and layouts to enhance listing appearance (legacy feature).",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2003
  },
  {
    id: "magical-listing",
    name: "Magical Listing",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "AI-powered listing creation - mobile app feature using photo scan to auto-generate title, category, description, and item specifics.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2023
  }
]
