// eBay Naming Graph - ULTRA MEGA WAVE 4 BATCH AE
// Focus: COMPREHENSIVE SWEEP - All Categories, Markets, Features
// 200+ NEW programs - Largest enrichment batch
// Generated: 2026-04-17

import { GraphNode } from './enriched-consolidated-DEDUPLICATED'

export const ENRICHED_WAVE4_AE: GraphNode[] = [

  // ===== BUYER EXPERIENCE & DISCOVERY (30 programs) =====

  {
    id: "saved-searches",
    name: "Saved Searches",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Allows buyers to save custom search queries and receive email or push notifications when new matching items are listed. Supports up to 300 saved searches per account.",
    market: "global",
    year: 2005
  },
  {
    id: "browse-categories",
    name: "Browse Categories",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Hierarchical navigation system with 1000+ product categories organized by vertical (Motors, Fashion, Electronics, Collectibles, etc.) for exploratory shopping.",
    market: "global",
    year: 1997
  },
  {
    id: "recently-viewed",
    name: "Recently Viewed",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "Personalized feed showing last 100 items viewed by buyer with quick access to revisit listings. Syncs across devices when logged in.",
    market: "global",
    year: 2010
  },
  {
    id: "watching",
    name: "Watching",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "Wishlist feature allowing buyers to track up to 400 items with notifications for price drops, ending soon auctions, and listing updates.",
    market: "global",
    year: 2003
  },
  {
    id: "price-alert",
    name: "Price Alert",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "Automated notification system alerting buyers when watched items drop below specified price threshold. Available for Buy It Now listings only.",
    market: ["US", "UK", "DE", "AU"],
    year: 2018
  },
  {
    id: "similar-sponsored-items",
    name: "Similar Sponsored Items",
    type: "advertising",
    tier: "feature",
    status: "current",
    parent: "promoted-listings",
    desc: "Algorithmic recommendations module on product pages showing paid ads for related items from other sellers, driving cross-listing discovery and ad revenue.",
    market: "global",
    year: 2017
  },
  {
    id: "more-from-this-seller",
    name: "More From This Seller",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "Product page module showcasing additional items from the same seller to encourage multi-item purchases and store traffic.",
    market: "global",
    year: 2012
  },
  {
    id: "item-specifics-filter",
    name: "Item Specifics Filter",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Left rail refinement facets allowing buyers to filter by brand, size, color, condition, features and 50+ category-specific attributes for precision search.",
    market: "global",
    year: 2009
  },
  {
    id: "condition-filter",
    name: "Condition Filter",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Search refinement allowing buyers to filter by New, Open Box, Certified Refurbished, Seller Refurbished, Used (Like New, Very Good, Good, Acceptable), For Parts.",
    market: "global",
    year: 2007
  },
  {
    id: "location-filter",
    name: "Location Filter",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Search refinement by item location, distance from buyer ZIP code, or shipping origin country. Enables local pickup prioritization.",
    market: "global",
    year: 2004
  },
  {
    id: "price-range-filter",
    name: "Price Range Filter",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Search refinement allowing buyers to set minimum and maximum price bounds. Includes dynamic price histogram showing distribution of results by price tier.",
    market: "global",
    year: 2003
  },
  {
    id: "buy-it-now-filter",
    name: "Buy It Now Filter",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Search refinement to show only fixed-price or auction-with-BIN listings, excluding pure auction format for instant purchase preference.",
    market: "global",
    year: 2005
  },
  {
    id: "free-shipping-filter",
    name: "Free Shipping Filter",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Search refinement to show only listings with no shipping cost to buyer. High-engagement filter driving 30%+ higher conversion rates.",
    market: "global",
    year: 2011
  },
  {
    id: "returns-accepted-filter",
    name: "Returns Accepted Filter",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Search refinement to show only listings where seller accepts returns (30-day, 60-day, or seller-specified policy). Trust signal filter.",
    market: "global",
    year: 2013
  },
  {
    id: "authenticity-guarantee-filter",
    name: "Authenticity Guarantee Filter",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "authenticity-guarantee",
    desc: "Search refinement showing only luxury items eligible for third-party authentication inspection before delivery. Available in Handbags, Watches, Sneakers, Jewelry, Trading Cards.",
    market: ["US", "UK", "DE", "AU", "CA"],
    year: 2020
  },
  {
    id: "authorized-seller-filter",
    name: "Authorized Seller Filter",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Search refinement showing only sellers officially authorized by brand manufacturers to sell new products, providing warranty coverage and authenticity assurance.",
    market: ["US", "UK", "DE"],
    year: 2019
  },
  {
    id: "top-rated-filter",
    name: "Top Rated Filter",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "seller-performance-standards",
    desc: "Search refinement showing only Top Rated sellers (1% defect rate, 4.8+ ratings, 100+ transactions) for premium buyer protection and faster shipping.",
    market: "global",
    year: 2010
  },
  {
    id: "sold-items-filter",
    name: "Sold Items Filter",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Advanced search option to view completed/sold listings from last 90 days for market research, price comparison, and collectible valuation.",
    market: "global",
    year: 2006
  },
  {
    id: "ending-soon",
    name: "Ending Soon",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Sort option showing auctions ending within 1-24 hours, creating urgency for last-minute bidding and deal discovery.",
    market: "global",
    year: 2000
  },
  {
    id: "newly-listed",
    name: "Newly Listed",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Sort option showing items listed within last 24 hours, popular for limited-release products, collectibles, and competitive buyers seeking early access.",
    market: "global",
    year: 2004
  },
  {
    id: "best-match-sort",
    name: "Best Match Sort",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Default search ranking algorithm combining relevance, seller quality, price competitiveness, shipping speed, listing quality, and conversion signals.",
    market: "global",
    year: 2007
  },
  {
    id: "price-plus-shipping-sort",
    name: "Price + Shipping Sort",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Sort option showing total landed cost (item price + shipping + tax) from lowest to highest, revealing true deal value.",
    market: "global",
    year: 2003
  },
  {
    id: "distance-nearest-first",
    name: "Distance: Nearest First",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Sort option prioritizing items closest to buyer's location, useful for local pickup, heavy items, and fast delivery preference.",
    market: "global",
    year: 2008
  },
  {
    id: "condition-new-sort",
    name: "Condition: New Sort",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Sort option prioritizing brand new items over used/refurbished, surfacing factory-sealed products and retail stock first.",
    market: "global",
    year: 2011
  },
  {
    id: "view-item-page",
    name: "View Item Page",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "Core product detail page (VIP) displaying title, photos, description, price, seller info, shipping, returns, authenticity badges, and purchase CTA. 15B+ views annually.",
    market: "global",
    year: 1997
  },
  {
    id: "make-offer-button",
    name: "Make Offer Button",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "best-offer",
    desc: "Call-to-action on listings with Best Offer enabled, launching negotiation interface. Available on 30% of Buy It Now listings, 40% acceptance rate.",
    market: "global",
    year: 2005
  },
  {
    id: "add-to-watchlist",
    name: "Add to Watchlist",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "One-click action to save item for later, triggering price drop alerts, ending soon notifications, and recommendation signals. 400M+ items watched daily.",
    market: "global",
    year: 2002
  },
  {
    id: "share-this-item",
    name: "Share This Item",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "Social sharing buttons (Facebook, Twitter, Pinterest, Email, SMS) on item pages to drive viral traffic and gift discovery. 50M+ shares monthly.",
    market: "global",
    year: 2013
  },
  {
    id: "email-to-friend",
    name: "Email to Friend",
    type: "category",
    tier: "feature",
    status: "legacy",
    parent: "buyer",
    desc: "Original sharing feature allowing buyers to forward listing links via email form. Deprecated in favor of native Share buttons.",
    market: "global",
    year: 2001
  },
  {
    id: "report-this-item",
    name: "Report This Item",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Reporting tool for buyers to flag counterfeit items, prohibited listings, intellectual property violations, or suspicious activity. Triggers Trust & Safety review.",
    market: "global",
    year: 2003
  },

  // ===== SELLER TOOLS & LISTING MANAGEMENT (40 programs) =====

  {
    id: "bulk-listing-upload",
    name: "Bulk Listing Upload",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "CSV/Excel upload tool for creating 100+ listings simultaneously via File Exchange. Requires Business Policies setup. Used by 60% of high-volume sellers.",
    market: "global",
    year: 2010
  },
  {
    id: "turbo-lister",
    name: "Turbo Lister",
    type: "category",
    tier: "feature",
    status: "legacy",
    parent: "listing",
    desc: "Desktop application for offline listing creation and batch upload. Supported templates, inventory management, and scheduled listing. Sunset 2020, replaced by Seller Hub.",
    market: "global",
    year: 2004,
    renamedTo: "seller-hub"
  },
  {
    id: "relist-item",
    name: "Relist Item",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "One-click feature to republish unsold listing with original details. Qualifies for insertion fee credit if item sells on second listing (once per item).",
    market: "global",
    year: 2003
  },
  {
    id: "sell-similar",
    name: "Sell Similar",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Listing duplication tool copying all details from existing listing into new draft. Saves time for sellers with identical or variant inventory (sizes, colors).",
    market: "global",
    year: 2006
  },
  {
    id: "scheduled-listing",
    name: "Scheduled Listing",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Allows sellers to create listings in advance with specific publish date/time for product launches, seasonal releases, or peak traffic timing. $0.10 fee per listing.",
    market: "global",
    year: 2005
  },
  {
    id: "end-listing-early",
    name: "End Listing Early",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Seller action to terminate active listing before scheduled end time. For auctions with bids, can cancel with bid retraction. Excessive use triggers seller defects.",
    market: "global",
    year: 2000
  },
  {
    id: "revise-listing",
    name: "Revise Listing",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Edit tool for updating active listing details. Some changes restricted after bids/sales (title, category, format). Photos, description, price, quantity always editable.",
    market: "global",
    year: 2001
  },
  {
    id: "promote-similar-items",
    name: "Promote Similar Items",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "In-listing module showcasing seller's other items in same category. Drives multi-item purchases and store traffic. Automatically generated based on category and item specifics.",
    market: "global",
    year: 2014
  },
  {
    id: "custom-label",
    name: "Custom Label",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Seller-created tags (SKU, supplier, season, campaign) for internal inventory organization. Not visible to buyers. Used for reporting, promotions, and catalog management.",
    market: "global",
    year: 2015
  },
  {
    id: "multi-variation-listing",
    name: "Multi-Variation Listing",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Single listing supporting multiple SKU combinations (Size + Color, GB + Color) with independent inventory counts. Max 250 variations. Reduces listing fees, improves SEO.",
    market: "global",
    year: 2011
  },
  {
    id: "variation-specifics",
    name: "Variation Specifics",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Attribute selectors (dropdown/button) on multi-variation listings allowing buyers to choose Size, Color, Style, Capacity before purchase. Required for clothing, shoes, electronics.",
    market: "global",
    year: 2011
  },
  {
    id: "variation-photos",
    name: "Variation Photos",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Unique images per variation (e.g., each color has dedicated photo). Updates main image when buyer selects variation. Drives 25% higher conversion than generic photos.",
    market: "global",
    year: 2013
  },
  {
    id: "out-of-stock-listing",
    name: "Out of Stock Listing",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Listing state when quantity = 0 on multi-quantity/store inventory listings. Hidden from search but preserves listing history, watchers, and SEO. Reactivates when inventory added.",
    market: "global",
    year: 2012
  },
  {
    id: "quantity-available",
    name: "Quantity Available",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Inventory field on multi-quantity listings showing units in stock. Displays 'More than 10 available' when qty > 10 to hide total inventory from competitors.",
    market: "global",
    year: 2009
  },
  {
    id: "sold-quantity-display",
    name: "Sold Quantity Display",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Social proof counter on listings showing units sold (e.g., '500+ sold'). Drives urgency and trust. Visible on multi-quantity listings after 5+ sales.",
    market: "global",
    year: 2016
  },
  {
    id: "watchers-count",
    name: "Watchers Count",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Demand signal showing number of buyers watching item (e.g., '37 watchers'). Creates urgency for auctions, validates pricing for BIN. Only visible to seller above 50 watchers.",
    market: "global",
    year: 2007
  },
  {
    id: "view-count",
    name: "View Count",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Total page views on listing, visible to seller only. Used for diagnosing traffic quality, pricing issues, or search visibility problems.",
    market: "global",
    year: 2002
  },
  {
    id: "item-description-editor",
    name: "Item Description Editor",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "WYSIWYG HTML editor for listing descriptions with rich text, tables, images, videos. Supports templates, custom CSS (stores), and mobile preview.",
    market: "global",
    year: 2008
  },
  {
    id: "description-templates",
    name: "Description Templates",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Pre-built listing description layouts with seller branding, policies, and product sections. Saves time for consistent multi-listing creation. 50+ templates in Seller Hub.",
    market: "global",
    year: 2012
  },
  {
    id: "photo-uploader",
    name: "Photo Uploader",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Drag-and-drop image upload tool supporting up to 24 photos per listing (first 12 free, additional $0.15 each). Auto-optimizes for mobile, removes background (AI), enhances lighting.",
    market: "global",
    year: 2007
  },
  {
    id: "photo-background-removal",
    name: "Photo Background Removal",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "AI-powered tool automatically removing photo backgrounds to create clean white-background product images. Improves mobile conversion 15%. Free for all sellers.",
    market: "global",
    year: 2023
  },
  {
    id: "photo-enhancement",
    name: "Photo Enhancement",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "AI-powered image optimization adjusting brightness, contrast, sharpness, and color balance for professional presentation. Auto-applies on upload unless disabled.",
    market: "global",
    year: 2022
  },
  {
    id: "listing-analytics",
    name: "Listing Analytics",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Seller Hub dashboard showing views, watchers, conversion rate, traffic source, and search ranking per listing. Historical data for 90 days, exportable CSV.",
    market: "global",
    year: 2017
  },
  {
    id: "traffic-report",
    name: "Traffic Report",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Seller Hub report showing listing impressions, clicks, click-through rate, and traffic sources (search, browse, promoted, external) for performance optimization.",
    market: "global",
    year: 2016
  },
  {
    id: "sales-report",
    name: "Sales Report",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Seller Hub report with total sales, units sold, average sale price, transaction fees, net proceeds by date range. Filterable by category, listing format, or custom label.",
    market: "global",
    year: 2016
  },
  {
    id: "fee-illustrator",
    name: "Fee Illustrator",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Listing preview tool showing estimated eBay fees (insertion, final value, upgrade) before publishing. Helps sellers price competitively while maintaining profit margins.",
    market: "global",
    year: 2013
  },
  {
    id: "listing-quality-report",
    name: "Listing Quality Report",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Automated audit flagging listings with missing item specifics, low-quality photos, incomplete descriptions, or policy violations. Includes actionable improvement suggestions.",
    market: "global",
    year: 2018
  },
  {
    id: "search-standing-dashboard",
    name: "Search Standing Dashboard",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Seller Hub report showing search visibility score, Best Match ranking factors, and defect penalties impacting search placement. Updated daily.",
    market: "global",
    year: 2019
  },
  {
    id: "promoted-listings-dashboard",
    name: "Promoted Listings Dashboard",
    type: "advertising",
    tier: "feature",
    status: "current",
    parent: "promoted-listings",
    desc: "Campaign management interface for setting ad rates (1-20%), pausing/activating promotions, and viewing ROAS, impressions, clicks, sales by listing.",
    market: "global",
    year: 2016
  },
  {
    id: "ad-rate-recommendation",
    name: "Ad Rate Recommendation",
    type: "advertising",
    tier: "feature",
    status: "current",
    parent: "promoted-listings",
    desc: "Machine learning model suggesting optimal ad rate per listing based on category competition, margins, and conversion likelihood to maximize ROI.",
    market: "global",
    year: 2019
  },
  {
    id: "promoted-listings-standard",
    name: "Promoted Listings Standard",
    type: "advertising",
    tier: "product",
    status: "current",
    parent: "promoted-listings",
    desc: "Cost-per-sale ad product placing listings in top search results and browse pages. Sellers pay ad fee (2-20% of sale price) only when promoted listing generates sale.",
    market: "global",
    year: 2015
  },
  {
    id: "promoted-listings-advanced",
    name: "Promoted Listings Advanced",
    type: "advertising",
    tier: "product",
    status: "current",
    parent: "promoted-listings",
    desc: "Cost-per-click ad product for large sellers targeting keywords, categories, and audiences on/off eBay (Google, Bing, Facebook). Requires managed campaigns, min $500/month spend.",
    market: ["US", "UK", "DE", "AU"],
    year: 2020
  },
  {
    id: "campaign-bidding",
    name: "Campaign Bidding",
    type: "advertising",
    tier: "feature",
    status: "current",
    parent: "promoted-listings",
    desc: "Promoted Listings Advanced feature allowing sellers to set max CPC bids per keyword or audience segment for budget control and ROAS optimization.",
    market: ["US", "UK", "DE", "AU"],
    year: 2020
  },
  {
    id: "keyword-targeting",
    name: "Keyword Targeting",
    type: "advertising",
    tier: "feature",
    status: "current",
    parent: "promoted-listings",
    desc: "Promoted Listings Advanced feature enabling sellers to bid on specific search terms to appear in sponsored placements when buyers search those keywords.",
    market: ["US", "UK", "DE", "AU"],
    year: 2020
  },
  {
    id: "audience-targeting",
    name: "Audience Targeting",
    type: "advertising",
    tier: "feature",
    status: "current",
    parent: "promoted-listings",
    desc: "Promoted Listings Advanced feature using first-party data (browsing, purchase history, cart abandonment) to target high-intent buyer segments.",
    market: ["US", "UK", "DE", "AU"],
    year: 2021
  },
  {
    id: "offsite-ads",
    name: "Offsite Ads",
    type: "advertising",
    tier: "program",
    status: "current",
    parent: "ebay-advertising",
    desc: "Automatic program promoting seller listings on Google, Facebook, Instagram, Bing. Sellers pay 8-12% of sale when traffic from offsite ad converts. Mandatory for sellers >$10K annual sales.",
    market: ["US", "UK", "DE"],
    year: 2020
  },
  {
    id: "offsite-ads-opt-out",
    name: "Offsite Ads Opt Out",
    type: "advertising",
    tier: "feature",
    status: "current",
    parent: "ebay-advertising",
    desc: "Option for sellers under $10K annual sales to disable Offsite Ads and avoid 12% ad fee on externally-sourced sales. Reduces traffic but protects margins.",
    market: ["US", "UK", "DE"],
    year: 2020
  },
  {
    id: "seller-coupon",
    name: "Seller Coupon",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "marketing",
    desc: "Promotional tool allowing sellers to create discount codes ($ off or % off) for targeted buyer segments, cart abandoners, or store subscribers. Tracked in marketing dashboard.",
    market: "global",
    year: 2018
  },
  {
    id: "markdown-manager",
    name: "Markdown Manager",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "marketing",
    desc: "Bulk pricing tool for discounting slow-moving inventory. Sellers set rules (e.g., reduce 10% after 30 days unsold) and system auto-applies markdowns with strikethrough display.",
    market: "global",
    year: 2019
  },
  {
    id: "volume-pricing",
    name: "Volume Pricing",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Tiered discount pricing for multi-quantity purchases (e.g., Buy 2 save 5%, Buy 5 save 10%). Automatically calculated at checkout, displayed on listing.",
    market: "global",
    year: 2014
  },

  // ===== PAYMENTS & CHECKOUT (25 programs) =====

  {
    id: "managed-payments",
    name: "Managed Payments",
    type: "category",
    tier: "platform",
    status: "current",
    parent: "payments",
    desc: "eBay's proprietary payment processing platform replacing PayPal as primary checkout (2018-2021 migration). Handles credit cards, debit, Apple Pay, Google Pay, PayPal integration.",
    market: "global",
    year: 2018
  },
  {
    id: "payment-processing",
    name: "Payment Processing",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Checkout infrastructure processing 1.5B+ transactions annually through Managed Payments with Adyen backend, supporting 20+ payment methods globally.",
    market: "global",
    year: 2018
  },
  {
    id: "instant-payout",
    name: "Instant Payout",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Optional service depositing seller funds to linked debit card within minutes of sale (vs. 2-day standard). 1% fee, max $1,000 per day.",
    market: "US",
    year: 2020
  },
  {
    id: "daily-payout",
    name: "Daily Payout",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Standard payout cadence depositing funds to seller bank account daily (next business day). Default for Managed Payments sellers. Replaces PayPal instant access.",
    market: "global",
    year: 2019
  },
  {
    id: "weekly-payout",
    name: "Weekly Payout",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Alternate payout schedule depositing funds every 7 days. Available for sellers preferring consolidated accounting or managing cash flow timing.",
    market: "global",
    year: 2019
  },
  {
    id: "payment-holds",
    name: "Payment Holds",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Risk mitigation system holding seller funds for 21 days (new sellers) or until tracking shows delivery (performance issues). Protects buyers from non-delivery, fraud.",
    market: "global",
    year: 2009
  },
  {
    id: "payment-dispute",
    name: "Payment Dispute",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Buyer-initiated chargeback through credit card issuer or PayPal for unauthorized transaction, item not received, or not as described. Separate from eBay Money Back Guarantee.",
    market: "global",
    year: 2005
  },
  {
    id: "seller-transaction-report",
    name: "Seller Transaction Report",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Downloadable CSV of all transactions, fees, refunds, payouts for accounting integration. Includes order ID, buyer, amount, fees, net proceeds. Monthly tax summary included.",
    market: "global",
    year: 2019
  },
  {
    id: "1099-k-tax-form",
    name: "1099-K Tax Form",
    type: "category",
    tier: "legal",
    status: "current",
    parent: "payments",
    desc: "IRS tax document issued to US sellers with 200+ transactions OR $20K+ gross sales annually reporting payment card and third-party network transactions.",
    market: "US",
    year: 2011
  },
  {
    id: "sales-tax-collection",
    name: "Sales Tax Collection",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Automated tax calculation and remittance system collecting state/local sales tax based on buyer location. eBay files returns and remits tax in 35+ states (Internet Sales Tax laws).",
    market: "US",
    year: 2019
  },
  {
    id: "vat-collection",
    name: "VAT Collection",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Value-Added Tax collection for EU/UK transactions. eBay acts as deemed supplier collecting 20-27% VAT on low-value imports (<€150) and remitting to tax authorities.",
    market: ["UK", "DE", "FR", "IT"],
    year: 2021
  },
  {
    id: "guest-checkout",
    name: "Guest Checkout",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Checkout flow allowing buyers to purchase without creating eBay account. Requires email, shipping address, payment method. Reduces friction, increases mobile conversion 12%.",
    market: "global",
    year: 2016
  },
  {
    id: "saved-payment-methods",
    name: "Saved Payment Methods",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Secure vault storing buyer credit cards, debit cards, PayPal accounts for one-click checkout. PCI-compliant tokenization, no card numbers stored on eBay servers.",
    market: "global",
    year: 2010
  },
  {
    id: "auto-pay",
    name: "Auto Pay",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Setting to automatically charge saved payment method immediately after Buy It Now or winning auction bid, eliminating manual checkout step.",
    market: "global",
    year: 2012
  },
  {
    id: "combined-shipping-discount",
    name: "Combined Shipping Discount",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Seller-configured discount applying reduced shipping cost when buyer purchases multiple items. Rules: flat rate, percentage off, or free shipping after N items.",
    market: "global",
    year: 2007
  },
  {
    id: "shipping-calculator",
    name: "Shipping Calculator",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Checkout tool calculating shipping cost based on buyer ZIP/postal code, package dimensions, carrier service level. Shows estimated delivery date before purchase.",
    market: "global",
    year: 2006
  },
  {
    id: "calculated-shipping",
    name: "Calculated Shipping",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Dynamic shipping pricing using real-time carrier rates (USPS, FedEx, UPS) based on item weight, dimensions, and buyer location. Seller pays exact cost, no profit on shipping.",
    market: ["US", "UK", "AU", "CA"],
    year: 2008
  },
  {
    id: "flat-rate-shipping",
    name: "Flat Rate Shipping",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Fixed shipping price set by seller regardless of buyer location. Simplifies checkout but may overcharge nearby buyers or undercharge distant buyers.",
    market: "global",
    year: 2003
  },
  {
    id: "free-shipping-threshold",
    name: "Free Shipping Threshold",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Seller promotion offering free shipping when cart total exceeds specified amount (e.g., Free shipping over $50). Drives multi-item purchases, higher AOV.",
    market: "global",
    year: 2015
  },
  {
    id: "local-pickup",
    name: "Local Pickup",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Shipping option allowing buyers to collect items in person at seller location, eliminating shipping cost. Popular for furniture, vehicles, heavy equipment.",
    market: "global",
    year: 2005
  },
  {
    id: "global-shipping-program",
    name: "Global Shipping Program",
    type: "category",
    tier: "program",
    status: "legacy",
    parent: "shipping",
    desc: "Legacy program where sellers shipped to US hub, eBay handled international shipping/customs. Replaced by eBay International Shipping 2021.",
    market: ["US", "UK", "DE", "AU"],
    year: 2012,
    renamedTo: "ebay-international-shipping"
  },
  {
    id: "ebay-international-shipping",
    name: "eBay International Shipping",
    type: "category",
    tier: "program",
    status: "current",
    parent: "shipping",
    desc: "Replacement for GSP allowing sellers to ship to domestic hub with eBay handling customs, international shipping, import fees. Buyer sees total landed cost at checkout.",
    market: "global",
    year: 2021
  },
  {
    id: "international-standard-delivery",
    name: "International Standard Delivery",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Shipping service level for cross-border purchases with 11-23 business day delivery windows. Trackable, customs forms auto-generated.",
    market: "global",
    year: 2014
  },
  {
    id: "expedited-international-shipping",
    name: "Expedited International Shipping",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Premium cross-border shipping with 6-10 business day delivery via FedEx/UPS/DHL. Includes tracking, insurance, signature confirmation.",
    market: "global",
    year: 2009
  },
  {
    id: "import-charges",
    name: "Import Charges",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Customs duties, VAT, import taxes prepaid at checkout for international orders. eBay calculates, collects, and remits to customs authorities, ensuring no surprise fees on delivery.",
    market: "global",
    year: 2018
  },

  // ===== CUSTOMER SERVICE & SUPPORT (20 programs) =====

  {
    id: "ebay-customer-service",
    name: "eBay Customer Service",
    type: "category",
    tier: "organization",
    status: "current",
    parent: "support",
    desc: "24/7 support center with phone, chat, email channels for buyer and seller assistance. Handles account issues, transaction disputes, policy questions, technical troubleshooting.",
    market: "global",
    year: 1999
  },
  {
    id: "live-chat-support",
    name: "Live Chat Support",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "support",
    desc: "Real-time text-based support available 24/7 in Help Center for immediate assistance. Avg wait time <2 minutes, resolution rate 85% in first session.",
    market: ["US", "UK", "DE", "AU"],
    year: 2017
  },
  {
    id: "phone-support",
    name: "Phone Support",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "support",
    desc: "Voice support line available 5am-9pm PT for complex issues, account security, high-value disputes. Dedicated lines for Top Rated and enterprise sellers.",
    market: ["US", "UK", "AU"],
    year: 2003
  },
  {
    id: "help-center",
    name: "Help Center",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "support",
    desc: "Self-service knowledge base with 5,000+ articles covering selling, buying, policies, troubleshooting. Includes AI-powered search, video tutorials, community forum integration.",
    market: "global",
    year: 2004
  },
  {
    id: "virtual-assistant",
    name: "Virtual Assistant",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "support",
    desc: "AI-powered chatbot answering common questions (tracking, returns, account access) with 70% automation rate. Escalates complex cases to human agents.",
    market: "global",
    year: 2019
  },
  {
    id: "community-forums",
    name: "Community Forums",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "support",
    desc: "Peer-to-peer discussion boards organized by topic (Shipping, Selling, eBay Stores, Motors) where 2M+ members share advice. Volunteer Power Sellers moderate.",
    market: "global",
    year: 2001
  },
  {
    id: "seller-community",
    name: "Seller Community",
    type: "category",
    tier: "program",
    status: "current",
    parent: "community",
    desc: "Online forum for seller networking, best practice sharing, and policy announcements. Includes regional boards, vertical-specific groups, and eBay staff participation.",
    market: "global",
    year: 2005
  },
  {
    id: "ebay-radio",
    name: "eBay Radio",
    type: "category",
    tier: "event",
    status: "legacy",
    parent: "education",
    desc: "Weekly podcast/webinar series featuring eBay experts discussing selling strategies, platform updates, and seller success stories. Discontinued 2019.",
    market: "US",
    year: 2006
  },
  {
    id: "seller-newsletter",
    name: "Seller Newsletter",
    type: "category",
    tier: "publication",
    status: "current",
    parent: "education",
    desc: "Monthly email digest for sellers highlighting policy changes, seasonal tips, feature launches, and success stories. Customized by seller tier (Above Standard, Top Rated, Stores).",
    market: "global",
    year: 2007
  },
  {
    id: "seller-updates",
    name: "Seller Updates",
    type: "category",
    tier: "publication",
    status: "current",
    parent: "education",
    desc: "Quarterly announcement blog detailing fee changes, policy updates, new features, and platform roadmap. Required reading for serious sellers, often includes 60+ day advance notice.",
    market: "global",
    year: 2010
  },
  {
    id: "selling-coach",
    name: "Selling Coach",
    type: "category",
    tier: "feature",
    status: "legacy",
    parent: "education",
    desc: "Automated recommendation engine suggesting pricing, categories, item specifics based on listing analysis. Deprecated 2018, replaced by Listing Quality Report.",
    market: "global",
    year: 2009,
    renamedTo: "listing-quality-report"
  },
  {
    id: "seller-hub-tasks",
    name: "Seller Hub Tasks",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Actionable to-do list in Seller Hub showing awaiting shipment, buyer messages, returns, payment holds, listing renewals. Prioritized by urgency.",
    market: "global",
    year: 2016
  },
  {
    id: "awaiting-shipment",
    name: "Awaiting Shipment",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Seller Hub view showing orders requiring tracking upload or mark-as-shipped action. Color-coded by handling time deadline (green: on time, red: overdue).",
    market: "global",
    year: 2016
  },
  {
    id: "buyer-messages",
    name: "Buyer Messages",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Seller Hub inbox for buyer questions about listings, shipping, returns. Response time tracked in seller performance (24hr response recommended). Integrated with mobile app.",
    market: "global",
    year: 2008
  },
  {
    id: "message-center",
    name: "Message Center",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "Buyer inbox for seller communications, eBay notifications, promotional messages. Archive, search, and flag capabilities. Accessible via web and mobile app.",
    market: "global",
    year: 2004
  },
  {
    id: "ask-seller-question",
    name: "Ask Seller a Question",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "Pre-purchase messaging tool on item pages allowing buyers to inquire about condition, shipping, compatibility. Sellers encouraged to respond within 24 hours for trust signal.",
    market: "global",
    year: 2002
  },
  {
    id: "report-buyer",
    name: "Report Buyer",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Seller tool to flag buyers for non-payment, abusive messages, feedback extortion, or repeat return abuse. Triggers Trust & Safety investigation.",
    market: "global",
    year: 2006
  },
  {
    id: "block-buyer-list",
    name: "Block Buyer List",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Seller control allowing up to 5,000 buyer usernames to be blocked from purchasing. Prevents problem buyers, competitors, or abusive actors from transacting.",
    market: "global",
    year: 2008
  },
  {
    id: "unpaid-item-assistant",
    name: "Unpaid Item Assistant",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Automated tool that opens unpaid item cases after 4 days of non-payment and closes/refunds after 30 days. Records buyer strike, allows seller to block repeat offenders.",
    market: "global",
    year: 2012
  },
  {
    id: "buyer-requirements",
    name: "Buyer Requirements",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Seller settings to block buyers with unpaid item strikes, negative feedback score, or located in countries not shipped to. Reduces fraud, non-payment risk.",
    market: "global",
    year: 2010
  },

  // ===== TRUST & SAFETY PROGRAMS (20 programs) =====

  {
    id: "account-security",
    name: "Account Security",
    type: "trust",
    tier: "program",
    status: "current",
    parent: "trust",
    desc: "Multi-layered protection including password strength requirements, 2FA, login alerts, session management, and breach monitoring to prevent account takeovers.",
    market: "global",
    year: 2004
  },
  {
    id: "two-factor-authentication",
    name: "Two-Factor Authentication",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Optional security layer requiring SMS code, authenticator app, or security key in addition to password for login. Reduces account compromises 99.9%.",
    market: "global",
    year: 2016
  },
  {
    id: "login-alerts",
    name: "Login Alerts",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Email/SMS notifications when account accessed from new device, location, or IP address. Allows users to secure account if unauthorized login detected.",
    market: "global",
    year: 2013
  },
  {
    id: "password-reset",
    name: "Password Reset",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Self-service account recovery flow using email, phone verification, or security questions. Additional identity verification required for high-value accounts.",
    market: "global",
    year: 2000
  },
  {
    id: "verify-account",
    name: "Verify Account",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Identity confirmation process requiring phone number, address, payment method verification for new accounts or high-risk activity. Reduces fraud, bot accounts.",
    market: "global",
    year: 2011
  },
  {
    id: "seller-verification",
    name: "Seller Verification",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Enhanced identity check for new sellers requiring government ID, business registration, or tax ID upload. Mandatory for high-value categories (luxury, electronics).",
    market: ["US", "UK", "DE"],
    year: 2019
  },
  {
    id: "vero-program",
    name: "VeRO Program",
    type: "trust",
    tier: "program",
    status: "current",
    parent: "trust",
    desc: "Verified Rights Owner program allowing brands to report counterfeit, trademark, copyright violations for removal. 30,000+ participating brands, 1M+ monthly takedowns.",
    market: "global",
    year: 2000
  },
  {
    id: "counterfeit-detection",
    name: "Counterfeit Detection",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Machine learning system scanning listings for counterfeit signals (keywords, pricing, seller history) and blocking before publication. 95% accuracy, blocks 1M+ listings annually.",
    market: "global",
    year: 2017
  },
  {
    id: "prohibited-items-list",
    name: "Prohibited Items List",
    type: "trust",
    tier: "legal",
    status: "current",
    parent: "trust",
    desc: "Policy document detailing items banned from sale: weapons, drugs, tobacco, alcohol (most markets), recalled products, hazmat, human remains, stolen goods.",
    market: "global",
    year: 1999
  },
  {
    id: "listing-removal-notice",
    name: "Listing Removal Notice",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Automated notification sent when listing violates policy and is removed. Includes violation reason, policy link, appeal instructions. Excessive removals trigger account restrictions.",
    market: "global",
    year: 2003
  },
  {
    id: "selling-restrictions",
    name: "Selling Restrictions",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Account limitations applied to sellers with policy violations, performance defects, or fraud signals. Restricts listing categories, quantity, or requires pre-approval.",
    market: "global",
    year: 2005
  },
  {
    id: "buying-restrictions",
    name: "Buying Restrictions",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Account limitations on buyers with unpaid items, return abuse, or fraudulent activity. Caps monthly purchase limits, restricts high-value transactions, requires verified payment.",
    market: "global",
    year: 2009
  },
  {
    id: "account-suspension",
    name: "Account Suspension",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Temporary or permanent account restriction preventing buying, selling, or messaging due to serious policy violations, fraud, or legal orders. Appeal process available.",
    market: "global",
    year: 2001
  },
  {
    id: "indefinite-suspension",
    name: "Indefinite Suspension",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "trust",
    desc: "Permanent account ban with no reinstatement option. Applied for repeat offenders, criminal activity, trademark infringement, or egregious policy abuse.",
    market: "global",
    year: 2004
  },
  {
    id: "linked-accounts-policy",
    name: "Linked Accounts Policy",
    type: "trust",
    tier: "legal",
    status: "current",
    parent: "trust",
    desc: "Policy prohibiting suspended users from creating new accounts via same device, IP, address, payment method. Enforced via device fingerprinting and identity linking.",
    market: "global",
    year: 2008
  },
  {
    id: "feedback-extortion-policy",
    name: "Feedback Extortion Policy",
    type: "trust",
    tier: "legal",
    status: "current",
    parent: "feedback",
    desc: "Prohibition against buyers threatening negative feedback to extort refunds, free items, or other concessions. Violators receive feedback removal and account restrictions.",
    market: "global",
    year: 2007
  },
  {
    id: "shill-bidding-policy",
    name: "Shill Bidding Policy",
    type: "trust",
    tier: "legal",
    status: "current",
    parent: "trust",
    desc: "Prohibition against sellers or associates bidding on own auctions to inflate prices. Enforced via IP tracking, bidding patterns, linked accounts. Results in suspension.",
    market: "global",
    year: 1999
  },
  {
    id: "bid-shielding-policy",
    name: "Bid Shielding Policy",
    type: "trust",
    tier: "legal",
    status: "current",
    parent: "trust",
    desc: "Prohibition against colluding bidders placing high bids to discourage others, then retracting before auction end. Enforced via bidding behavior analysis.",
    market: "global",
    year: 2002
  },
  {
    id: "transaction-interference-policy",
    name: "Transaction Interference Policy",
    type: "trust",
    tier: "legal",
    status: "current",
    parent: "trust",
    desc: "Prohibition against contacting buyers to complete sales outside eBay (fee avoidance), offering competing items on active auctions, or sabotaging competitor listings.",
    market: "global",
    year: 2004
  },
  {
    id: "privacy-policy",
    name: "Privacy Policy",
    type: "trust",
    tier: "legal",
    status: "current",
    parent: "trust",
    desc: "Legal document governing collection, use, sharing of user data. Covers transaction data, browsing history, marketing preferences, third-party integrations, GDPR/CCPA compliance.",
    market: "global",
    year: 1998
  },

  // ===== MOBILE & APP FEATURES (15 programs) =====

  {
    id: "ebay-mobile-app",
    name: "eBay Mobile App",
    type: "category",
    tier: "platform",
    status: "current",
    parent: "buyer",
    desc: "iOS and Android native app with 200M+ downloads, driving 60% of GMV. Features include barcode scanner, image search, push notifications, saved searches, mobile-exclusive deals.",
    market: "global",
    year: 2008
  },
  {
    id: "mobile-web",
    name: "Mobile Web",
    type: "category",
    tier: "platform",
    status: "current",
    parent: "buyer",
    desc: "Responsive mobile website (m.ebay.com) optimized for smartphone browsers. Lighter alternative to app with core buying/selling functionality.",
    market: "global",
    year: 2011
  },
  {
    id: "barcode-scanner",
    name: "Barcode Scanner",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "Mobile app feature using camera to scan UPC/EAN barcodes for instant product lookup, price comparison, and listing search. Popular for retail arbitrage, collectibles.",
    market: "global",
    year: 2013
  },
  {
    id: "image-search",
    name: "Image Search",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Visual search tool allowing users to upload/snap photo and find similar items using computer vision. Identifies products, styles, patterns. 100M+ searches monthly.",
    market: "global",
    year: 2017
  },
  {
    id: "push-notifications",
    name: "Push Notifications",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "notifications",
    desc: "Mobile app alerts for outbid notices, ending soon auctions, price drops, shipping updates, messages, promotional offers. Customizable by category.",
    market: "global",
    year: 2010
  },
  {
    id: "in-app-messaging",
    name: "In-App Messaging",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "Real-time chat between buyers and sellers within mobile app for pre-purchase questions, shipping coordination, return requests. Higher response rate than email.",
    market: "global",
    year: 2015
  },
  {
    id: "mobile-quick-list",
    name: "Mobile Quick List",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Simplified mobile listing flow using photo recognition to auto-populate title, category, item specifics, pricing suggestions. List in <60 seconds.",
    market: "global",
    year: 2019
  },
  {
    id: "augmented-reality-preview",
    name: "Augmented Reality Preview",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "iOS app feature using ARKit to visualize furniture, decor items in buyer's space via camera before purchase. Available in Home & Garden categories.",
    market: ["US", "UK", "AU"],
    year: 2021
  },
  {
    id: "mobile-checkout",
    name: "Mobile Checkout",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Optimized one-tap purchase flow on mobile with Apple Pay, Google Pay, saved addresses, autofill. 40% faster than desktop checkout.",
    market: "global",
    year: 2014
  },
  {
    id: "shake-to-search",
    name: "Shake to Search",
    type: "category",
    tier: "feature",
    status: "legacy",
    parent: "search",
    desc: "Mobile app Easter egg feature triggering random category search when device shaken. Removed 2019 due to low usage.",
    market: "global",
    year: 2016
  },
  {
    id: "mobile-seller-hub",
    name: "Mobile Seller Hub",
    type: "category",
    tier: "platform",
    status: "current",
    parent: "seller-hub",
    desc: "iOS/Android app for sellers to manage orders, upload tracking, respond to messages, view analytics, create listings on-the-go. 50M+ monthly active users.",
    market: "global",
    year: 2017
  },
  {
    id: "mobile-photo-editor",
    name: "Mobile Photo Editor",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "In-app photo editing tools for crop, rotate, brightness, contrast, background removal, text overlay. Optimizes listing images without external apps.",
    market: "global",
    year: 2020
  },
  {
    id: "mobile-analytics",
    name: "Mobile Analytics",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Seller Hub mobile app dashboard showing sales, traffic, conversion rates, promoted listings ROI. Real-time updates, customizable date ranges.",
    market: "global",
    year: 2018
  },
  {
    id: "mobile-deals",
    name: "Mobile Deals",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-deals",
    desc: "App-exclusive discounts and flash sales with 10-30% off trending products. Rotates every 4 hours, push notification alerts. Drives app stickiness.",
    market: ["US", "UK", "DE"],
    year: 2019
  },
  {
    id: "app-store-promotion",
    name: "App Store Promotion",
    type: "category",
    tier: "campaign",
    status: "current",
    parent: "marketing",
    desc: "eBay-funded acquisition campaigns on Apple App Store, Google Play featuring discounts for new app users. $5-10 off first purchase via app.",
    market: "global",
    year: 2016
  },

  // ===== VERTICAL-SPECIFIC PROGRAMS (20 programs) =====

  {
    id: "ebay-motors-parts",
    name: "eBay Motors Parts & Accessories",
    type: "category",
    tier: "vertical",
    status: "current",
    parent: "ebay-motors",
    desc: "Sub-vertical for automotive parts, tires, tools, accessories with compatibility fitment tables, VIN lookup, OEM/aftermarket filters.",
    market: ["US", "UK", "DE", "AU"],
    year: 2000
  },
  {
    id: "fitment-compatibility",
    name: "Fitment Compatibility",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-motors",
    desc: "Database matching auto parts to specific vehicle years/makes/models. Sellers upload compatibility data, buyers search by their vehicle for guaranteed fit parts.",
    market: ["US", "UK", "DE", "AU"],
    year: 2008
  },
  {
    id: "vin-lookup",
    name: "VIN Lookup",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-motors",
    desc: "Vehicle Identification Number decoder showing exact year, make, model, trim, engine specs for precise parts compatibility matching.",
    market: ["US", "UK", "DE", "AU"],
    year: 2012
  },
  {
    id: "vehicle-history-report",
    name: "Vehicle History Report",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "ebay-motors",
    desc: "Free AutoCheck vehicle history report on Motors listings showing accidents, title issues, odometer fraud, ownership count. Trust signal for high-value purchases.",
    market: "US",
    year: 2015
  },
  {
    id: "classified-ads",
    name: "Classified Ads",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-motors",
    desc: "Local-only listing format for vehicles, real estate, heavy equipment. No auction/BIN, seller shows phone number, buyers contact directly. $40-125 insertion fee.",
    market: ["US", "UK", "DE", "IT"],
    year: 2005
  },
  {
    id: "sneaker-authentication",
    name: "Sneaker Authentication",
    type: "trust",
    tier: "program",
    status: "current",
    parent: "authenticity-guarantee",
    desc: "Third-party inspection service for sneakers $100+ verifying authenticity via Hypebeast-trained authenticators before shipment to buyer. 1-2 day delay, free service.",
    market: ["US", "UK", "DE", "CA", "AU"],
    year: 2020
  },
  {
    id: "trading-card-authentication",
    name: "Trading Card Authentication",
    type: "trust",
    tier: "program",
    status: "current",
    parent: "authenticity-guarantee",
    desc: "Professional grading service for trading cards $250+ using PSA/BGS authenticators verifying condition, grade accuracy, case integrity before delivery.",
    market: ["US", "UK"],
    year: 2021
  },
  {
    id: "jewelry-authentication",
    name: "Jewelry Authentication",
    type: "trust",
    tier: "program",
    status: "current",
    parent: "authenticity-guarantee",
    desc: "GIA-certified gemologist inspection for jewelry $2,000+ verifying metal purity, gemstone authenticity, craftsmanship quality. 3-5 day delay.",
    market: ["US", "UK"],
    year: 2022
  },
  {
    id: "handbag-authentication",
    name: "Handbag Authentication",
    type: "trust",
    tier: "program",
    status: "current",
    parent: "authenticity-guarantee",
    desc: "Luxury authenticator inspection for designer handbags $500+ (Louis Vuitton, Chanel, Gucci, Hermès) verifying materials, stitching, hardware, serial numbers.",
    market: ["US", "UK", "DE", "AU"],
    year: 2020
  },
  {
    id: "watch-authentication",
    name: "Watch Authentication",
    type: "trust",
    tier: "program",
    status: "current",
    parent: "authenticity-guarantee",
    desc: "Horologist inspection for luxury watches $2,000+ (Rolex, Omega, Patek Philippe) verifying movement, case, dial, documentation authenticity.",
    market: ["US", "UK"],
    year: 2021
  },
  {
    id: "sports-memorabilia",
    name: "Sports Memorabilia",
    type: "category",
    tier: "vertical",
    status: "current",
    parent: "collectibles",
    desc: "Category for autographed jerseys, game-used equipment, trading cards, championship rings with COA requirement for high-value items.",
    market: "global",
    year: 2000
  },
  {
    id: "certificate-of-authenticity",
    name: "Certificate of Authenticity",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "collectibles",
    desc: "Third-party authentication documentation (PSA/DNA, JSA, Beckett) required for autographed sports memorabilia $250+ to combat forgeries.",
    market: ["US", "UK"],
    year: 2011
  },
  {
    id: "coins-currency",
    name: "Coins & Currency",
    type: "category",
    tier: "vertical",
    status: "current",
    parent: "collectibles",
    desc: "Numismatics category for rare coins, paper money, bullion with grading standards (NGC, PCGS), precious metal spot pricing integration.",
    market: "global",
    year: 1999
  },
  {
    id: "stamps",
    name: "Stamps",
    type: "category",
    tier: "vertical",
    status: "current",
    parent: "collectibles",
    desc: "Philately category for postage stamps, first day covers, postal history with condition grading (mint, used, hinged) and catalog value references (Scott, Stanley Gibbons).",
    market: "global",
    year: 1999
  },
  {
    id: "antiques",
    name: "Antiques",
    type: "category",
    tier: "vertical",
    status: "current",
    parent: "collectibles",
    desc: "Category for items 100+ years old including furniture, pottery, glassware, art, textiles with provenance documentation and appraisal support.",
    market: "global",
    year: 2000
  },
  {
    id: "fine-art",
    name: "Fine Art",
    type: "category",
    tier: "vertical",
    status: "current",
    parent: "collectibles",
    desc: "Category for paintings, sculptures, prints, photography with artist verification, provenance tracking, authenticity certification requirements for $1,000+ pieces.",
    market: "global",
    year: 2003
  },
  {
    id: "comics",
    name: "Comics",
    type: "category",
    tier: "vertical",
    status: "current",
    parent: "collectibles",
    desc: "Comic book category with CGC/CBCS grading integration, key issue pricing, variant tracking, and Golden/Silver/Bronze Age designations.",
    market: "global",
    year: 2001
  },
  {
    id: "video-games",
    name: "Video Games",
    type: "category",
    tier: "vertical",
    status: "current",
    parent: "category",
    desc: "Gaming vertical for consoles, physical games, accessories, retro systems with platform compatibility filters (PlayStation, Xbox, Nintendo, PC).",
    market: "global",
    year: 2002
  },
  {
    id: "wata-grading",
    name: "WATA Grading",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "collectibles",
    desc: "Video game grading integration for sealed games showing WATA/VGA grade (1-10), seal integrity, packaging condition for investment-grade collectibles.",
    market: ["US", "UK"],
    year: 2020
  },
  {
    id: "business-industrial",
    name: "Business & Industrial",
    type: "category",
    tier: "vertical",
    status: "current",
    parent: "category",
    desc: "B2B vertical for commercial equipment, manufacturing tools, restaurant supplies, construction machinery, medical devices with freight shipping support.",
    market: "global",
    year: 2005
  },

  // ===== SEASONAL & PROMOTIONAL PROGRAMS (15 programs) =====

  {
    id: "black-friday-deals",
    name: "Black Friday Deals",
    type: "category",
    tier: "campaign",
    status: "current",
    parent: "ebay-deals",
    desc: "Annual November event with 70%+ off discounts, doorbusters rotating hourly, exclusive seller participation requiring 4.8+ rating and 30-day returns.",
    market: ["US", "UK", "DE", "AU"],
    year: 2010
  },
  {
    id: "cyber-monday",
    name: "Cyber Monday",
    type: "category",
    tier: "campaign",
    status: "current",
    parent: "ebay-deals",
    desc: "Annual post-Thanksgiving online shopping event with tech/electronics focus, $5-10 off coupons for app users, free shipping promotions.",
    market: ["US", "UK", "AU"],
    year: 2011
  },
  {
    id: "holiday-gift-guide",
    name: "Holiday Gift Guide",
    type: "category",
    tier: "campaign",
    status: "current",
    parent: "marketing",
    desc: "Seasonal curated collections (November-December) organized by recipient type (him/her/kids/home) with guaranteed delivery by Christmas cutoff dates.",
    market: "global",
    year: 2007
  },
  {
    id: "guaranteed-delivery",
    name: "Guaranteed Delivery",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Seasonal promise (October-December) showing exact delivery date before purchase. eBay refunds shipping if late. Requires 1-day handling, tracking, fast carriers.",
    market: ["US", "UK", "AU"],
    year: 2016
  },
  {
    id: "daily-deals",
    name: "Daily Deals",
    type: "category",
    tier: "program",
    status: "current",
    parent: "ebay-deals",
    desc: "Year-round rotating offers featuring 20-80% off trending products in spotlight categories. Changes 10am PT daily, limited inventory, featured on homepage.",
    market: "global",
    year: 2012
  },
  {
    id: "flash-deals",
    name: "Flash Deals",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-deals",
    desc: "Time-limited offers (1-6 hours) with countdown timer creating urgency. Mobile push notification alerts, 50-90% off clearance inventory.",
    market: ["US", "UK", "DE"],
    year: 2018
  },
  {
    id: "ebay-bucks",
    name: "eBay Bucks",
    type: "category",
    tier: "program",
    status: "legacy",
    parent: "marketing",
    desc: "Cashback rewards program (2017-2021) giving 1-10% back on purchases as certificates. Replaced by eBay Coupons and promotional credits.",
    market: "US",
    year: 2017,
    renamedTo: "promotional-credit"
  },
  {
    id: "promotional-credit",
    name: "Promotional Credit",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "marketing",
    desc: "eBay-issued vouchers ($5-100) for service failures, retention offers, survey incentives, influencer partnerships. 30-90 day expiration.",
    market: "global",
    year: 2021
  },
  {
    id: "seasonal-seller-standards",
    name: "Seasonal Seller Standards",
    type: "trust",
    tier: "program",
    status: "current",
    parent: "seller-performance-standards",
    desc: "Relaxed performance evaluation during Q4 (Oct-Dec) holiday surge extending handling time grace periods and defect rate thresholds by 20% to accommodate volume.",
    market: "global",
    year: 2014
  },
  {
    id: "spring-clearance",
    name: "Spring Clearance",
    type: "category",
    tier: "campaign",
    status: "current",
    parent: "ebay-deals",
    desc: "Annual March-April event for sellers to liquidate winter inventory with sitewide coupons, free listings, promoted listing discounts.",
    market: ["US", "UK"],
    year: 2015
  },
  {
    id: "back-to-school",
    name: "Back to School",
    type: "category",
    tier: "campaign",
    status: "current",
    parent: "marketing",
    desc: "August-September promotional event for student essentials (laptops, backpacks, dorm, supplies) with education discounts, tax-free promotions in participating states.",
    market: ["US", "UK"],
    year: 2012
  },
  {
    id: "mothers-day-gifts",
    name: "Mother's Day Gifts",
    type: "category",
    tier: "campaign",
    status: "current",
    parent: "marketing",
    desc: "May seasonal landing page curating jewelry, flowers, personalized items, spa/beauty with guaranteed Mother's Day delivery cutoff dates.",
    market: "global",
    year: 2008
  },
  {
    id: "fathers-day-gifts",
    name: "Father's Day Gifts",
    type: "category",
    tier: "campaign",
    status: "current",
    parent: "marketing",
    desc: "June seasonal campaign featuring tools, tech, automotive, sports memorabilia with gift wrapping options and guaranteed Father's Day delivery.",
    market: "global",
    year: 2009
  },
  {
    id: "anniversary-sale",
    name: "Anniversary Sale",
    type: "category",
    tier: "campaign",
    status: "current",
    parent: "ebay-deals",
    desc: "September celebration of eBay founding (Sept 1995) with nostalgia marketing, retro collectibles spotlight, exclusive discounts, user milestone rewards.",
    market: "global",
    year: 2005
  },
  {
    id: "green-monday",
    name: "Green Monday",
    type: "category",
    tier: "campaign",
    status: "current",
    parent: "ebay-deals",
    desc: "Second Monday in December shopping event offering last-chance deals before Christmas shipping cutoffs. Free shipping promotions, extended returns.",
    market: "US",
    year: 2014
  },

  // ===== INTERNATIONAL & REGIONAL FEATURES (20 programs) =====

  {
    id: "ebay-uk",
    name: "eBay UK",
    type: "regional",
    tier: "platform",
    status: "current",
    parent: "regional",
    desc: "United Kingdom marketplace (ebay.co.uk) with GBP currency, UK-specific categories (British collectibles, football memorabilia), VAT handling, Royal Mail integration.",
    market: "UK",
    year: 1999
  },
  {
    id: "ebay-germany",
    name: "eBay Germany",
    type: "regional",
    tier: "platform",
    status: "current",
    parent: "regional",
    desc: "German marketplace (ebay.de) with EUR currency, localized categories, DHL/Hermes shipping, German consumer protection laws (14-day returns mandatory).",
    market: "DE",
    year: 1999
  },
  {
    id: "ebay-australia",
    name: "eBay Australia",
    type: "regional",
    tier: "platform",
    status: "current",
    parent: "regional",
    desc: "Australian marketplace (ebay.com.au) with AUD currency, Australia Post integration, GST collection, localized categories (AFL, cricket memorabilia).",
    market: "AU",
    year: 1999
  },
  {
    id: "ebay-canada",
    name: "eBay Canada",
    type: "regional",
    tier: "platform",
    status: "current",
    parent: "regional",
    desc: "Canadian marketplace (ebay.ca) with CAD currency, bilingual (English/French) interface, Canada Post shipping, cross-border tax handling.",
    market: "CA",
    year: 2000
  },
  {
    id: "ebay-france",
    name: "eBay France",
    type: "regional",
    tier: "platform",
    status: "current",
    parent: "regional",
    desc: "French marketplace (ebay.fr) with EUR currency, French language, Colissimo/Chronopost shipping, EU consumer protection compliance.",
    market: "FR",
    year: 2000
  },
  {
    id: "ebay-italy",
    name: "eBay Italy",
    type: "regional",
    tier: "platform",
    status: "current",
    parent: "regional",
    desc: "Italian marketplace (ebay.it) with EUR currency, Italian language, Poste Italiane integration, localized fashion/luxury categories.",
    market: "IT",
    year: 2001
  },
  {
    id: "ebay-spain",
    name: "eBay Spain",
    type: "regional",
    tier: "platform",
    status: "current",
    parent: "regional",
    desc: "Spanish marketplace (ebay.es) with EUR currency, Spanish language, Correos shipping, localized categories (La Liga memorabilia).",
    market: "ES",
    year: 2001
  },
  {
    id: "global-shipping-toggle",
    name: "Global Shipping Toggle",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Seller setting to enable/disable international shipping per listing. Auto-calculates customs, shows total landed cost to buyers, manages export compliance.",
    market: "global",
    year: 2013
  },
  {
    id: "cross-border-trade",
    name: "Cross Border Trade",
    type: "category",
    tier: "program",
    status: "current",
    parent: "shipping",
    desc: "Strategic initiative expanding international selling with simplified customs forms, import tax prepayment, translation tools, currency conversion.",
    market: "global",
    year: 2014
  },
  {
    id: "currency-conversion",
    name: "Currency Conversion",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Automatic price display in buyer's local currency with live exchange rates. Seller receives funds in listing currency, buyer pays in preferred currency.",
    market: "global",
    year: 2008
  },
  {
    id: "language-translation",
    name: "Language Translation",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Machine translation of listing titles, descriptions, item specifics into 20+ languages for cross-border discovery. Powered by eBay MT engine.",
    market: "global",
    year: 2016
  },
  {
    id: "prohibited-restricted-items-by-country",
    name: "Prohibited & Restricted Items by Country",
    type: "trust",
    tier: "legal",
    status: "current",
    parent: "trust",
    desc: "Country-specific restrictions varying by market (e.g., knives restricted UK, alcohol prohibited most markets, Nazi memorabilia banned Germany).",
    market: "global",
    year: 2003
  },
  {
    id: "eu-consumer-rights-directive",
    name: "EU Consumer Rights Directive",
    type: "trust",
    tier: "legal",
    status: "current",
    parent: "returns",
    desc: "European law mandating 14-day return window for distance sales, requiring sellers to accept returns regardless of stated policy. Enforced on EU marketplaces.",
    market: ["UK", "DE", "FR", "IT", "ES"],
    year: 2014
  },
  {
    id: "gdpr-compliance",
    name: "GDPR Compliance",
    type: "trust",
    tier: "legal",
    status: "current",
    parent: "trust",
    desc: "EU General Data Protection Regulation implementation allowing users to access, export, delete personal data. Includes cookie consent, data portability rights.",
    market: ["UK", "DE", "FR", "IT", "ES"],
    year: 2018
  },
  {
    id: "ccpa-compliance",
    name: "CCPA Compliance",
    type: "trust",
    tier: "legal",
    status: "current",
    parent: "trust",
    desc: "California Consumer Privacy Act compliance allowing CA residents to opt out of data sale, request deletion, access collected data. 'Do Not Sell My Info' link in footer.",
    market: "US",
    year: 2020
  },
  {
    id: "royal-mail-tracked-24",
    name: "Royal Mail Tracked 24",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "UK-exclusive shipping service with tracking and 24-hour delivery target. Discounted rates via eBay shipping labels, Top Rated eligible.",
    market: "UK",
    year: 2014
  },
  {
    id: "dhl-paket",
    name: "DHL Paket",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Germany's primary parcel service integrated with eBay for discounted label printing, tracking, and Packstation delivery to automated lockers.",
    market: "DE",
    year: 2010
  },
  {
    id: "australia-post-express",
    name: "Australia Post Express",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Premium Australian shipping with 1-2 day metro delivery, tracking, insurance. eBay label discounts up to 25% off retail rates.",
    market: "AU",
    year: 2012
  },
  {
    id: "canada-post-expedited",
    name: "Canada Post Expedited",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Canadian mid-tier shipping with 2-5 day delivery, tracking, insurance. Discounted rates via eBay for cross-country shipments.",
    market: "CA",
    year: 2011
  },
  {
    id: "hermes-paketshop",
    name: "Hermes PaketShop",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "German parcel network with 15,000+ retail drop-off locations. Popular for seller convenience and buyer pickup flexibility.",
    market: "DE",
    year: 2013
  }
];
