// eBay Naming Graph - Enriched Wave 4 Batch G
// Focus: eBay Verticals (Fashion, Electronics, Home & Garden), Category-Specific Features, Specialized Tools
// Generated: 2026-04-17
// Count: 50 programs

import { GraphNode } from './enriched-consolidated-DEDUPLICATED'

export const ENRICHED_WAVE4_G: GraphNode[] = [
  {
    id: "shop-by-diagram",
    name: "Shop by Diagram",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-motors",
    desc: "Visual parts finder for eBay Motors using exploded diagrams - select parts directly from vehicle schematics for exact fitment matching.",
    market: "global",
    year: 2015
  },
  {
    id: "parts-compatibility",
    name: "Parts Compatibility",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-motors",
    desc: "Parts fitment database for Motors/Home & Garden verticals - sellers declare compatibility, buyers filter by make/model/year.",
    market: "global",
    year: 2008
  },
  {
    id: "fitment-plus",
    name: "Fitment Plus",
    type: "category",
    tier: "program",
    status: "current",
    parent: "ebay-motors",
    desc: "Premium fitment data service using eBay's EPID catalog - automated compatibility matching for automotive parts sellers.",
    market: "US",
    year: 2018
  },
  {
    id: "fitment-plus-auto",
    name: "Fitment Plus Auto (FPA)",
    type: "category",
    tier: "program",
    status: "current",
    parent: "ebay-motors",
    desc: "Automated fitment table builder using manufacturer data - FPA generates compatibility tables at scale for high-volume Motors sellers.",
    market: "US",
    year: 2019
  },
  {
    id: "circular-fashion-fund",
    name: "Circular Fashion Fund",
    type: "impact",
    tier: "program",
    status: "current",
    parent: "sustainability",
    desc: "Investment fund supporting pre-loved fashion startups and circular economy initiatives - grants/partnerships to reduce fashion waste.",
    market: "global",
    year: 2021
  },
  {
    id: "pre-loved-fashion-week",
    name: "Pre-Loved Fashion Week",
    type: "impact",
    tier: "campaign",
    status: "current",
    parent: "circular-fashion-fund",
    desc: "Annual global campaign celebrating secondhand fashion - curated collections, influencer partnerships, sustainability messaging.",
    market: "global",
    year: 2022
  },
  {
    id: "preloved-partner-program",
    name: "Preloved Partner Program",
    type: "category",
    tier: "program",
    status: "current",
    parent: "fashion",
    desc: "Partnerships with luxury consignment/authentication brands - integrated storefronts for The RealReal, Vestiaire Collective, etc.",
    market: ["US", "UK"],
    year: 2020
  },
  {
    id: "certified-recycler-program",
    name: "Certified Recycler Program",
    type: "impact",
    tier: "program",
    status: "current",
    parent: "sustainability",
    desc: "Seller certification for electronics recyclers - verified e-waste compliance, refurbishing standards, environmental certifications.",
    market: "global",
    year: 2019
  },
  {
    id: "certified-recycled",
    name: "Certified Recycled",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "certified-recycler-program",
    desc: "Condition badge for items made from recycled materials - sustainability filter, verified by eBay's compliance team.",
    market: "global",
    year: 2020
  },
  {
    id: "certified-open-box",
    name: "Certified Open Box",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-refurbished",
    desc: "Condition state for new items with opened packaging - factory seal broken but never used, full warranty, 30-day returns.",
    market: "global",
    year: 2020
  },
  {
    id: "certified-by-brand",
    name: "Certified by Brand",
    type: "trust",
    tier: "program",
    status: "current",
    parent: "refurbished",
    desc: "Brand-direct refurbishment program - manufacturer-certified refurbs sold through brand's official eBay store.",
    market: "US",
    year: 2021
  },
  {
    id: "ebay-business-supply",
    name: "eBay Business Supply",
    type: "category",
    tier: "vertical",
    status: "current",
    parent: "b2b",
    desc: "B2B vertical for office supplies, industrial equipment, business services - volume pricing, business buyer accounts, tax exemption.",
    market: "global",
    year: 2016
  },
  {
    id: "collectibles-price-guide",
    name: "Collectibles Price Guide",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "collectibles",
    desc: "Pricing data tool for collectibles categories (trading cards, comics, coins) - market trends, recent sales, valuation estimates.",
    market: "US",
    year: 2020
  },
  {
    id: "image-search",
    name: "Image Search",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Visual search tool - upload photo or screenshot to find similar items, reverse image search powered by computer vision.",
    market: ["US", "UK", "CA", "AU"],
    year: 2017
  },
  {
    id: "find-it-on-ebay",
    name: "Find It On eBay",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Browser extension for image-based search - right-click any image on the web to find it on eBay.",
    market: ["US", "UK", "CA", "AU"],
    year: 2018
  },
  {
    id: "category-browse",
    name: "Category Browse",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "discovery",
    desc: "Hierarchical category navigation - L1/L2/L3 taxonomy, 20,000+ categories, aspect-based refinements.",
    market: "global",
    year: 2000
  },
  {
    id: "collections",
    name: "Collections",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "discovery",
    desc: "Personalized item grouping tool - save items to custom collections (e.g., 'Kitchen Remodel', 'Gift Ideas'), shareable lists.",
    market: "global",
    year: 2019
  },
  {
    id: "following",
    name: "Following",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "discovery",
    desc: "Follow sellers/searches/categories - personalized feed of new listings from followed entities, notification triggers.",
    market: "global",
    year: 2018
  },
  {
    id: "ai-banner",
    name: "AI Store Banner Generator",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-stores",
    desc: "Generative AI tool for creating custom eBay Store banners - text-to-image, brand style transfer, automated design variants.",
    market: "US",
    year: 2024
  },
  {
    id: "store-header",
    name: "Store Header",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-stores",
    desc: "Customizable storefront header - logo, banner, navigation, branding, included in all eBay Stores subscriptions.",
    market: "global",
    year: 2005
  },
  {
    id: "store-categories",
    name: "Store Categories",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-stores",
    desc: "Custom category taxonomy for Store listings - sellers create up to 300 custom categories, independent of eBay's L1/L2/L3.",
    market: "global",
    year: 2005
  },
  {
    id: "store-promotions-box",
    name: "Store Promotions Box",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-stores",
    desc: "Promotional widget on Store pages - feature sales, coupons, new arrivals, customizable markdown messaging.",
    market: "global",
    year: 2010
  },
  {
    id: "store-tier-starter",
    name: "Store Tier - Starter",
    type: "category",
    tier: "variant",
    status: "current",
    parent: "ebay-stores",
    desc: "Entry-level eBay Stores subscription - $4.95/mo (US), basic storefront, 100 free listings, 5% FVF discount.",
    market: ["US", "AU"],
    year: 2020
  },
  {
    id: "store-tier-platin",
    name: "Store Tier - Platin",
    type: "category",
    tier: "variant",
    status: "current",
    parent: "ebay-stores",
    desc: "Top-tier Germany-only eBay Stores subscription - €299/mo, 100,000 free listings, 12% FVF discount, priority support.",
    market: "DE",
    year: 2015
  },
  {
    id: "store-tier-premium-plus",
    name: "Store Tier - Premium Plus",
    type: "category",
    tier: "variant",
    status: "current",
    parent: "ebay-stores",
    desc: "Italy-only eBay Stores subscription tier - €149/mo, 25,000 free listings, 9% FVF discount.",
    market: "IT",
    year: 2018
  },
  {
    id: "pro-seller-program",
    name: "Pro Seller Program",
    type: "category",
    tier: "program",
    status: "current",
    parent: "seller-benefits",
    desc: "High-volume seller program in select markets - dedicated account manager, fee discounts, beta access, quarterly business reviews.",
    market: ["US", "UK", "DE"],
    year: 2019
  },
  {
    id: "pro-trader-program",
    name: "Pro-Trader Program",
    type: "category",
    tier: "program",
    status: "current",
    parent: "seller-benefits",
    desc: "UK/DE program for professional resellers - seller registration, VAT compliance tools, bulk listing features.",
    market: ["UK", "DE"],
    year: 2016
  },
  {
    id: "ebay-ambassador",
    name: "eBay Ambassador",
    type: "category",
    tier: "program",
    status: "current",
    parent: "community",
    desc: "Volunteer community moderator program - experienced sellers answer questions, moderate forums, early feature access.",
    market: "global",
    year: 2010
  },
  {
    id: "ebay-concierge",
    name: "eBay Concierge",
    type: "category",
    tier: "program",
    status: "current",
    parent: "luxury",
    desc: "White-glove service for luxury sellers - photography, authentication, listing creation, shipping coordination for high-value items.",
    market: "US",
    year: 2018
  },
  {
    id: "ebay-valet-original",
    name: "eBay Valet (Original)",
    type: "category",
    tier: "program",
    status: "legacy",
    parent: "services",
    desc: "Consignment service (2014-2017) - ship items to eBay, they list/photograph/ship for commission. Sunset 2017.",
    market: "US",
    year: 2014,
    renamedTo: "ebay-concierge"
  },
  {
    id: "ebay-rachat",
    name: "eBay Rachat",
    type: "category",
    tier: "program",
    status: "current",
    parent: "recommerce",
    desc: "France buyback program - instant quotes for electronics/phones, eBay purchases device and resells, circular economy initiative.",
    market: "FR",
    year: 2022
  },
  {
    id: "merchant-integration-platform",
    name: "Merchant Integration Platform (MIP)",
    type: "developer",
    tier: "platform",
    status: "current",
    parent: "developer",
    desc: "Enterprise integration hub - streamlined API access, bulk operations, order management, inventory sync for large retailers.",
    market: "global",
    year: 2012
  },
  {
    id: "ebay-export",
    name: "eBay Export",
    type: "category",
    tier: "program",
    status: "current",
    parent: "international",
    desc: "Cross-border trade facilitation program - customs documentation, export compliance, international shipping partnerships.",
    market: "global",
    year: 2015
  },
  {
    id: "export-academy",
    name: "Export Academy",
    type: "category",
    tier: "program",
    status: "current",
    parent: "ebay-export",
    desc: "Education program for cross-border sellers - webinars, guides, market research, localization best practices.",
    market: "global",
    year: 2016
  },
  {
    id: "cbt-seller-dashboard",
    name: "Cross Border Trade (CBT) Seller Dashboard",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-export",
    desc: "Analytics tool for international sellers - performance by destination country, currency conversion, tariff estimates.",
    market: "global",
    year: 2017
  },
  {
    id: "international-site-visibility",
    name: "International Site Visibility",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "international",
    desc: "Cross-border listing syndication - US listings auto-appear on UK/AU/CA sites with currency/shipping conversion.",
    market: "global",
    year: 2010
  },
  {
    id: "managed-display",
    name: "Managed Display",
    type: "advertising",
    tier: "program",
    status: "current",
    parent: "ebay-advertising",
    desc: "Display advertising placement service - eBay's ad team manages banner/native placements on external sites, CPM/CPA pricing.",
    market: "US",
    year: 2020
  },
  {
    id: "brand-identity",
    name: "Brand Identity",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "brand-tools",
    desc: "Brand verification program for manufacturers - custom storefront badges, enhanced search placement, counterfeit protection tools.",
    market: "global",
    year: 2019
  },
  {
    id: "brand-name",
    name: "Brand Name",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing-fields",
    desc: "Required item specific for branded products - structured brand taxonomy, autocomplete, powers brand refinement filters.",
    market: "global",
    year: 2005
  },
  {
    id: "product-identifiers",
    name: "Product Identifiers",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing-fields",
    desc: "UPC/EAN/ISBN/MPN fields for catalog matching - required in 70%+ categories, enables eBay Product ID (EPID) assignment.",
    market: "global",
    year: 2012
  },
  {
    id: "item-comparison",
    name: "Item Comparison",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "discovery",
    desc: "Side-by-side comparison tool - buyers select multiple items, view specs/price/condition in comparison table.",
    market: "global",
    year: 2016
  },
  {
    id: "similar-items",
    name: "Similar Items",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "discovery",
    desc: "Recommendation rail on VIP - shows visually/semantically similar items, powered by computer vision + collaborative filtering.",
    market: "global",
    year: 2015
  },
  {
    id: "item-reviews",
    name: "Item Reviews",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "Product-level review system - buyers rate item (not seller), aggregated star ratings shown on VIP, launched 2019.",
    market: "global",
    year: 2019
  },
  {
    id: "product-reviews",
    name: "Product Reviews",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "Catalog-level reviews tied to eBay Product ID (EPID) - aggregated across all sellers offering the same product.",
    market: "global",
    year: 2020
  },
  {
    id: "verified-purchase",
    name: "Verified Purchase",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "feedback",
    desc: "Badge on reviews indicating buyer purchased item on eBay - prevents fake reviews, increases trust, shown on item reviews.",
    market: "global",
    year: 2020
  },
  {
    id: "ebay-customer-service",
    name: "eBay Customer Service",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "support",
    desc: "Centralized buyer/seller support hub - chat, phone, email routing, case management, escalation workflows.",
    market: "global",
    year: 2000
  },
  {
    id: "seller-help",
    name: "Seller Help",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "support",
    desc: "Seller-specific help portal - knowledge base, video tutorials, policy documentation, community forums.",
    market: "global",
    year: 2005
  },
  {
    id: "seller-clinics",
    name: "Seller Clinics",
    type: "category",
    tier: "program",
    status: "current",
    parent: "education",
    desc: "In-person seller education events - quarterly regional workshops, eBay staff present on policies/tools/strategies.",
    market: ["US", "UK", "DE"],
    year: 2010
  },
  {
    id: "seller-news",
    name: "Seller News",
    type: "category",
    tier: "publication",
    status: "current",
    parent: "communications",
    desc: "Monthly seller newsletter - policy updates, feature launches, seller stories, delivered via email + Seller Hub.",
    market: "global",
    year: 2008
  },
  {
    id: "consommation-raisonnee",
    name: "Consommation Raisonnée",
    type: "impact",
    tier: "campaign",
    status: "current",
    parent: "sustainability",
    desc: "France sustainability campaign - 'mindful consumption' messaging, pre-loved fashion, refurbished electronics promotion.",
    market: "FR",
    year: 2021
  }
]
