// eBay Naming Graph - Wave 3 Batch U (Final Sweep)
// Enriched unenriched programs from translations.ts NOT in enriched-consolidated-DEDUPLICATED.ts
// Generated: 2026-04-18
// Total: 140 programs with full GraphNode metadata

export interface GraphNode {
  id: string
  name: string
  type: "masterbrand" | "category" | "advertising" | "trust" | "impact" | "developer" | "regional"
  tier: "master" | "umbrella" | "t1" | "t2" | "t3" | "product" | "program" | "feature" | "legal" | "organization" | "publication" | "event" | "campaign" | "vertical" | "platform" | "variant"
  status: "current" | "legacy" | "renamed"
  parent?: string
  desc: string
  market?: "US" | "UK" | "DE" | "FR" | "IT" | "AU" | "CA" | "global" | string[]
  renamedFrom?: string
  renamedTo?: string
  year?: number
}

export const ENRICHED_WAVE3_U: GraphNode[] = [
  {
    id: "promoted-listings-general",
    name: "Promoted Listings General",
    type: "advertising",
    tier: "variant",
    status: "current",
    parent: "promoted-listings-standard",
    desc: "Lower-cost Promoted Listings campaign with broader placement across eBay search results and category pages.",
    market: "global",
    year: 2024
  },
  {
    id: "promoted-listings-priority",
    name: "Promoted Listings Priority",
    type: "advertising",
    tier: "variant",
    status: "current",
    parent: "promoted-listings-advanced",
    desc: "Premium Promoted Listings campaign offering priority placement in top search positions and higher visibility.",
    market: "global",
    year: 2024
  },
  {
    id: "ebay-refurbished-warranty",
    name: "eBay Refurbished Warranty",
    type: "trust",
    tier: "program",
    status: "current",
    parent: "ebay-refurbished",
    desc: "2-year warranty with free shipping and 30-day returns on eBay Refurbished products, backed by Allstate.",
    market: "US",
    year: 2019
  },
  {
    id: "logistica-ebay-by-orange-connex",
    name: "Logistica eBay by Orange Connex",
    type: "category",
    tier: "program",
    status: "current",
    parent: "shipping",
    desc: "Italy-specific managed logistics service powered by Orange Connex for streamlined fulfillment and shipping.",
    market: "IT",
    year: 2021
  },
  {
    id: "ebay-wow",
    name: "eBay WOW!",
    type: "category",
    tier: "campaign",
    status: "current",
    parent: "deals",
    desc: "German daily deals program featuring limited-time offers on select products (WOW! des Tages).",
    market: "DE",
    year: 2014
  },
  {
    id: "consommation-raisonnee",
    name: "Consommation Raisonnée",
    type: "impact",
    tier: "program",
    status: "current",
    parent: "sustainability",
    desc: "French responsible consumption program promoting sustainable shopping and second-hand purchases.",
    market: "FR",
    year: 2021
  },
  {
    id: "ebay-ai-message-assistance",
    name: "eBay.ai Message Assistance",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "AI-powered message assistant that suggests contextual responses to buyer inquiries, streamlining seller communication.",
    market: "global",
    year: 2024
  },
  {
    id: "tax-documents",
    name: "Tax Documents",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Section in Seller Hub providing access to 1099-K forms, sales tax summaries, and other tax-related documents.",
    market: ["US", "CA"],
    year: 2013
  },
  {
    id: "sales-tax-collection",
    name: "Sales Tax Collection",
    type: "category",
    tier: "program",
    status: "current",
    parent: "payments",
    desc: "Automated sales tax calculation and collection service for US sellers, handling state and local tax compliance.",
    market: "US",
    year: 2019
  },
  {
    id: "multi-variation-listings",
    name: "Multi-Variation Listings",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Listing format allowing sellers to offer multiple product variants (size, color, style) within a single listing.",
    market: "global",
    year: 2011
  },
  {
    id: "watch-count",
    name: "Watch Count",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Metric showing how many buyers have added a listing to their Watchlist, indicating buyer interest level.",
    market: "global",
    year: 2005
  },
  {
    id: "impressions",
    name: "Impressions",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Metric tracking how many times a listing appears in search results and category pages, regardless of clicks.",
    market: "global",
    year: 2014
  },
  {
    id: "click-through-rate",
    name: "Click-Through Rate",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Percentage of impressions that result in clicks, measuring listing thumbnail and title effectiveness.",
    market: "global",
    year: 2014
  },
  {
    id: "sales-conversion-rate",
    name: "Sales Conversion Rate",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Percentage of listing views that result in sales, measuring overall listing effectiveness and buyer intent.",
    market: "global",
    year: 2014
  },
  {
    id: "seller-news",
    name: "Seller News",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Announcements and updates section in Seller Hub providing policy changes, new features, and important seller communications.",
    market: "global",
    year: 2016
  },
  {
    id: "buyer-requirements",
    name: "Buyer Requirements",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-tools",
    desc: "Seller tool to set automatic restrictions on who can bid or buy, filtering buyers by feedback score, location, or payment method.",
    market: "global",
    year: 2008
  },
  {
    id: "block-buyers",
    name: "Block Buyers",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-tools",
    desc: "Tool allowing sellers to manually block specific eBay members from bidding on or purchasing their items.",
    market: "global",
    year: 2003
  },
  {
    id: "purchase-limits",
    name: "Purchase Limits",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer-requirements",
    desc: "Restriction setting limiting maximum quantity a single buyer can purchase within a time period.",
    market: "global",
    year: 2010
  },
  {
    id: "listing-quality-report",
    name: "Listing Quality Report",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Analytics report identifying listing improvement opportunities based on missing item specifics, photos, or descriptions.",
    market: "global",
    year: 2018
  },
  {
    id: "price-suggestions",
    name: "Price Suggestions",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "pricing-tools",
    desc: "AI-powered pricing recommendations based on historical sales data, market trends, and competitive analysis.",
    market: "global",
    year: 2020
  },
  {
    id: "competitive-pricing",
    name: "Competitive Pricing",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "pricing-tools",
    desc: "Real-time pricing intelligence showing how seller's prices compare to similar active and sold listings.",
    market: "global",
    year: 2019
  },
  {
    id: "auto-pricing",
    name: "Auto Pricing",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "pricing-tools",
    desc: "Automated pricing rules that adjust listing prices based on competitor pricing, market conditions, or sales velocity.",
    market: ["US", "UK", "DE"],
    year: 2021
  },
  {
    id: "item-location",
    name: "Item Location",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Required field specifying the physical location of the item being sold, used for shipping calculation and buyer filtering.",
    market: "global",
    year: 1999
  },
  {
    id: "ship-from-address",
    name: "Ship From Address",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Seller's warehouse or dispatch location used for shipping label generation and delivery time estimates.",
    market: "global",
    year: 2013
  },
  {
    id: "calculated-shipping",
    name: "Calculated Shipping",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Dynamic shipping cost calculation based on buyer's zip code, package dimensions, and carrier rates.",
    market: "global",
    year: 2004
  },
  {
    id: "flat-rate-shipping",
    name: "Flat Rate Shipping",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Fixed shipping price set by seller, regardless of buyer location or package size.",
    market: "global",
    year: 2001
  },
  {
    id: "free-shipping",
    name: "Free Shipping",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Shipping option where seller absorbs shipping costs, often boosting search placement and conversion rates.",
    market: "global",
    year: 2009
  },
  {
    id: "local-delivery",
    name: "Local Delivery",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Seller-provided delivery service for buyers within a specified local area, alternative to shipping or pickup.",
    market: "global",
    year: 2020
  },
  {
    id: "same-day-handling",
    name: "Same-Day Handling",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Seller commitment to ship item on the same day as purchase, improving buyer confidence and search placement.",
    market: "global",
    year: 2015
  },
  {
    id: "1-day-handling",
    name: "1-Day Handling",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Seller commitment to ship within 1 business day of payment receipt, standard for high-volume sellers.",
    market: "global",
    year: 2010
  },
  {
    id: "handling-time",
    name: "Handling Time",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Number of business days between payment receipt and shipment, used to calculate estimated delivery date.",
    market: "global",
    year: 2007
  },
  {
    id: "estimated-delivery",
    name: "Estimated Delivery",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Calculated date range when buyer can expect to receive item, based on handling time and carrier transit time.",
    market: "global",
    year: 2013
  },
  {
    id: "free-returns",
    name: "Free Returns",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "returns",
    desc: "Seller-provided return shipping at no cost to buyer, earning search visibility boost and buyer trust badge.",
    market: "global",
    year: 2018
  },
  {
    id: "30-day-returns",
    name: "30-Day Returns",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "returns",
    desc: "Standard return window offering buyers 30 days from delivery to initiate a return.",
    market: "global",
    year: 2014
  },
  {
    id: "60-day-returns",
    name: "60-Day Returns",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "returns",
    desc: "Extended return window offering buyers 60 days from delivery, providing competitive advantage and search boost.",
    market: "global",
    year: 2018
  },
  {
    id: "buyer-pays-return-shipping",
    name: "Buyer Pays Return Shipping",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "returns",
    desc: "Return policy option where buyer covers cost of return shipping unless item not as described.",
    market: "global",
    year: 2014
  },
  {
    id: "seller-pays-return-shipping",
    name: "Seller Pays Return Shipping",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "returns",
    desc: "Return policy option where seller provides prepaid return label for all returns, improving buyer confidence.",
    market: "global",
    year: 2014
  },
  {
    id: "no-returns-accepted",
    name: "No Returns Accepted",
    type: "category",
    tier: "feature",
    status: "legacy",
    parent: "returns",
    desc: "Discontinued return policy option that prevented buyers from returning items. eBay now mandates 30-day returns in most categories.",
    market: "global",
    year: 2005,
    renamedTo: "30-day-returns"
  },
  {
    id: "restocking-fee",
    name: "Restocking Fee",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "returns",
    desc: "Fee charged to buyer for returning item in opened or non-original condition, up to 20% of item price.",
    market: "global",
    year: 2014
  },
  {
    id: "auction-format",
    name: "Auction Format",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Classic eBay listing format where buyers bid against each other, with item selling to highest bidder at listing end.",
    market: "global",
    year: 1995
  },
  {
    id: "fixed-price-format",
    name: "Fixed Price Format",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Buy It Now listing format with set price, allowing immediate purchase without bidding.",
    market: "global",
    year: 2000
  },
  {
    id: "starting-bid",
    name: "Starting Bid",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "auction-format",
    desc: "Minimum opening bid amount for auction listings, determining the lowest acceptable starting price.",
    market: "global",
    year: 1995
  },
  {
    id: "active-listings",
    name: "Active Listings",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Seller Hub view showing all currently live listings available for buyers to purchase or bid on.",
    market: "global",
    year: 2016
  },
  {
    id: "draft-listings",
    name: "Draft Listings",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Saved incomplete listings that can be finished and published later, stored for up to 90 days.",
    market: "global",
    year: 2016
  },
  {
    id: "ended-listings",
    name: "Ended Listings",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Seller Hub view showing all completed auction listings and expired fixed-price listings.",
    market: "global",
    year: 2016
  },
  {
    id: "sold-listings",
    name: "Sold Listings",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Seller Hub view showing all successfully sold items requiring shipment or order processing.",
    market: "global",
    year: 2016
  },
  {
    id: "unsold-listings",
    name: "Unsold Listings",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Seller Hub view showing ended listings that did not sell, available for relisting.",
    market: "global",
    year: 2016
  },
  {
    id: "inactive-listings",
    name: "Inactive Listings",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Out-of-stock or paused listings that are not currently visible to buyers but can be reactivated.",
    market: "global",
    year: 2016
  },
  {
    id: "completed-listings",
    name: "Completed Listings",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "All finished transactions including sold items and ended unsold listings, used for historical analysis.",
    market: "global",
    year: 2016
  },
  {
    id: "quantity-available",
    name: "Quantity Available",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "inventory",
    desc: "Number of units currently in stock and available for purchase in a fixed-price listing.",
    market: "global",
    year: 2003
  },
  {
    id: "inventory-management",
    name: "Inventory Management",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Tools for tracking, updating, and syncing inventory levels across eBay listings and external channels.",
    market: "global",
    year: 2016
  },
  {
    id: "stock-quantity",
    name: "Stock Quantity",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "inventory",
    desc: "Total inventory count for a SKU across all listings and sales channels.",
    market: "global",
    year: 2016
  },
  {
    id: "advanced-search",
    name: "Advanced Search",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Enhanced search interface with filters for price range, condition, location, listing format, and more.",
    market: "global",
    year: 2003
  },
  {
    id: "category-browse",
    name: "Category Browse",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "discovery",
    desc: "Hierarchical navigation system allowing buyers to explore items by product category and subcategory.",
    market: "global",
    year: 1995
  },
  {
    id: "search-filters",
    name: "Search Filters",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Refinement options in search results for condition, price, shipping, brand, and other attributes.",
    market: "global",
    year: 2009
  },
  {
    id: "condition-description",
    name: "Condition Description",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Detailed text description of item condition, supplementing the standard condition dropdown selection.",
    market: "global",
    year: 2011
  },
  {
    id: "item-condition",
    name: "Item Condition",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing",
    desc: "Required field specifying item state: New, Used, Refurbished, For Parts, or category-specific condition values.",
    market: "global",
    year: 2007
  },
  {
    id: "cassini",
    name: "Cassini",
    type: "category",
    tier: "platform",
    status: "current",
    parent: "search",
    desc: "eBay's proprietary search engine algorithm determining listing relevance and ranking in search results.",
    market: "global",
    year: 2013
  },
  {
    id: "csv-upload",
    name: "CSV Upload",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "bulk-tools",
    desc: "File-based bulk listing tool allowing sellers to upload spreadsheets with multiple listings at once.",
    market: "global",
    year: 2010
  },
  {
    id: "bulk-upload",
    name: "Bulk Upload",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "bulk-tools",
    desc: "Suite of tools for creating, editing, or ending multiple listings simultaneously via file upload or API.",
    market: "global",
    year: 2008
  },
  {
    id: "save-for-later",
    name: "Save for Later",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "buyer",
    desc: "Feature allowing buyers to move items from cart to a saved list for future purchase consideration.",
    market: "global",
    year: 2018
  },
  {
    id: "push-notifications",
    name: "Push Notifications",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "notifications",
    desc: "Mobile app alerts for outbid notices, shipping updates, offers, and messages delivered to device lock screen.",
    market: "global",
    year: 2013
  },
  {
    id: "email-notifications",
    name: "Email Notifications",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "notifications",
    desc: "Email alerts for account activity, purchases, sales, messages, and policy updates sent to registered email address.",
    market: "global",
    year: 1995
  },
  {
    id: "sms-alerts",
    name: "SMS Alerts",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "notifications",
    desc: "Text message notifications for critical events like outbid alerts, winning confirmations, and shipment updates.",
    market: ["US", "UK"],
    year: 2017
  },
  {
    id: "outbid-alert",
    name: "Outbid Alert",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "notifications",
    desc: "Real-time notification when another bidder exceeds your bid on an auction listing.",
    market: "global",
    year: 2001
  },
  {
    id: "automatic-bidding",
    name: "Automatic Bidding",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "auction-format",
    desc: "Proxy bidding system where eBay automatically increases your bid up to your maximum to maintain highest bidder status.",
    market: "global",
    year: 1995
  },
  {
    id: "proxy-bidding",
    name: "Proxy Bidding",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "auction-format",
    desc: "eBay's automated bidding mechanism that bids on your behalf up to your specified maximum amount.",
    market: "global",
    year: 1995
  },
  {
    id: "bid-increment",
    name: "Bid Increment",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "auction-format",
    desc: "Minimum amount by which next bid must exceed current high bid, scales based on current price level.",
    market: "global",
    year: 1995
  },
  {
    id: "counteroffer",
    name: "Counteroffer",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "best-offer",
    desc: "Seller response to buyer's Best Offer proposing a different price for negotiation.",
    market: "global",
    year: 2005
  },
  {
    id: "accept-offer",
    name: "Accept Offer",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "best-offer",
    desc: "Seller action to approve buyer's Best Offer, creating binding sale at offered price.",
    market: "global",
    year: 2005
  },
  {
    id: "decline-offer",
    name: "Decline Offer",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "best-offer",
    desc: "Seller action to reject buyer's Best Offer without negotiation.",
    market: "global",
    year: 2005
  },
  {
    id: "second-chance-offer",
    name: "Second Chance Offer",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "auction-format",
    desc: "Offer sent to underbidders after auction ends if winning bidder doesn't pay or seller has duplicate items.",
    market: "global",
    year: 2002
  },
  {
    id: "purchase-history",
    name: "Purchase History",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "my-ebay",
    desc: "Complete record of all items purchased on eBay, accessible in My eBay for order tracking and repurchasing.",
    market: "global",
    year: 2003
  },
  {
    id: "buy-again",
    name: "Buy Again",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "my-ebay",
    desc: "Quick repurchase feature allowing buyers to rebuy previously purchased items from purchase history.",
    market: "global",
    year: 2019
  },
  {
    id: "collections",
    name: "Collections",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "my-ebay",
    desc: "Buyer-created curated lists for organizing saved items by theme, project, or category.",
    market: "global",
    year: 2020
  },
  {
    id: "print-shipping-label",
    name: "Print Shipping Label",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Feature allowing sellers to generate prepaid shipping labels with discounted carrier rates through eBay.",
    market: "global",
    year: 2007
  },
  {
    id: "thermal-printer",
    name: "Thermal Printer",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Label printer support for generating 4x6 shipping labels without requiring standard paper or ink.",
    market: "global",
    year: 2010
  },
  {
    id: "upload-tracking",
    name: "Upload Tracking",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Tool for manually adding tracking numbers to orders when using non-eBay shipping labels.",
    market: "global",
    year: 2013
  },
  {
    id: "tracking-number",
    name: "Tracking Number",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Carrier-provided identifier for package location tracking, required for seller protection on high-value items.",
    market: "global",
    year: 2005
  },
  {
    id: "package-tracking",
    name: "Package Tracking",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Real-time shipment status updates shown in buyer's purchase history and seller's sold items.",
    market: "global",
    year: 2013
  },
  {
    id: "mark-as-shipped",
    name: "Mark as Shipped",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "order-management",
    desc: "Seller action confirming item has been sent, triggering buyer notification and payment release timeline.",
    market: "global",
    year: 2010
  },
  {
    id: "shipment-confirmation",
    name: "Shipment Confirmation",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "notifications",
    desc: "Email and app notification sent to buyer when seller marks item as shipped with tracking information.",
    market: "global",
    year: 2010
  },
  {
    id: "cancel-order",
    name: "Cancel Order",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "order-management",
    desc: "Process for seller or buyer to void transaction before shipment, requires mutual agreement or valid reason.",
    market: "global",
    year: 2013
  },
  {
    id: "cancellation-request",
    name: "Cancellation Request",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "order-management",
    desc: "Buyer-initiated request to cancel order after purchase but before shipment, requires seller approval.",
    market: "global",
    year: 2016
  },
  {
    id: "full-refund",
    name: "Full Refund",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "returns",
    desc: "Complete purchase price refund including original shipping, issued for returns or resolved cases.",
    market: "global",
    year: 2011
  },
  {
    id: "partial-refund",
    name: "Partial Refund",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "returns",
    desc: "Refund of portion of purchase price, used for damaged items buyer keeps or agreed settlements.",
    market: "global",
    year: 2011
  },
  {
    id: "send-refund",
    name: "Send Refund",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "order-management",
    desc: "Seller action to issue money back to buyer through eBay's payment system or original payment method.",
    market: "global",
    year: 2011
  },
  {
    id: "combined-shipping",
    name: "Combined Shipping",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Discounted shipping when buyer purchases multiple items from same seller, consolidated into single package.",
    market: "global",
    year: 2006
  },
  {
    id: "request-total",
    name: "Request Total",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "checkout",
    desc: "Buyer action asking seller to provide combined shipping quote before payment for multiple purchases.",
    market: "global",
    year: 2006
  },
  {
    id: "shipping-discount",
    name: "Shipping Discount",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Reduced shipping rate for additional items purchased from same seller, encouraging multi-item purchases.",
    market: "global",
    year: 2006
  },
  {
    id: "send-invoice",
    name: "Send Invoice",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "order-management",
    desc: "Seller tool to send revised total to buyer, adjusting for combined shipping, discounts, or tax corrections.",
    market: "global",
    year: 2003
  },
  {
    id: "priority-campaign",
    name: "Priority Campaign",
    type: "advertising",
    tier: "variant",
    status: "current",
    parent: "promoted-listings-advanced",
    desc: "High-visibility ad campaign type offering premium placement in top search positions.",
    market: "global",
    year: 2024
  },
  {
    id: "general-campaign",
    name: "General Campaign",
    type: "advertising",
    tier: "variant",
    status: "current",
    parent: "promoted-listings-standard",
    desc: "Standard ad campaign type with broad placement across search results and category pages.",
    market: "global",
    year: 2024
  },
  {
    id: "ad-attribution",
    name: "Ad Attribution",
    type: "advertising",
    tier: "feature",
    status: "current",
    parent: "promoted-listings",
    desc: "Analytics showing which sales resulted from Promoted Listings ads versus organic search placement.",
    market: "global",
    year: 2019
  },
  {
    id: "cost-per-sale",
    name: "Cost Per Sale",
    type: "advertising",
    tier: "feature",
    status: "current",
    parent: "promoted-listings",
    desc: "Advertising metric showing total ad fees divided by number of attributed sales.",
    market: "global",
    year: 2019
  },
  {
    id: "cost-per-click",
    name: "Cost Per Click",
    type: "advertising",
    tier: "feature",
    status: "current",
    parent: "promoted-listings-advanced",
    desc: "Ad rate metric in Promoted Listings Advanced where sellers pay for each click on promoted listing.",
    market: "global",
    year: 2020
  },
  {
    id: "ad-fee",
    name: "Ad Fee",
    type: "advertising",
    tier: "feature",
    status: "current",
    parent: "promoted-listings",
    desc: "Commission charged when promoted listing generates sale, calculated as percentage of final sale price.",
    market: "global",
    year: 2015
  },
  {
    id: "premium-placement",
    name: "Premium Placement",
    type: "advertising",
    tier: "feature",
    status: "current",
    parent: "promoted-listings-advanced",
    desc: "Top search position slots available through Promoted Listings Advanced bidding.",
    market: "global",
    year: 2020
  },
  {
    id: "page-views",
    name: "Page Views",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Total number of times listing page was viewed, including multiple views by same user.",
    market: "global",
    year: 2005
  },
  {
    id: "visits",
    name: "Visits",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Number of distinct browsing sessions viewing a listing, counting multiple page views in one session as one visit.",
    market: "global",
    year: 2014
  },
  {
    id: "unique-visitors",
    name: "Unique Visitors",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Count of individual users who viewed listing, deduplicated by user account.",
    market: "global",
    year: 2014
  },
  {
    id: "session-duration",
    name: "Session Duration",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Average time buyers spend viewing listing page and related content during browsing session.",
    market: "global",
    year: 2018
  },
  {
    id: "bounce-rate",
    name: "Bounce Rate",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Percentage of visitors who leave listing immediately without interaction, indicating relevance or quality issues.",
    market: "global",
    year: 2018
  },
  {
    id: "sell-through-rate",
    name: "Sell-Through Rate",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Percentage of listed inventory that sells within specific timeframe, measuring demand and pricing effectiveness.",
    market: "global",
    year: 2016
  },
  {
    id: "conversion-rate",
    name: "Conversion Rate",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "analytics",
    desc: "Percentage of listing views resulting in sales, key metric for listing optimization and pricing strategy.",
    market: "global",
    year: 2014
  },
  {
    id: "transaction-defect-rate",
    name: "Transaction Defect Rate",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "seller-performance-standards",
    desc: "Percentage of transactions with defects (INR, SNAD, cancellations), must stay below 2% to maintain Above Standard.",
    market: "global",
    year: 2014
  },
  {
    id: "late-shipment-rate",
    name: "Late Shipment Rate",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "seller-performance-standards",
    desc: "Percentage of orders shipped after stated handling time, impacts search placement and Top Rated eligibility.",
    market: "global",
    year: 2014
  },
  {
    id: "valid-tracking-rate",
    name: "Valid Tracking Rate",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "seller-performance-standards",
    desc: "Percentage of shipments with validated carrier tracking, must meet minimum threshold for Top Rated status.",
    market: "global",
    year: 2019
  },
  {
    id: "item-not-received",
    name: "Item Not Received",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-money-back-guarantee",
    desc: "Buyer request type filed when item not delivered by estimated delivery date, defect against seller performance.",
    market: "global",
    year: 2011
  },
  {
    id: "significantly-not-as-described",
    name: "Significantly Not as Described",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "ebay-money-back-guarantee",
    desc: "Buyer claim that received item materially differs from listing description, photos, or stated condition.",
    market: "global",
    year: 2011
  },
  {
    id: "cases-closed-without-seller-resolution",
    name: "Cases Closed Without Seller Resolution",
    type: "trust",
    tier: "feature",
    status: "current",
    parent: "seller-performance-standards",
    desc: "Metric tracking cases where eBay stepped in to resolve dispute, counting as defect against seller.",
    market: "global",
    year: 2014
  },
  {
    id: "offers-sent",
    name: "Offers Sent",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "best-offer",
    desc: "Seller-initiated offers sent to interested buyers who watched or engaged with listing.",
    market: "global",
    year: 2018
  },
  {
    id: "offers-received",
    name: "Offers Received",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "best-offer",
    desc: "Buyer-initiated purchase offers submitted on listings with Best Offer enabled.",
    market: "global",
    year: 2005
  },
  {
    id: "offer-history",
    name: "Offer History",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "best-offer",
    desc: "Record of all offers sent, received, accepted, declined, and countered for a listing.",
    market: "global",
    year: 2005
  },
  {
    id: "review-offers",
    name: "Review Offers",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "seller-hub",
    desc: "Seller Hub section for managing pending Best Offers requiring accept, decline, or counter action.",
    market: "global",
    year: 2016
  },
  {
    id: "paypal",
    name: "PayPal",
    type: "category",
    tier: "platform",
    status: "legacy",
    parent: "payments",
    desc: "Third-party payment processor formerly required for eBay transactions, now optional as eBay manages payments directly.",
    market: "global",
    year: 2002,
    renamedTo: "ebay-managed-payments"
  },
  {
    id: "venmo",
    name: "Venmo",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "PayPal-owned peer-to-peer payment option available for US buyers at checkout.",
    market: "US",
    year: 2022
  },
  {
    id: "apple-pay",
    name: "Apple Pay",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Digital wallet payment option for iOS users completing checkout via Apple Pay.",
    market: ["US", "UK", "AU", "CA"],
    year: 2020
  },
  {
    id: "google-pay",
    name: "Google Pay",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Digital wallet payment option for Android users completing checkout via Google Pay.",
    market: ["US", "UK", "AU", "CA"],
    year: 2020
  },
  {
    id: "klarna",
    name: "Klarna",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Buy now, pay later financing option allowing buyers to split payments into 4 interest-free installments.",
    market: ["US", "UK", "DE"],
    year: 2021
  },
  {
    id: "credit-card",
    name: "Credit Card",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Direct credit card payment processing through eBay Managed Payments (Visa, Mastercard, Amex, Discover).",
    market: "global",
    year: 2019
  },
  {
    id: "debit-card",
    name: "Debit Card",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Direct debit card payment processing through eBay Managed Payments.",
    market: "global",
    year: 2019
  }
];
