// eBay Naming Graph - Enriched Wave 4 Batch P
// Focus: Charity Programs, Sustainability Features, Social Impact, Community Initiatives
// Generated: 2026-04-17
// Count: 50 programs

import { GraphNode } from './enriched-consolidated-DEDUPLICATED'

export const ENRICHED_WAVE4_P: GraphNode[] = [
  {
    id: "paypal-giving-fund",
    name: "PayPal Giving Fund",
    type: "impact",
    tier: "program",
    status: "current",
    parent: "charity",
    desc: "Charitable donation platform partnering with eBay for Charity - facilitates tax-deductible donations to verified nonprofits globally with zero platform fees.",
    market: "global",
    year: 2011
  },
  {
    id: "charity-listing",
    name: "Charity Listing",
    type: "impact",
    tier: "feature",
    status: "current",
    parent: "charity",
    desc: "Listing type designating charitable benefit - sellers can allocate 10-100% of sale proceeds to registered nonprofits, displayed with special badge.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2003
  },
  {
    id: "charity-percentage",
    name: "Charity Percentage",
    type: "impact",
    tier: "feature",
    status: "current",
    parent: "charity",
    desc: "Donation allocation selector for charity listings - sellers choose percentage (10-100%) of final sale price going to nonprofit organization.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2003
  },
  {
    id: "donate-now",
    name: "Donate Now",
    type: "impact",
    tier: "feature",
    status: "current",
    parent: "charity",
    desc: "Direct donation button on charity listings - buyers can make immediate tax-deductible contributions without purchasing items.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2013
  },
  {
    id: "ebay-foundation",
    name: "eBay Foundation",
    type: "impact",
    tier: "organization",
    status: "current",
    parent: "impact",
    desc: "Corporate foundation supporting economic opportunity and digital inclusion - funds nonprofits addressing digital divide and entrepreneurship education globally.",
    market: "global",
    year: 1998
  },
  {
    id: "seller-training-program",
    name: "Seller Training Program",
    type: "category",
    tier: "program",
    status: "current",
    parent: "community",
    desc: "Structured educational curriculum for new and growing sellers - covers listing optimization, shipping, customer service, and platform best practices.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2012
  },
  {
    id: "seller-webinar-series",
    name: "Seller Webinar Series",
    type: "category",
    tier: "program",
    status: "current",
    parent: "community",
    desc: "Live and recorded training sessions covering seasonal strategies, new features, and vertical-specific tactics - hosted by eBay category experts.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2015
  },
  {
    id: "seller-clinics",
    name: "Seller Clinics",
    type: "category",
    tier: "program",
    status: "current",
    parent: "community",
    desc: "In-person and virtual coaching sessions with eBay experts - personalized guidance on seller challenges and growth strategies.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "pro-seller-program",
    name: "Pro Seller Program",
    type: "category",
    tier: "program",
    status: "current",
    parent: "sellertools",
    desc: "Advanced seller tier offering priority support, beta access, and dedicated account management - invitation-only for high-volume sellers with excellent performance.",
    market: ["US", "UK", "AU"],
    year: 2019
  },
  {
    id: "seller-onramp",
    name: "Seller OnRamp",
    type: "category",
    tier: "program",
    status: "current",
    parent: "community",
    desc: "Onboarding program for new sellers providing step-by-step setup guidance, first listing support, and early success milestones tracking.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2021
  },
  {
    id: "training-calendar",
    name: "Training Calendar",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "community",
    desc: "Centralized schedule of seller webinars, workshops, and events - filterable by topic, vertical, and seller level with RSVP functionality.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2016
  },
  {
    id: "ebay-global-sellers-youtube-channel",
    name: "eBay Global Sellers YouTube Channel",
    type: "category",
    tier: "platform",
    status: "current",
    parent: "community",
    desc: "Official YouTube channel featuring seller success stories, tutorial videos, product updates, and best practices - multilingual content library.",
    market: "global",
    year: 2019
  },
  {
    id: "recommerce-report",
    name: "Recommerce Report",
    type: "impact",
    tier: "publication",
    status: "current",
    parent: "impact",
    desc: "Annual sustainability report tracking pre-owned goods impact - quantifies carbon savings, waste reduction, and circular economy contributions from eBay marketplace.",
    market: "global",
    year: 2020
  },
  {
    id: "climate-transition-plan",
    name: "Climate Transition Plan",
    type: "impact",
    tier: "program",
    status: "current",
    parent: "impact",
    desc: "Corporate climate strategy targeting carbon neutrality by 2030 - includes renewable energy commitments, emissions reduction roadmap, and supplier engagement.",
    market: "global",
    year: 2023
  },
  {
    id: "feedback-forum",
    name: "Feedback Forum",
    type: "category",
    tier: "feature",
    status: "legacy",
    parent: "community",
    desc: "Community discussion board for feedback policy questions and disputes - replaced by Resolution Center for formal cases, legacy forum archived 2018.",
    market: ["US", "UK", "CA", "AU"],
    year: 2003,
    renamedTo: "resolution-center"
  },
  {
    id: "ebay-university",
    name: "eBay University",
    type: "category",
    tier: "program",
    status: "legacy",
    parent: "community",
    desc: "Educational program offering workshops, certification courses, and traveling training events for sellers - discontinued in 2019, replaced by digital learning.",
    market: "US",
    year: 2005,
    renamedTo: "seller-training-program"
  },
  {
    id: "seller-help",
    name: "Seller Help",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "support",
    desc: "Knowledge base and self-service help portal for sellers - searchable articles, policy documentation, and troubleshooting guides.",
    market: "global",
    year: 2008
  },
  {
    id: "help-center",
    name: "Help Center",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "support",
    desc: "Unified support portal for buyers and sellers - consolidated help articles, contact options, and AI-powered chatbot assistance.",
    market: "global",
    year: 2016
  },
  {
    id: "customer-service-metrics",
    name: "Customer Service Metrics",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Seller Hub dashboard showing response time, resolution rate, and customer satisfaction scores - tracked against service level standards.",
    market: "global",
    year: 2017
  },
  {
    id: "seller-levels",
    name: "Seller Levels",
    type: "category",
    tier: "program",
    status: "current",
    parent: "sellertools",
    desc: "Tiered seller classification system (Below Standard, Above Standard, Top Rated) determining search visibility, fee discounts, and program access.",
    market: "global",
    year: 2008
  },
  {
    id: "cases-closed-without-seller-resolution",
    name: "Cases Closed Without Seller Resolution",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "performance-metrics",
    desc: "Defect metric tracking cases closed in buyer's favor without seller response - impacts seller level and search ranking.",
    market: "global",
    year: 2014
  },
  {
    id: "payment-dispute-seller-protections",
    name: "Payment Dispute Seller Protections",
    type: "trust",
    tier: "program",
    status: "current",
    parent: "seller-protections",
    desc: "Protection against unauthorized payment reversals and chargebacks - covers eligible transactions with tracking and seller policy compliance.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2020
  },
  {
    id: "seller-hub-reports",
    name: "Seller Hub Reports",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Analytics dashboard providing sales trends, traffic insights, performance metrics, and downloadable CSV reports for business intelligence.",
    market: "global",
    year: 2016
  },
  {
    id: "deals-seller-portal",
    name: "Deals Seller Portal",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "promotional-tools",
    desc: "Campaign management interface for Daily Deals submissions - sellers propose discounts, eBay merchandising team curates homepage placements.",
    market: ["US", "UK", "DE", "AU"],
    year: 2014
  },
  {
    id: "spendable-funds",
    name: "Spendable Funds",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "payments",
    desc: "Available balance in eBay managed payments account - funds immediately usable for shipping labels, seller fees, or withdrawal to bank.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2020
  },
  {
    id: "economy-shipping",
    name: "Economy Shipping",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "shipping",
    desc: "Budget shipping tier with longer delivery windows (5-10 business days) - meets buyer demand for low-cost options on non-urgent purchases.",
    market: ["US", "UK", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "speedpak-economy",
    name: "SpeedPAK Economy",
    type: "category",
    tier: "program",
    status: "current",
    parent: "international-shipping",
    desc: "Budget international shipping option within SpeedPAK network - slower transit (15-30 days) at lower rates for cross-border sellers.",
    market: "global",
    year: 2018
  },
  {
    id: "certified-recycler-program",
    name: "Certified Recycler Program",
    type: "impact",
    tier: "program",
    status: "current",
    parent: "sustainability",
    desc: "Verification program for electronics recyclers meeting e-waste standards (R2, e-Stewards) - badge displayed on recycler listings for buyer confidence.",
    market: ["UK"],
    year: 2019
  },
  {
    id: "advanced-search",
    name: "Advanced Search",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Power search interface with 20+ filters - price range, condition, location, seller type, listing format for precision item discovery.",
    market: "global",
    year: 2000
  },
  {
    id: "best-match",
    name: "Best Match",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Default search ranking algorithm balancing relevance, seller performance, listing quality, and buyer preferences - proprietary eBay Cassini engine.",
    market: "global",
    year: 2007
  },
  {
    id: "sort-by",
    name: "Sort By",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Search results ordering options - Best Match, Price Low-High, Price High-Low, Time Ending Soonest, Newly Listed, Distance Nearest.",
    market: "global",
    year: 2003
  },
  {
    id: "filter-results",
    name: "Filter Results",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Dynamic faceted search filters based on category taxonomy - condition, brand, price, location, shipping options, seller type.",
    market: "global",
    year: 2010
  },
  {
    id: "price-range",
    name: "Price Range",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Search filter allowing buyers to set minimum and maximum price boundaries - supports both auction and fixed-price listings.",
    market: "global",
    year: 2002
  },
  {
    id: "condition-filter",
    name: "Condition Filter",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Item condition facet filter - New, New with tags, New with defects, Refurbished, Used, For parts or not working.",
    market: "global",
    year: 2005
  },
  {
    id: "sold-listings",
    name: "Sold Listings",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Search filter showing completed successful sales - displays final sale price and end date for pricing research and trend analysis.",
    market: "global",
    year: 2006
  },
  {
    id: "completed-listings",
    name: "Completed Listings",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Search filter showing all ended listings regardless of sale outcome - includes unsold auctions for comprehensive market research.",
    market: "global",
    year: 2006
  },
  {
    id: "newly-listed",
    name: "Newly Listed",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Search sort showing most recently listed items first - popular for collectibles, limited edition drops, and time-sensitive purchases.",
    market: "global",
    year: 2004
  },
  {
    id: "delivery-options",
    name: "Delivery Options",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Search filter for shipping preferences - Free shipping, Fast & Free, Local pickup, International shipping available.",
    market: "global",
    year: 2012
  },
  {
    id: "lockable-filters",
    name: "Lockable Filters",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "User preference to persist selected filters across search sessions - maintains condition, price range, shipping preferences for repeat searches.",
    market: "global",
    year: 2018
  },
  {
    id: "ebay-picture-services",
    name: "eBay Picture Services (EPS)",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing-tools",
    desc: "Image hosting service providing unlimited free photo uploads with automatic resizing, cropping, and optimization for listings.",
    market: "global",
    year: 2004
  },
  {
    id: "gallery-picture",
    name: "Gallery Picture",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing-tools",
    desc: "Primary listing thumbnail displayed in search results - free first image, optimized to 500x500px for fast load times.",
    market: "global",
    year: 2000
  },
  {
    id: "gallery-plus",
    name: "Gallery Plus",
    type: "category",
    tier: "feature",
    status: "legacy",
    parent: "listing-tools",
    desc: "Premium listing upgrade showing enlarged thumbnail in search results - $1.00 fee, deprecated in 2019 with free image improvements.",
    market: "global",
    year: 2005
  },
  {
    id: "supersize-pictures",
    name: "Supersize Pictures",
    type: "category",
    tier: "feature",
    status: "legacy",
    parent: "listing-tools",
    desc: "Paid upgrade allowing high-resolution zoomable images - replaced by free unlimited large images in 2012.",
    market: "global",
    year: 2007
  },
  {
    id: "featured-categories",
    name: "Featured Categories",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "stores",
    desc: "Store customization allowing sellers to highlight top product categories in custom navigation - improves browsing and cross-selling.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2010
  },
  {
    id: "store-categories",
    name: "Store Categories",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "stores",
    desc: "Custom taxonomy for organizing store inventory - sellers create hierarchical categories independent of eBay site catalog.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2008
  },
  {
    id: "custom-storefront",
    name: "Custom Storefront",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "stores",
    desc: "Branded homepage for eBay Stores - customizable banner, colors, layout, and promotional modules for cohesive brand experience.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2009
  },
  {
    id: "transaction-defect-rate",
    name: "Transaction Defect Rate",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "performance-metrics",
    desc: "Seller performance metric tracking transactions with defects (cases, INR claims, low DSRs) - must stay under 2% for Top Rated status.",
    market: "global",
    year: 2014
  },
  {
    id: "late-shipment-rate",
    name: "Late Shipment Rate",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "performance-metrics",
    desc: "Percentage of orders shipped after stated handling time - must stay under 3% for Top Rated status, tracked via scan events.",
    market: "global",
    year: 2014
  },
  {
    id: "volume-pricing",
    name: "Volume Pricing",
    type: "category",
    tier: "program",
    status: "current",
    parent: "promotional-tools",
    desc: "Quantity-based discount tool - sellers set tiered pricing (e.g., 5% off 3+, 10% off 5+) displayed automatically on listings.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2015
  },
  {
    id: "quantity-discounts",
    name: "Quantity Discounts",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "promotional-tools",
    desc: "Automated discount applied when buyers purchase multiple quantities of same item - set minimum quantity and discount percentage.",
    market: ["US", "UK", "DE", "FR", "IT", "CA", "AU"],
    year: 2013
  }
]
