// Wave 5: April 16, 2026 Research Items - Net-New Discoveries
// 45 programs with evidence URLs not in baseline 831-node dataset

import { GraphNode } from './enriched-consolidated-DEDUPLICATED'

export const WAVE5_RESEARCH_ITEMS: GraphNode[] = [
  {
    id: "about-me",
    name: "About Me",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "sellertools",
    desc: "Free HTML-based seller profile page launched 1998 allowing sellers to personalize their eBay presence, build trust, and share background information with buyers.",
    market: "global",
    year: 1998
  },
  {
    id: "automated-promoted-listings-campaigns",
    name: "Automated Promoted Listings Campaigns",
    type: "advertising",
    tier: "feature",
    status: "current",
    parent: "promoted-listings",
    desc: "Rule-based automation for Promoted Listings with automatic ad rate adjustment, launched March 2025 to reduce manual campaign management.",
    market: "US",
    year: 2025
  },
  {
    id: "billpoint",
    name: "Billpoint",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "payments",
    desc: "Payment solution launched as beta Q4 1999, phased out January 2003 after PayPal acquisition. Precursor to eBay's managed payments infrastructure.",
    market: "US",
    year: 1999
  },
  {
    id: "butterfield-butterfield",
    name: "Butterfield & Butterfield",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "acquisitions",
    desc: "135-year-old San Francisco art and antiques auction house acquired May 1999 for ~$260M. Sold to Bonhams 2002. Early attempt to enter high-end collectibles.",
    market: "US",
    year: 1999
  },
  {
    id: "comc",
    name: "COMC",
    type: "category",
    tier: "product",
    status: "current",
    parent: "collectibles",
    desc: "Commercial agreement and investment announced Nov 2023 with trading card company managing 100M+ cards. Partnership (not acquisition) strengthening collectibles ecosystem.",
    market: "US",
    year: 2023
  },
  {
    id: "circular-fashion-innovator-of-the-year",
    name: "Circular Fashion Innovator of the Year",
    type: "impact",
    tier: "program",
    status: "current",
    parent: "circular-fashion-fund",
    desc: "Special $300K prize within Circular Fashion Fund for 2025 cohort, recognizing standout sustainability innovation in fashion resale sector.",
    market: "global",
    year: 2025
  },
  {
    id: "critical-path-software",
    name: "Critical Path Software",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "acquisitions",
    desc: "Talent acquisition completed December 2010 for mobile strategy expertise, supporting eBay's mobile app development during smartphone commerce transition.",
    market: "global",
    year: 2010
  },
  {
    id: "electronic-travel-auction",
    name: "Electronic Travel Auction",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "partnerships",
    desc: "First third-party licensing partner (November 1996) using SmartMarket Technology for travel auctions. Early proof of eBay platform licensing model.",
    market: "US",
    year: 1996
  },
  {
    id: "feedback-forum",
    name: "Feedback Forum",
    type: "trust",
    tier: "product",
    status: "current",
    parent: "trust",
    desc: "Original feedback and rating system launched February 26, 1996 by Pierre Omidyar. Foundation of eBay's trust infrastructure and peer-to-peer reputation economy.",
    market: "global",
    year: 1996
  },
  {
    id: "find-it-on-ebay",
    name: "Find It On eBay",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "search",
    desc: "Android-specific variant of Image Search launched Fall 2017 using computer vision. Also appears as campaign name in 2024 Goldin integration cross-promotion.",
    market: "US",
    year: 2017
  },
  {
    id: "gsi-commerce-ebay-enterprise",
    name: "GSI Commerce / eBay Enterprise",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "acquisitions",
    desc: "Acquired March 2011, closed June 2011. Rebranded to eBay Enterprise June 2013. E-commerce technology and fulfillment services for enterprise clients. Later divested.",
    market: "global",
    year: 2011
  },
  {
    id: "global-shipping-program",
    name: "Global Shipping Program",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "shipping",
    desc: "Cross-border shipping solution active 2013-2023, major driver of eBay export business. Coexisted with eBay International Shipping before full transition.",
    market: ["US", "UK"],
    year: 2013
  },
  {
    id: "knownorigin",
    name: "KnownOrigin",
    type: "category",
    tier: "product",
    status: "current",
    parent: "collectibles",
    desc: "Leading NFT marketplace acquired June 2022. Founded 2018 in Manchester, UK. Operates autonomously within eBay's digital collectibles ecosystem.",
    market: "global",
    year: 2022
  },
  {
    id: "kruse-international",
    name: "Kruse International",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "acquisitions",
    desc: "Automobile auctioneer acquired 1999 for $165M stock. Launched automotive category, precursor to eBay Motors. Repurchased by Dean Kruse 2002.",
    market: "US",
    year: 1999
  },
  {
    id: "mymix-fashion-campaign",
    name: "MYMIX Fashion Campaign",
    type: "category",
    tier: "campaign",
    status: "legacy",
    parent: "fashion",
    desc: "UK-specific Spring/Summer 2012 fashion marketing campaign. Part of eBay's vertical-specific marketing push during fashion category expansion.",
    market: "UK",
    year: 2012
  },
  {
    id: "magento",
    name: "Magento",
    type: "developer",
    tier: "product",
    status: "legacy",
    parent: "developer",
    desc: "E-commerce platform. Initial investment March 2010, full acquisition announced June 2011, completed August 2011. Core component of X.commerce platform. Divested 2015.",
    market: "global",
    year: 2011
  },
  {
    id: "magical-bulk-listing-tool",
    name: "Magical Bulk Listing Tool",
    type: "category",
    tier: "feature",
    status: "current",
    parent: "listing-tools",
    desc: "AI-powered extension of Magical Listing Tool launched 2024 for batch processing and multi-item listing creation, reducing time for high-volume sellers.",
    market: "US",
    year: 2024
  },
  {
    id: "mission-fish-seller-account",
    name: "Mission Fish Seller Account",
    type: "impact",
    tier: "program",
    status: "legacy",
    parent: "charity",
    desc: "Charity seller account program retired 2015, replaced by Donation Account within eBay Giving Works/eBay for Charity framework.",
    market: "US",
    year: 2003,
    renamedTo: "donation-account"
  },
  {
    id: "paypal-spinoff",
    name: "PayPal Spinoff",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "corporate",
    desc: "Corporate separation completed 2015, creating independent publicly-traded PayPal. Major strategic shift enabling eBay's Managed Payments initiative.",
    market: "global",
    year: 2015
  },
  {
    id: "safeharbor",
    name: "SafeHarbor",
    type: "trust",
    tier: "program",
    status: "legacy",
    parent: "trust",
    desc: "Early fraud and dispute reporting system launched 1999, contactable via SafeHarbor@eBay.com. Precursor to modern Trust & Safety programs and Resolution Center.",
    market: "US",
    year: 1999
  },
  {
    id: "shoprunner",
    name: "ShopRunner",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "acquisitions",
    desc: "Premium shipping service acquired as part of GSI Commerce 2011, mostly divested. eBay had minority ownership 2011-2013 during enterprise commerce push.",
    market: "US",
    year: 2011
  },
  {
    id: "smartmarket-technology",
    name: "SmartMarket Technology",
    type: "developer",
    tier: "platform",
    status: "legacy",
    parent: "developer",
    desc: "eBay's auction platform technology licensed to Electronic Travel Auction (November 1996). First third-party licensing deal. Internal technology brand.",
    market: "US",
    year: 1996
  },
  {
    id: "tcgplayer",
    name: "TCGplayer",
    type: "category",
    tier: "product",
    status: "current",
    parent: "collectibles",
    desc: "Collectible card game marketplace acquired October 2022 for ~$295M. Operates autonomously serving trading card enthusiasts with integrated authentication services.",
    market: "US",
    year: 2022
  },
  {
    id: "tcgplayer-authentication-center",
    name: "TCGplayer Authentication Center",
    type: "trust",
    tier: "program",
    status: "current",
    parent: "tcgplayer",
    desc: "Authentication service operated by TCGplayer for grading and verifying collectible trading cards. Integrated with eBay Authenticity Guarantee ecosystem.",
    market: "US",
    year: 2022
  },
  {
    id: "tcgplayer-marketplace",
    name: "TCGplayer Marketplace",
    type: "category",
    tier: "product",
    status: "current",
    parent: "tcgplayer",
    desc: "Trading card marketplace platform within TCGplayer. Primary buying/selling interface for collectible card games community.",
    market: "US",
    year: 2022
  },
  {
    id: "techstars-future-of-ecommerce",
    name: "Techstars Future of Ecommerce powered by eBay",
    type: "developer",
    tier: "program",
    status: "current",
    parent: "developer",
    desc: "Accelerator program launched September 2023 in partnership with Techstars, supporting startups building next-generation e-commerce solutions.",
    market: "US",
    year: 2023
  },
  {
    id: "things-people-love",
    name: "Things.People.Love",
    type: "category",
    tier: "campaign",
    status: "current",
    parent: "marketing",
    desc: "Creative platform and brand strategy launched 2024 with eBay Evo design system. Unified messaging framework highlighting eBay's unique product assortment.",
    market: "global",
    year: 2024
  },
  {
    id: "tise",
    name: "Tise",
    type: "category",
    tier: "product",
    status: "current",
    parent: "acquisitions",
    desc: "Norway-based C2C social marketplace for Gen Z/Millennial secondhand fashion acquired October 2025. eBay Ventures invested 2022 before full acquisition.",
    market: ["NO", "EU"],
    year: 2025
  },
  {
    id: "twice-acquisition",
    name: "Twice",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "acquisitions",
    desc: "Clothing resale startup acquired July 2015 as bolt-on acquisition for eBay Valet fashion category expansion. Integrated into Valet service.",
    market: "US",
    year: 2015
  },
  {
    id: "up4sale",
    name: "Up4Sale",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "acquisitions",
    desc: "Trading site acquired 1998 during early eBay expansion phase. One of earliest acquisition-driven category expansions.",
    market: "US",
    year: 1998
  },
  {
    id: "xcommerce",
    name: "X.commerce",
    type: "developer",
    tier: "platform",
    status: "legacy",
    parent: "developer",
    desc: "Unified eBay/PayPal/Magento developer ecosystem announced October 2011 at Innovate conference. Active 2011-2013 era during open commerce platform push.",
    market: "global",
    year: 2011
  },
  {
    id: "you-cant-fake-fashion-campaign",
    name: "YOU CAN'T FAKE FASHION Campaign",
    type: "category",
    tier: "campaign",
    status: "legacy",
    parent: "fashion",
    desc: "Major fashion authenticity initiative launched 2011 with CFDA partnership featuring 75+ American designers. Part of fashion vertical trust-building strategy.",
    market: "US",
    year: 2011
  },
  {
    id: "zong-mobile-payments",
    name: "Zong",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "payments",
    desc: "Mobile payments via carrier billing, part of X.commerce platform 2011. Early mobile commerce payment experimentation during smartphone transition.",
    market: "global",
    year: 2011
  },
  {
    id: "ebay-4-0-mobile-app",
    name: "eBay 4.0",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "mobile",
    desc: "Major mobile app version from mobile-first transformation era. Significant milestone in eBay's app evolution and smartphone commerce strategy.",
    market: "global",
    year: 2012
  },
  {
    id: "ebay-bucks",
    name: "eBay Bucks",
    type: "category",
    tier: "program",
    status: "legacy",
    parent: "loyalty",
    desc: "First-ever free cashback rewards program publicly launched August 2010 after year-long pilot. Earned on purchases, redeemable for future eBay shopping.",
    market: "US",
    year: 2010
  },
  {
    id: "ebay-fashion-app",
    name: "eBay Fashion App",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "mobile",
    desc: "Vertical-specific mobile app for fashion category retired 2015. Functionality migrated to flagship eBay app as part of app consolidation strategy.",
    market: "US",
    year: 2013
  },
  {
    id: "ebay-innovate-developer-conference",
    name: "eBay Innovate Developer Conference",
    type: "developer",
    tier: "event",
    status: "legacy",
    parent: "developer",
    desc: "Annual developer conference held 2011 (minimum). Announced X.commerce platform. Predecessor/alternative to eBay Open conference series.",
    market: "global",
    year: 2011
  },
  {
    id: "ebay-milo",
    name: "eBay Milo",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "acquisitions",
    desc: "Local shopping engine acquired December 2010 for online-to-offline commerce strategy. Integrated into RedLaser. Served $917B local retail market opportunity.",
    market: "US",
    year: 2010
  },
  {
    id: "ebay-mobile-app-android",
    name: "eBay Mobile App (Android)",
    type: "category",
    tier: "product",
    status: "current",
    parent: "mobile",
    desc: "Android mobile app launched February 16, 2010. Early mover in mobile commerce alongside iOS app during smartphone adoption wave.",
    market: "global",
    year: 2010
  },
  {
    id: "ebay-moda-latin-america",
    name: "eBay Moda",
    type: "regional",
    tier: "product",
    status: "legacy",
    parent: "fashion",
    desc: "Regional fashion app launched September 2013 for Latin America market. Localized shopping experience for fashion vertical in LATAM.",
    market: ["MX", "BR", "AR"],
    year: 2013
  },
  {
    id: "ebay-now",
    name: "eBay Now",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "shipping",
    desc: "Same-day delivery service launched 2012, retired 2015. Pilots in SF, NYC, San Jose. Early experiment in rapid fulfillment competing with Amazon Prime.",
    market: "US",
    year: 2012
  },
  {
    id: "ebay-playbook",
    name: "eBay Playbook",
    type: "category",
    tier: "product",
    status: "current",
    parent: "marketing",
    desc: "Comprehensive brand guide with 280+ pages and 2700+ images/videos. Part of eBay Evo initiative establishing unified design system and brand standards.",
    market: "global",
    year: 2024
  },
  {
    id: "ebay-redlaser",
    name: "eBay RedLaser",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "acquisitions",
    desc: "Barcode scanning iPhone app acquired June 2010 with 2M+ downloads. Reached 9M downloads by March 2011. Core mobile shopping tool 2010-2015 era.",
    market: "global",
    year: 2010
  },
  {
    id: "ebay-valet",
    name: "eBay Valet",
    type: "category",
    tier: "product",
    status: "legacy",
    parent: "services",
    desc: "Consignment service launched June 2014 where eBay handles selling for users. Closed 2018. Included Twice acquisition for fashion expansion.",
    market: "US",
    year: 2014
  }
]
